### PR TITLE
fix: surface the status of listeners when MergeGateways enabled

### LINKED ISSUE #2668: Conflicted listener status is not surfaced for gateways when MergeGateways enabled
*Description*:

Applying these config, the listener of GTW `merged-eg-3` is conflicted with the listener GTW `merged-eg-2`. But there is no status surfaced about these conflicted listener.

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: mg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: merged-eg-1
  namespace: default
spec:
  gatewayClassName: mg
  listeners:
     - name: http
       port: 8080
       protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: merged-eg-2
  namespace: default
spec:
  gatewayClassName: mg
  listeners:
     - name: http
       port: 8081
       protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: merged-eg-3
  namespace: default
spec:
  gatewayClassName: mg
  listeners:
     - name: http
       port: 8081
       protocol: HTTP
```

According to the validation method, the conflicted status should be computed, but somehow is not surfaced.

https://github.com/envoyproxy/gateway/blob/4c79ef9aa1e06d3b61b83e95f21d1705fa6568ba/internal/gatewayapi/validate.go#L541

```console
k get gtw -o yaml                                                 ✱

apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1","kind":"Gateway","metadata":{"annotations":{},"name":"merged-eg-1","namespace":"default"},"spec":{"gatewayClassName":"mg","listeners":[{"name":"http","port":8080,"protocol":"HTTP"}]}}
    creationTimestamp: "2024-02-21T14:43:57Z"
    generation: 1
    name: merged-eg-1
    namespace: default
    resourceVersion: "7869"
    uid: 2285a144-8c92-4ab3-81d4-fd485723f246
  spec:
    gatewayClassName: mg
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 8080
      protocol: HTTP
  status:
    addresses:
    - type: IPAddress
      value: 172.18.255.200
    conditions:
    - lastTransitionTime: "2024-02-21T14:43:58Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-02-21T14:43:58Z"
      message: Address assigned to the Gateway, 1/1 envoy Deployment replicas available
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
- apiVersion: gateway.networking.k8s.io/v1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1","kind":"Gateway","metadata":{"annotations":{},"name":"merged-eg-2","namespace":"default"},"spec":{"gatewayClassName":"mg","listeners":[{"name":"http","port":8081,"protocol":"HTTP"}]}}
    creationTimestamp: "2024-02-21T14:43:57Z"
    generation: 1
    name: merged-eg-2
    namespace: default
    resourceVersion: "7870"
    uid: 27440145-0932-46dd-aba1-d8dcf53a7f0d
  spec:
    gatewayClassName: mg
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 8081
      protocol: HTTP
  status:
    addresses:
    - type: IPAddress
      value: 172.18.255.200
    conditions:
    - lastTransitionTime: "2024-02-21T14:43:58Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-02-21T14:43:58Z"
      message: Address assigned to the Gateway, 1/1 envoy Deployment replicas available
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
- apiVersion: gateway.networking.k8s.io/v1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1","kind":"Gateway","metadata":{"annotations":{},"name":"merged-eg-3","namespace":"default"},"spec":{"gatewayClassName":"mg","listeners":[{"name":"http","port":8081,"protocol":"HTTP"}]}}
    creationTimestamp: "2024-02-21T14:43:57Z"
    generation: 1
    name: merged-eg-3
    namespace: default
    resourceVersion: "7871"
    uid: 7bc0dc08-f145-4310-b18d-6dc86a123151
  spec:
    gatewayClassName: mg
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 8081
      protocol: HTTP
  status:
    addresses:
    - type: IPAddress
      value: 172.18.255.200
    conditions:
    - lastTransitionTime: "2024-02-21T14:43:58Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-02-21T14:43:58Z"
      message: Address assigned to the Gateway, 1/1 envoy Deployment replicas available
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
kind: List
metadata:
  resourceVersion: ""
```

*Environment*:

lattest

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2668

### CODE REVIEW

File: internal/provider/kubernetes/predicates.go [hunk 1]
```diff
@@ -226,9 +229,15 @@ func (r *gatewayAPIReconciler) validateServiceForReconcile(obj client.Object) bo
...
+					key := types.NamespacedName{Namespace: gtw.Namespace, Name: gtw.Name}
+					if err := r.client.Get(ctx, key, curGtw); err != nil {
+						r.log.Info("gateway not found", "gatewayclass", gclass, "name", key.String())
+						return false
+					}
+
+					r.updateStatusForGateway(ctx, curGtw)
 				}
 			}
 		}
```
Comment (cnvergence) [inline internal/provider/kubernetes/predicates.go:243]: I was more thinking about something like this, wdyt?
```bash
	gclass, ok := labels[gatewayapi.OwningGatewayClassLabel]
	if ok && r.mergeGateways[gclass] {
		gatewayList := &gwapiv1.GatewayList{}
		if err := r.client.List(ctx, gatewayList, &client.ListOptions{
			FieldSelector: fields.OneTermEqualSelector(classGatewayIndex, gclass),
		}); err != nil {
			r.log.Info("no associated Gateways found for GatewayClass", "name", gclass)
		}
		if len(gatewayList.Items) > 0 {
			for _, gw := range gatewayList.Items {
				gw := gw
				r.updateStatusForGateway(ctx, &gw)
			}

		}
		return false
	}
```

Comment (cnvergence) [reply internal/provider/kubernetes/predicates.go:243]: we could move it also to separate func like r.findOwningGateways

**Review by cnvergence — CHANGES_REQUESTED** [review]

File: internal/provider/kubernetes/predicates.go (hunk 1 above)
Comment (shawnh2) [reply internal/provider/kubernetes/predicates.go:243]: @cnvergence one question: for example, if we got A,B,C three gateways, and the listener conflict only happened between B and C. what we expected to see:
- (1) A, B should works but C should not;
- (2) neither of A, B, C should work;

Comment (cnvergence) [reply internal/provider/kubernetes/predicates.go:243]: we should set the option A, meaning that the newest gateway with conflict will get rejected

Comment (cnvergence) [reply internal/provider/kubernetes/predicates.go:243]: this is expected behaviour https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/testdata/merge-invalid-multiple-gateways.out.yaml

Comment (shawnh2) [reply internal/provider/kubernetes/predicates.go]: updated, thanks for answering

File: internal/provider/kubernetes/predicates.go [hunk 2]
```diff
@@ -450,6 +443,23 @@ func (r *gatewayAPIReconciler) findOwningGateway(ctx context.Context, labels map
...
+		FieldSelector: fields.OneTermEqualSelector(classGatewayIndex, gatewayClassName),
+	}); err != nil {
+		return err
+	}
+
+	for _, gateway := range gateways.Items {
+		gateway := gateway
+		r.updateStatusForGateway(ctx, &gateway)
+	}
+
```
Comment (cnvergence) [inline internal/provider/kubernetes/predicates.go:459]:
```suggestion
        if len(gateways.Items) > 0 {
	        for _, gateway := range gateways.Items {
		        gateway := gateway
		        r.updateStatusForGateway(ctx, &gateway)
	        }
        }
```

Comment (cnvergence) [reply internal/provider/kubernetes/predicates.go:459]: let's add the check

File: internal/provider/kubernetes/predicates.go [hunk 3]
```diff
@@ -213,24 +213,22 @@ func (r *gatewayAPIReconciler) validateServiceForReconcile(obj client.Object) bo
 	}
 	labels := svc.GetLabels()
 
-	// Check if the Service belongs to a Gateway, if so, update the Gateway status.
-	gtw := r.findOwningGateway(ctx, labels)
-	if gtw != nil {
-		r.updateStatusForGateway(ctx, gtw)
-		return false
+	// Only services in the configured namespace should be reconciled.
+	if svc.Namespace == r.namespace {
```
Comment (cnvergence) [inline internal/provider/kubernetes/predicates.go:217]: this added condition break provider tests

**Comment by arkodg** [comment]
@shawnh2 @cnvergence trying to understand the bug here, there are 2 paths for writing back status for `Gateway`
1) from gateway-api->provider for `Gateway.Status.Conditions`
2)  provider reconciles the deployment/service associated with the `Gateway` and we update the `Gateway.Address` and also `Gateway.Status.Conditions`

The above PR is working on a fix in 2., trying to understand how that is related since the new Condition is coming from 1.
Was 2. wiping out 1. ?

File: internal/provider/kubernetes/predicates.go (hunk 3 above)
Comment (shawnh2) [reply internal/provider/kubernetes/predicates.go]: reverted

File: internal/provider/kubernetes/predicates.go (hunk 2 above)
Comment (shawnh2) [reply internal/provider/kubernetes/predicates.go:461]: I don't think this extra check for the loop is necessary, since the loop will not start if `gateways.Item` is empty.

Instead I have added this check to return error if `gateways.Item` is empty, meaning no gateways found under the specific gatewayclass.

Comment (cnvergence) [reply internal/provider/kubernetes/predicates.go:461]: works either way, thanks

**Review by cnvergence — APPROVED** [review]
LGTM

**Review by Xunzhuo — APPROVED** [review]
/lgtm
