### PR TITLE
fix: header modifier doesn't permit multiple values with commas

### LINKED ISSUE #5733: ResponseHeaderModifier does not permit to set a content with commas
*Description*:
>I cannot set `Cache-Control: foo,bar` with ResponseHeaderModifier

*Repro steps*:

1. Deploy the quickstart example
2. Apply the following HTTPRoute:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
      weight: 1
    filters:
    - responseHeaderModifier:
        set:
        - name: Cache-Control
          value: private, no-store
      type: ResponseHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
```

3. Run the following curl command:

curl -i http://${ENVOY_GATEWAY_IP}/-H 'Host: www.example.com' -H 'X-Echo-Set-Header: Cache-control: value1' | grep ^cache-control
You will see This:
```
cache-control:  no-store
```

Expected output:
```
cache-control: private, no-store
```

Proxy config extract:
```
          "response_headers_to_add": [
           {
            "header": {
             "key": "Cache-Control",
             "value": "private"
            },
            "append_action": "OVERWRITE_IF_EXISTS_OR_ADD"
           },
           {
            "header": {
             "key": "Cache-Control",
             "value": " no-store"
            },
            "append_action": "OVERWRITE_IF_EXISTS_OR_ADD"
           }
          ],
```

### PR DESCRIPTION
**Pull request by kkk777-7**
**What this PR does / why we need it**:
Fixed an issue where some values were missing when multiple comma-separated values were specified in HeaderModifier set.

**Root cause**
The issue occurs because comma-separated input is stored as intermediate array data, and in the case of set, Envoy’s `corev3.HeaderValueOption_OVERWRITE_IF_EXISTS_OR_ADD` is used, which results in only the last element being added.
https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/route.go#L595

According to RFC 7230, when multiple values share the same header field name, it is recommended to send them as a comma-separated value. Therefore, stopped storing intermediate data as an array separated by commas.

**Which issue(s) this PR fixes**:

Fixes #5733 

Release Notes: Yes

### CODE REVIEW

File: internal/gatewayapi/filters.go [hunk 1]
```diff
@@ -439,7 +439,7 @@ func (t *Translator) processRequestHeaderModifierFilter(
 			newHeader := ir.AddHeader{
 				Name:   headerKey,
 				Append: true,
-				Value:  strings.Split(addHeader.Value, ","),
+				Value:  []string{addHeader.Value},
```
Comment (arkodg) [inline internal/gatewayapi/filters.go:442]: doesnt this break request header case, fixed by https://github.com/envoyproxy/gateway/pull/4031 ?

Comment (kkk777-7) [reply internal/gatewayapi/filters.go:442]: Exactly. I’m currently reconsidering whether the approach in #4031 is indeed the correct one.

my understanding is that when a header field contains comma-separated values, 
Envoy should, as a proxy, pass the header through without splitting the values.
(I’m not very familiar with this area, so I might be mistaken 😅)

Comment (kkk777-7) [reply internal/gatewayapi/filters.go:442]: I’ll check how other OSS projects handle this.

Comment (maevii) [reply internal/gatewayapi/filters.go:442]: FWIW, just my opinion as a user/outsider tracking this:

> Envoy should, as a proxy, pass the header through without splitting the values.

This would be the expected behavior to me.

[Permissions-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Permissions-Policy#examples) for example can either be sent as multiple headers or a single comma-separated one, but it's usually sent comma-separated (especially when it [ends up being massive](https://github.com/w3c/webappsec-permissions-policy/issues/189#issuecomment-2615939970), where splitting it up would actually incur measurable response size overhead). I don't think there's any reason envoy should unnecessarily split it up, and IIRC nginx also sends comma-separated headers as-is.

Comment (kkk777-7) [reply internal/gatewayapi/filters.go:442]: @azey7f 
thanks for your insight !
From a quick look at Istio’s code and documentation, it seems that Istio also doesn’t perform any splitting.

**Review by arkodg — APPROVED** [review]
