### PR TITLE
fix: validation for certificates

### LINKED ISSUE #7608: ClientTrafficPolicy: Single expired client certificate CA in caCertificateRefs breaks gateway
*Description*:

Expired CAs in client trust bundle cause gateway to stop working. All incoming requests are rejected with bad status code ("direct  reponse").

Background Info: We have an gateway with multiple  "client CAs" configured. When a CA is renewed both the  old and new CA are configured for the gateway and at some point the old one will expire and later on be removed.We observed that after a CA expired the gateway stopped working.

*Repro steps*:

Configure gateway with currently valid and expired CA.

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-mtls
  namespace: mygwns
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mygw
  headers:
    xForwardedClientCert:
      mode: SanitizeSet
      certDetailsToAdd: ["Cert"] # can be Subject, Cert, Chain, DNS, URI
    requestID: PreserveOrGenerate
  tls:
    clientValidation:
      optional: true # the client can provide no certificate
      caCertificateRefs:
        - kind: "Secret"
          group: ""
          name: "gateway-mtls-trustbundle" # contains multiple CA certificates
```

After removing the expired CA the gateway started working again. I can try to provide a minimal repro sample. But wanted to post the problem now, in case someone else runs into it.

*Environment*:
 
- Hosted on Azure Kubernetes Service.
- Envoy gateway helm release 1.5.3

*Logs*:

In the logs we saw incoming requests being answereed with  a  `response_code_details: direct_response`,  and `response_code: 500` without error flags or any information pointing to the underlying problem.

```json
{
    /* snippy */
    ":authority": "example.com",
    "bytes_received": 0,
    "bytes_sent": 0,
    "connection_termination_details": null,
    "downstream_local_address": "1.2.3.4:10443",
    "downstream_remote_address": "2.3.4.5:50384",
    "duration": 0,
    "method": "POST",
    "protocol": "HTTP/1.1",
    "requested_server_name": "example.com",
    "response_code": 500,
    "response_code_details": "direct_response",
    "response_flags": "-",
    "route_name": "httproute/myapp/myroute/rule/0/match/0/myrule",
    "start_time": "2025-11-26T09:33:13.915Z",
    "upstream_cluster": null,
    "upstream_host": null,
    "upstream_local_address": null
}
```

### PR DESCRIPTION
**Pull request by kkk777-7**
**What this PR does / why we need it**:

Fix CA certificate validation.

Currently, CA certificate validation only check first block.
So, if user stores the CA bundle in Secret and first block is invalid (e.g. expired certificate), CA certificate validation fails.
This behavior causes #7608.

Fixed: 
Support validating all block.  and invalid block is exclude.
If no valid certificates exist, return ListenerError with `InvalidCertificateRef` condition.
If valid certificates exist and invalid certificates exist, return ListenerError with `PartiallyInvalidCertificateRef` condition.

### Related PR
https://github.com/envoyproxy/gateway/pull/7909

### Tests
- [x] If no valid certificates exist in Secret, return 500 response.
  - https://github.com/envoyproxy/gateway/blob/96bc26c381419d22514ecfd5fa813348da958eeb/internal/gatewayapi/testdata/clienttrafficpolicy-mtls-cert-bundle-both-invalid.out.yaml
- [x] If one valid certificate exists and one invalid certificate exists, don't return 500 response and only contains valid certificate in xdsIR
  - https://github.com/envoyproxy/gateway/blob/96bc26c381419d22514ecfd5fa813348da958eeb/internal/gatewayapi/testdata/clienttrafficpolicy-mtls-cert-bundle.out.yaml
- [x] If both valid certificates exist, contains both valid certificates in xdsIR
  - https://github.com/envoyproxy/gateway/blob/96bc26c381419d22514ecfd5fa813348da958eeb/internal/gatewayapi/testdata/clienttrafficpolicy-mtls-cert-bundle-both-valid.out.yaml

**Which issue(s) this PR fixes**:

Fixes #7608 

Release Notes: Yes

### Related and Reference Issue
https://github.com/kubernetes/ingress-nginx/issues/4234#issuecomment-530868054

### CODE REVIEW

File: internal/gatewayapi/tls.go [hunk 1]
```diff
@@ -96,26 +98,66 @@ func parseCertsFromTLSSecretsData(secrets []*corev1.Secret) ([]*x509.Certificate
...
+		// Only include this PEM block if all certificates in it are valid
+		if blockValid {
+			validData = append(validData, pem.EncodeToMemory(block)...)
+			validPemCount++
 		}
 	}
-	return nil
+
+	// Return error if no valid certificates were found
+	if validPemCount == 0 {
```
Comment (rudrakhp) [inline internal/gatewayapi/tls.go]: Why can't we rely on `len(validData)`?

File: internal/gatewayapi/tls.go [hunk 2]
```diff
@@ -96,26 +98,66 @@ func parseCertsFromTLSSecretsData(secrets []*corev1.Secret) ([]*x509.Certificate
...
+		if len(errs) > 0 {
+			return nil, errors.Join(errs...)
+		}
+		// No errors but no valid PEM blocks found - PEM decoding failed
+		return nil, fmt.Errorf("unable to decode pem data for certificate")
+	}
+	return validData, nil
```
Comment (rudrakhp) [inline internal/gatewayapi/tls.go:227]: We are not returning the expired cert errors here if there is a valid cert. IMO we should return the error and log it as warning if `validData` is non empty.

**Comment by kkk777-7** [comment]
@rudrakhp 
thanks for your comments!  and sorry for delay response.
currently, I'm handling another issue which is related to this.  https://github.com/envoyproxy/gateway/pull/7909

I’d appreciate it if I could address 7909 first, then I’ll handle this.

File: internal/gatewayapi/tls.go (hunk 2 above)
Comment (arkodg) [reply internal/gatewayapi/tls.go:227]: +1

File: internal/gatewayapi/tls.go (hunk 1 above)
Comment (kkk777-7) [reply internal/gatewayapi/tls.go]: my bad, you're correct. I've fixed.

File: internal/gatewayapi/tls.go (hunk 2 above)
Comment (kkk777-7) [reply internal/gatewayapi/tls.go:227]: thanks @rudrakhp @arkodg , I've updated the logic.

if no valid certs exist, returns custom error with `InvalidCertificateRef` Reason,
and if valid and invalid certs exist, returns custom error with `PartiallyInvalidCertificateRef` Reason.

**Comment by kkk777-7** [comment]
hi @rudrakhp , @arkodg , @zhaohuabing , please review it when you have a moment.

**Review by arkodg — DISMISSED** [review]

**Review by zirain — DISMISSED** [review]

**Comment by zirain** [comment]
@kkk777-7 can you fix the conflict?

**Review by zhaohuabing — DISMISSED** [review]
