### PR TITLE
fix: Do not set backendRequestTimeout when Retries are set

### LINKED ISSUE #6414: Dont set backendRequestTimeout to Request Timeout when Retries are set
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: The expected value isn't returned, etc.

https://github.com/envoyproxy/gateway/blob/1376cae998ad5cea54bae765914908ee08a6121e/internal/gatewayapi/route.go#L328 should only be set when Retries are unset
https://github.com/envoyproxy/gateway/blob/1376cae998ad5cea54bae765914908ee08a6121e/internal/gatewayapi/route.go#L358

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by sudiptob2**
Fixes #6414

### CODE REVIEW

File: internal/gatewayapi/route.go [hunk 1]
```diff
@@ -327,7 +327,7 @@ func processRouteTimeout(irRoute *ir.HTTPRoute, rule gwapiv1.HTTPRouteRule) {
 
 		// Also set the IR Route Timeout to the backend request timeout
 		// until we introduce retries, then set it to per try timeout
-		if rule.Timeouts.BackendRequest != nil {
+		if rule.Timeouts.BackendRequest != nil && rule.Retry == nil {
```
Comment (rudrakhp) [inline internal/gatewayapi/route.go:331]: Should we simply skip setting timeout or set something in status so it's clear that this value is being disregarded? Or a log maybe?

Comment (arkodg) [reply internal/gatewayapi/route.go:331]: the logic based on the spec, so it shouldnt confuse user imo, its a bug

Comment (arkodg) [reply internal/gatewayapi/route.go:331]: @sudiptob2 can you update the comment on L320, and update it so its valid e.g. // Only set Route timeout to BackendRequest when Retries are not set

Comment (sudiptob2) [reply internal/gatewayapi/route.go:331]: Thanks for the review 🚀 Comment updated.

**Review by zirain — APPROVED** [review]
