### PR TITLE
gatewayapi: validate tls secret in listener certificateRef

### LINKED ISSUE #783: Enable GatewayInvalidTLSConfiguration conformance test
Seeing this conformance test fail in in https://github.com/envoyproxy/gateway/pull/780

Once fixed it should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

### PR DESCRIPTION
**Pull request by LanceEa**
Previously, the tls secret referenced in a listener certifcateRef would only validate that data existed within the `tls.key` and `tls.cert` fields. This adds additional validation to ensure the data in the `tls.cert` is a valid pem encoded cert and  the `tls.key` contains a valid pem encoded private key. The GatewayInvalidTLSConfiguration conformance test can now be enabled and passes.

Fixes #783

### CODE REVIEW

**Comment by LanceEa** [comment]
Ok, sorry for all the pushed commits and fixups. I should finish my coffee before doing early morning PR's 😄. 

I fixed up the lint issue reported by CI and the broken gatewayapi tests. With the new validation logic a few of the tests with TLS now require valid tls secrets for the inputs and expected outputs so I have adjusted those test so they match the new tls validation behavior.

**Comment by LanceEa** [comment]
Looks like my fixup commits didn't get the DCO. Let me know if you need me to squash those or I think the project squash merges so that should take care of them.

**Comment by danehans** [comment]
@LanceEa each commit needs to be signed for the DCO job to pass.

File: internal/gatewayapi/tls.go [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+// validateTLSSecretData ensures the cert and key provided in a secret
+// is not malformed and can be properly parsed.
+func validateTLSSecretData(secret *corev1.Secret) error {
+
+	certData := secret.Data[corev1.TLSCertKey]
+
+	certBlock, _ := pem.Decode(certData)
+	if certBlock == nil {
+		return fmt.Errorf("unable to parse pem data in %s", corev1.TLSCertKey)
```
Comment (arkodg) [inline internal/gatewayapi/tls.go:24]: dont think we should be logging the key value

File: internal/gatewayapi/tls.go [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+	}
+
+	_, err := x509.ParseCertificate(certBlock.Bytes)
+	if err != nil {
+		return fmt.Errorf("unable to parse certificate in %s: %w", corev1.TLSCertKey, err)
```
Comment (arkodg) [inline internal/gatewayapi/tls.go:29]: same as above

File: internal/gatewayapi/tls.go [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+	}
+
+	keyData := secret.Data[corev1.TLSPrivateKeyKey]
+
+	keyBlock, _ := pem.Decode(keyData)
+	if keyBlock == nil {
+		return fmt.Errorf("unable to decode pem data in %s", corev1.TLSCertKey)
```
Comment (arkodg) [inline internal/gatewayapi/tls.go:36]: same as above, lets not log the secret content, but maybe the name of the secret and unparsable attribute

File: internal/gatewayapi/tls.go [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+	}
+
```
Comment (arkodg) [inline internal/gatewayapi/tls.go:38]: instead of parsing all types, you could switch on `keyBlock.Type` and use the specific parsing function instead

File: internal/gatewayapi/tls.go (hunk 1 above)
Comment (haq204) [reply internal/gatewayapi/tls.go:24]: `corev1.TLSCertKey` is an alias to the key name inside the secret https://github.com/kubernetes/api/blob/master/core/v1/types.go#L6372. 

But moreover, do we want to enforce that secrets be of type `kubernetes.io/tls`? I don't think the conformance test actually enforces this so it would be a restriction we would be apply additionally applying

Comment (arkodg) [reply internal/gatewayapi/tls.go:24]: @haq204 I think its okay to start with this strict check since that is the only type we support today, we can loosen it as we start supporting other types which the API supports
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayTLSConfig

File: internal/gatewayapi/tls.go (hunk 3 above)
Comment (arkodg) [reply internal/gatewayapi/tls.go:36]: 🙈

File: internal/gatewayapi/tls.go (hunk 2 above)
Comment (arkodg) [reply internal/gatewayapi/tls.go:29]: 🙈

File: internal/gatewayapi/tls.go (hunk 1 above)
Comment (LanceEa) [reply internal/gatewayapi/tls.go:24]: @haq204 - This internal helper function is currently written with the assumption that the secret is valid because it is done in the main validate function as seen here: https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/validate.go#L314 

@arkodg - That is just the key so that it gives the user an additional indication of which part of the secret is bad...is the cert or the key. Do you still want me to remove it and make it generic or hard code the key in place?

Comment (arkodg) [reply internal/gatewayapi/tls.go:24]: @LanceEa it should be perfectly fine to keep the error strings as is, was a mistake on my end

**Comment by LanceEa** [comment]
Sorry for the pain with the forced push,  I went ahead and squashed the fixup commits to address the DCO and addressed feedback. I will be sure to get the DCO applied to fixup commits too, in the future.

**Review by arkodg — APPROVED** [review]
LGTM, thanks for fixing this !
