### PR TITLE
fix: fail fast when unrecoverable discovery errors happens on checking optional CRDs

### LINKED ISSUE #7871: Optional CRDs skipped when discovery errors are treated as “absent”
*Description*:
Kubernetes discovery can time out or hit other unrecoverable errors. `crdExists` treats these errors as if the CRD is missing, so optional CRDs such as SecurityPolicy never reconcile. Envoy Gateway continues with incomplete input, and connected Envoys can retain partial XDS state, causing traffic/auth disruption.

Expected behaviors: if unrecoverable discovery errors (timeouts, connection failures, etc.) happen when the controller starts watching resources, it should fail fast and exit so the EG pod restarts, and only explicit NotFound/NoMatch should be treated as “CRD absent” for optional resources.

### PR DESCRIPTION
**Pull request by zhaohuabing**
**What type of PR is this?**

This PR adds retries to the controller when it fails to discover optional CRDs from the API server. If all retries fail, the error is propagated and causes the EG pod to restart. This prevents the EG pod from reconciling incomplete resources and serving partial xDS configuration to Envoy.

It also propagates runner startup errors to the server, so the Envoy Gateway process can exit and restart cleanly. Previously, runner startup failures were only logged, and Envoy Gateway continued running even with failed runners. 

Fixes #7871

Release Notes: Yes

### CODE REVIEW

File: internal/provider/kubernetes/controller.go [hunk 1]
```diff
@@ -2703,28 +2757,56 @@ func (r *gatewayAPIReconciler) processEnvoyProxy(ep *egv1a1.EnvoyProxy, resource
...
+		Steps:    4,
+	})
+}
+
+func (r *gatewayAPIReconciler) crdExistsWithClient(ctx context.Context, discoveryClient discovery.DiscoveryInterface, kind, groupVersion string, backoff wait.Backoff) (bool, error) {
+	var apiResourceList *metav1.APIResourceList
+	var lastErr error
+	notFound := false
+
+	err := wait.ExponentialBackoffWithContext(ctx, backoff, func(ctx context.Context) (bool, error) {
```
Comment (zhaohuabing) [inline internal/provider/kubernetes/controller.go]: Should we keep retrying transient errors until it finally succeed instead of throwing the errors to the out layer and restarting the EG? 

@arkodg would appreciate your input on this.

Comment (zhaohuabing) [reply internal/provider/kubernetes/controller.go]: I think we could retry more times and restart EG if it still can’t recover after that.

File: internal/cmd/server.go [hunk 2]
```diff
@@ -80,27 +80,32 @@ func server(ctx context.Context, stdout, stderr io.Writer, asyncErrorNotifier *m
 	runnersDone := make(chan struct{})
 	hook := func(c context.Context, cfg *config.Server) error {
 		cfg.Logger.Info("Start runners")
+		defer func() { runnersDone <- struct{}{} }()
```
Comment (zhaohuabing) [inline internal/cmd/server.go]: Would this block startRunners when config files change? cc @mathetake @zirain

Comment (zhaohuabing) [reply internal/cmd/server.go]: Oh the config loader run hook in a separate go routine every time.

Comment (zhaohuabing) [reply internal/cmd/server.go]: This may cause go routine leak, try to fix it with https://github.com/envoyproxy/gateway/pull/7880.

File: internal/provider/kubernetes/controller.go [hunk 3]
```diff
@@ -2703,28 +2757,68 @@ func (r *gatewayAPIReconciler) processEnvoyProxy(ep *egv1a1.EnvoyProxy, resource
...
-	found := false
-	for _, list := range apiResourceList {
-		for i := range list.APIResources {
-			res := &list.APIResources[i]
-			if list.GroupVersion == groupVersion && res.Kind == kind {
-				found = true
-				break
+
+	return r.crdExistsWithClient(ctx, discoveryClient, kind, groupVersion, wait.Backoff{
+		Duration: time.Second,
```
Comment (arkodg) [inline internal/provider/kubernetes/controller.go:2766]: does this line up with other retry mechanisms we use, for e.g. in the status updater ?

File: internal/provider/kubernetes/controller.go [hunk 4]
```diff
@@ -2703,28 +2757,68 @@ func (r *gatewayAPIReconciler) processEnvoyProxy(ep *egv1a1.EnvoyProxy, resource
...
+		case !isTransientError(err):
+			return false, fmt.Errorf("discover resources for %s: %w", groupVersion, err)
 		}
-	}
 
-	return found
+		// retry transient errors with backoff
+		lastTransientErr = err
+
+		d := backoff.Duration
```
Comment (arkodg) [inline internal/provider/kubernetes/controller.go]: is there any existing API we can use for this ?

Comment (zirain) [reply internal/provider/kubernetes/controller.go]: wait.PollUntilContextTimeou?

File: internal/provider/kubernetes/controller.go [hunk 5]
```diff
@@ -2703,28 +2758,58 @@ func (r *gatewayAPIReconciler) processEnvoyProxy(ep *egv1a1.EnvoyProxy, resource
...
 }
 
-// crdExists checks for the existence of the CRD in k8s APIServer before watching it
-func (r *gatewayAPIReconciler) crdExists(mgr manager.Manager, kind, groupVersion string) bool {
+// crdExists checks for the existence of the CRD in k8s APIServer before watching it.
+func (r *gatewayAPIReconciler) crdExists(ctx context.Context, mgr manager.Manager, kind, groupVersion string) (bool, error) {
 	discoveryClient, err := discovery.NewDiscoveryClientForConfig(mgr.GetConfig())
 	if err != nil {
-		r.log.Error(err, "failed to create discovery client")
+		return false, fmt.Errorf("failed to create discovery client: %w", err)
```
Comment (arkodg) [inline internal/provider/kubernetes/controller.go]: can we create discoveryClient once ?

Comment (arkodg) [reply internal/provider/kubernetes/controller.go]: non blocking comment

File: internal/envoygateway/config/loader/configloader.go [hunk 6]
```diff
@@ -36,12 +37,18 @@ func New(cfgPath string, cfg *config.Server, f HookFunc) *Loader {
...
 	}
 }
 
 func (r *Loader) Start(ctx context.Context, logOut io.Writer) error {
 	r.runHook(ctx)
+	select {
+	case err := <-r.hookErr:
+		return err
+	default:
+	}
```
Comment (arkodg) [inline internal/envoygateway/config/loader/configloader.go]: there's another code path for the configmap restart case, we should try and make sure the flows are same

File: internal/envoygateway/config/loader/configloader.go [hunk 7]
```diff
@@ -36,12 +37,18 @@ func New(cfgPath string, cfg *config.Server, f HookFunc) *Loader {
...
 		logger:  cfg.Logger.WithName("config-loader"),
 		hook:    f,
+		hookErr: make(chan error, 1),
 		w:       filewatcher.NewWatcher(),
 	}
 }
 
 func (r *Loader) Start(ctx context.Context, logOut io.Writer) error {
 	r.runHook(ctx)
+	select {
```
Comment (arkodg) [inline internal/envoygateway/config/loader/configloader.go]: is this and the one in `server` needed ?

Comment (zhaohuabing) [reply internal/envoygateway/config/loader/configloader.go]: This change is required to propagate runner startup errors so the process exits and Envoy Gateway can restart cleanly. Previously, startup failures were only logged, and Envoy Gateway continued running even with failed runners.

File: internal/envoygateway/config/loader/configloader.go (hunk 6 above)
Comment (zhaohuabing) [reply internal/envoygateway/config/loader/configloader.go]: The errors are sent to the hookErr channel, and are handled in the server.

File: internal/envoygateway/config/loader/configloader.go (hunk 7 above)
Comment (zhaohuabing) [reply internal/envoygateway/config/loader/configloader.go]: Removed this one, the hook error can be handled in `server` together.

**Review by arkodg — DISMISSED** [review]
LGTM thanks

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
FYI, during test https://github.com/envoyproxy/gateway/pull/7964, it would take more 60s before runner return error with discovery failure.

**Comment by zhaohuabing** [comment]
> FYI, during test #7964, it would take more 60s before runner return error with discovery failure.

Hi @zirain Is this because of the retries in this PR?

**Comment by zirain** [comment]
> > FYI, during test #7964, it would take more 60s before runner return error with discovery failure.
> 
> Hi @zirain Is this because of the retries in this PR?

I'm not 100% sure, maybe we need a way to disable the retry in test code?
