### PR TITLE
bugfix: remove stale listener condition

### LINKED ISSUE #773: Stale listener condition present in Gateway for a non-existing Listener
*Description*:
Following the reproduction steps, it is seen that the Gateway is left with a stale listener condition, for a listener
that no longer exists.

*Repro steps*:
1. apply `examples/kubernetes/quickstart.yaml` - ensure that Gateway has proper Status conditions, with 1 listener condition
showing `attachedRoutes: 1`.
2. Add another listener in the gateway, for the listener spec to look something like this
```yaml
listeners:
- allowedRoutes:
     namespaces:
       from: Same
     name: http
     port: 8080
     protocol: HTTP
- allowedRoutes:
     namespaces:
       from: Same
     name: http2
     port: 8081
     protocol: HTTP 
```
This should create 2 listener conditions, both specifying `attachedRoutes: 1`.
3. Remove the single HTTPRoute that was created by the `quickstart.yaml`. Both existing listener conditions are updated correctly, specifying `attachedRoutes: 0`.
4. Re-apply the `quickstart.yaml` which will "recreate" the HTTPRoute, and "update" the Gateway to have only one listener.
5. The bug is that - in the Gateway status still shows the stale listener Condition corresponding to listener `http2` with `attachedRoutes: 0`
The spec and status thus looks like this
```yaml
 spec:
    gatewayClassName: eg
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 8080
      protocol: HTTP
  status:
    ....
    conditions:
    ....
    listeners:
    - attachedRoutes: 1
      conditions:
      - lastTransitionTime: "2022-12-03T06:58:58Z"
        message: Listener is ready
        observedGeneration: 3
        reason: Ready
        status: "True"
        type: Ready
      name: http
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
    - attachedRoutes: 0
      conditions:
      - lastTransitionTime: "2022-12-03T06:58:48Z"
        message: Listener is ready
        observedGeneration: 2
        reason: Ready
        status: "True"
        type: Ready
      name: http2
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
```

### PR DESCRIPTION
**Pull request by haq204**
Previously the listener status in the Gateway resource could be left stale if one of the listeners is removed.

We add new method to GatewayContext to reset the listener status and listener contexts and is called before re-computing

Testing:
- Add unit test for new method
- Add a couple of new testcases to the Translation unit tests to check for stale listener conditions and to ensure the status didn't change if the condition did not change.

Fixes #773

### CODE REVIEW

File: internal/gatewayapi/translator.go [hunk 1]
```diff
@@ -136,14 +138,7 @@ func (t *Translator) GetRelevantGateways(gateways []*v1beta1.Gateway) []*Gateway
...
 			}
-
-			for _, listener := range gateway.Spec.Listeners {
-				l := gc.GetListenerContext(listener.Name)
-				// Reset conditions and attached route count
-				// since it will be recomputed during translation.
-				l.ResetConditions()
-				l.ResetAttachedRoutes()
-			}
+			gc.ResetListeners()
```
Comment (arkodg) [inline internal/gatewayapi/translator.go:141]: * can we delete the `ResetConditions` and `ResetAttachedRoutes` since they are no longer used
* the code within `GetListenerContext` and `ResetListeners` is very similar, can we break up `GetListenerContext` to only perform a Get and use Reset to reset the context ?

Comment (haq204) [reply internal/gatewayapi/translator.go:141]: yea forgot to bring that up but also wanted to ask if we could get rid `ResetConditions` and `ResetAttachedRoutes`

Comment (arkodg) [reply internal/gatewayapi/translator.go:141]: yah please delete, also `GetListenerContext` can be deleted too I think
cc @skriss

Comment (haq204) [reply internal/gatewayapi/translator.go:141]: Now that I think about it, `GetListenerContext` is also not used anymore. Wondering if we should remove that method too?

Comment (arkodg) [reply internal/gatewayapi/translator.go:141]: sure go for it

Comment (haq204) [reply internal/gatewayapi/translator.go:141]: @arkodg removed unused methods

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by AliceProxy — APPROVED** [review]
lgtm, thanks
