### PR TITLE
fix: Allow Policy to attach to multiple http listeners 

### LINKED ISSUE #2963: bug: Allow Policy to attach to multiple http listeners
@arkodg You are right - we do have a regression here. The following _should_ be possible but is not possible right now:

Setting a single `ClientTrafficPolicy` or a `SecurityPolicy` that targets a single `Gateway`, when that `Gateway` has more than one listener. The policy in this case is intended to apply the same settings to all of the listeners, and is valid, but it is currently being rejected.

If, instead of targeting the entire `Gateway`, the `SecurityPolicy` were to target a specific `HTTPRoute` then the correct behavior would have been to reject the `SecurityPolicy` since it's not possible to have different configuration for two routes  connected to the same listener. 

I think that this should be tracked as a separate issue though - WDYT?

_Originally posted by @liorokman in https://github.com/envoyproxy/gateway/issues/2742#issuecomment-2002369812_

### PR DESCRIPTION
**Pull request by liorokman**
**Which issue(s) this PR fixes**:
Fixes #2963

### CODE REVIEW

File: internal/gatewayapi/clienttrafficpolicy.go [hunk 1]
```diff
@@ -312,7 +312,7 @@ func resolveCTPolicyTargetRef(policy *egv1a1.ClientTrafficPolicy, gateways map[t
 	return gateway.GatewayContext, nil
 }
 
-func validatePortOverlapForClientTrafficPolicy(l *ListenerContext, xds *ir.Xds) error {
+func validatePortOverlapForClientTrafficPolicy(l *ListenerContext, xds *ir.Xds, attachedToGateway bool) error {
```
Comment (arkodg) [inline internal/gatewayapi/clienttrafficpolicy.go:315]: adding comments for the new logic would really help

File: internal/gatewayapi/clienttrafficpolicy.go [hunk 2]
```diff
@@ -329,7 +329,20 @@ func validatePortOverlapForClientTrafficPolicy(l *ListenerContext, xds *ir.Xds)
 	// IR must exist since we're past validation
 	if httpIR != nil {
 		if sameListeners := listenersWithSameHTTPPort(xds, httpIR); len(sameListeners) != 0 {
-			return fmt.Errorf("affects additional listeners: %s", strings.Join(sameListeners, ", "))
+			if attachedToGateway {
```
Comment (arkodg) [inline internal/gatewayapi/clienttrafficpolicy.go:332]: this is now O(n^3)
can we instead hold a map containing listener name as the key and policy as the value ?
* if key is missing, add key, and return
* if key is present, policy is same, return
* if key is present, and a different policy, reject

this takes an approach of first policy wins, which imo is better than no policy winning

**Review by zhaohuabing — COMMENTED** [review]
We probably won't need this https://github.com/envoyproxy/gateway/pull/2970

**Comment by arkodg** [comment]
@zhaohuabing we still need it for CTP which adds fields like `MergeSlashes` on the `hcm` directly, so we have a conflict for http (non https/tls) case

File: internal/gatewayapi/clienttrafficpolicy.go (hunk 2 above)
Comment (liorokman) [reply internal/gatewayapi/clienttrafficpolicy.go:332]: > this takes an approach of first policy wins, which imo is better than no policy winning

"First policy wins" doesn't make sense. It's not a conflict between two policies where one can win and the other can lose, it's that translating a single policy (no other policies existing in the system) would result in it affecting multiple listeners including listeners that should not be affected by the policy.

Comment (liorokman) [reply internal/gatewayapi/clienttrafficpolicy.go:332]: > this is now O(n^3)

Looking closely at the ` validatePortOverlapForClientTrafficPolicy` method, it seems to me that it's `O(n)` where `n` is the number of HTTP listeners attached to a Gateway XDS representation.


```golang

func validatePortOverlapForClientTrafficPolicy(l *ListenerContext, xds *ir.Xds, attachedToGateway bool) error {
	irListenerName := irHTTPListenerName(l)
	var httpIR *ir.HTTPListener

         // O(n) loop

	for _, http := range xds.HTTP { 
		if http.Name == irListenerName {
			httpIR = http
			break
		}
	}

	// IR must exist since we're past validation
	if httpIR != nil {
                //           listenersWithSameHTTPPort is O(n) and it is called once. 
                //  This is an 'if' statment, not a 'for' statement.
		if sameListeners := listenersWithSameHTTPPort(xds, httpIR); len(sameListeners) != 0 {


			if attachedToGateway {
				gatewayName := irListenerName[0:strings.LastIndex(irListenerName, "/")]
				conflictingListeners := []string{}

                                // sameListeners is an array with an upper bound of O(n)

				for _, currName := range sameListeners {
					if strings.Index(currName, gatewayName) != 0 {
						conflictingListeners = append(conflictingListeners, currName)
					}
				}
				if len(conflictingListeners) != 0 {
					return fmt.Errorf("affects additional listeners: %s", strings.Join(conflictingListeners, ", "))
				}
			} else {
				return fmt.Errorf("affects additional listeners: %s", strings.Join(sameListeners, ", "))
			}
		}
	}
	return nil
}

```

Comment (arkodg) [reply internal/gatewayapi/clienttrafficpolicy.go:332]: @liorokman adding some reasons why we should consider first policy wins
* we already oldest config wins in most places https://github.com/envoyproxy/gateway/blob/6fa99be5a9a3e5d16294492162181ff64db67003/internal/gatewayapi/clienttrafficpolicy.go#L43
* this allows existing traffic to not get interrupted/dropped, ensures that is policy1 targets listener1 at t1 and policy2 targets listener2 at t2, listener1 is not affected

**Comment by zhaohuabing** [comment]
We don't need this for SecurityPolicy anymore.

File: internal/gatewayapi/securitypolicy.go [hunk 3]
```diff
@@ -194,7 +194,7 @@ func (t *Translator) ProcessSecurityPolicies(securityPolicies []*egv1a1.Security
 			irKey := t.getIRKey(targetedGateway.Gateway)
```
Comment (zhaohuabing) [inline internal/gatewayapi/securitypolicy.go:194]: We don't need this for SecurityPolicy anymore. It's handled in https://github.com/envoyproxy/gateway/pull/2970

File: internal/gatewayapi/clienttrafficpolicy.go (hunk 2 above)
Comment (liorokman) [reply internal/gatewayapi/clienttrafficpolicy.go:332]: @arkodg The bug occurs when there is exactly one policy. The scenario where there are two policies is out of scope for this issue. There's no way to implement "first policy wins", because "first policy wins" means "reject the policy provided".

Here's a recreation of the bug that this PR is trying to solve.:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    metadata:
      name: gateway
    spec:
      gatewayClassName: envoy-gateway-class
      listeners:
        - name: http
          port: 80
          protocol: HTTP
          hostname: foo.example.com
          allowedRoutes:
            namespaces:
              from: Same
        - name: http2
          port: 80
          protocol: HTTP
          hostname: bar.example.com
          allowedRoutes:
            namespaces:
              from: Same
---
apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: ClientTrafficPolicy
  metadata:
    name: target-gateway
  spec:
    targetRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: default
      sectionName: http
    path:
        escapedSlashesAction: RejectRequest
    timeout:
      http:
        requestReceivedTimeout: "5s"
      
```

The above single `ClientTrafficPolicy` tries to target only one listener - the one called `http` - and because both `http` and `http2` are non-TLS and on the same port, the `requestReceivedTimeout`  configured for `http2` will also be `5s`. Even worse, while `http` should have the `RejectRequest` action for escaped slashes, `http2` _should_ use the default value (`UnescapeAndForward`) but will instead be configured to `RejectRequest`.


Without this PR the translated IR will be correct - the various settings from the `ClientTrafficPolicy` will be set in the correct location - only on `http` and not on `http2`. The bug occurs because the correct IR is not translatable to valid XDS.

File: internal/gatewayapi/securitypolicy.go (hunk 3 above)
Comment (liorokman) [reply internal/gatewayapi/securitypolicy.go]: I removed the code that validates `SecurityPolicy` for this issue.

File: internal/gatewayapi/clienttrafficpolicy.go [hunk 4]
```diff
@@ -328,8 +328,29 @@ func validatePortOverlapForClientTrafficPolicy(l *ListenerContext, xds *ir.Xds)
...
+						conflictingListeners = append(conflictingListeners, currName)
+					}
+				}
+				if len(conflictingListeners) != 0 {
+					return fmt.Errorf("affects additional listeners: %s", strings.Join(conflictingListeners, ", "))
+				}
+			} else {
+				// If this policy is attached to a specific listener, any other listeners in the list
+				// would be affected by this policy but should not be, so this policy can't be accepted.
+				return fmt.Errorf("affects additional listeners: %s", strings.Join(sameListeners, ", "))
```
Comment (arkodg) [inline internal/gatewayapi/clienttrafficpolicy.go:352]:
```suggestion
				return fmt.Errorf("policy attached to multiple http (non https) listeners %s on the same port is not allowed", strings.Join(sameListeners, ", "))
```

File: internal/gatewayapi/clienttrafficpolicy.go [hunk 5]
```diff
@@ -328,8 +328,29 @@ func validatePortOverlapForClientTrafficPolicy(l *ListenerContext, xds *ir.Xds)
...
+				// originated is part of the listener's name by construction.
+				gatewayName := irListenerName[0:strings.LastIndex(irListenerName, "/")]
+				conflictingListeners := []string{}
+				for _, currName := range sameListeners {
+					if strings.Index(currName, gatewayName) != 0 {
+						conflictingListeners = append(conflictingListeners, currName)
+					}
+				}
+				if len(conflictingListeners) != 0 {
+					return fmt.Errorf("affects additional listeners: %s", strings.Join(conflictingListeners, ", "))
```
Comment (arkodg) [inline internal/gatewayapi/clienttrafficpolicy.go:347]: same as below

**Comment by arkodg** [comment]
thanks for adding comments @liorokman, added a minor comment around the error string to make it clearer why the policy was rejected, else LGTM !

File: internal/gatewayapi/clienttrafficpolicy.go (hunk 4 above)
Comment (liorokman) [reply internal/gatewayapi/clienttrafficpolicy.go:352]: The suggested error message is a bit misleading, since the policy document as applied by the user is explicitly not attached to any other listener.

How about `policy would affect additional http (non https) listeners to which it was not attached: %s` ?

Comment (arkodg) [reply internal/gatewayapi/clienttrafficpolicy.go:352]: ah instead of `attached`, we could use `applied` :) 

`ClientTrafficPolicy is being applied to multiple http (non https) listeners %s on the same port, which is not allowed`

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
all e2e tests consistently seem to be consistently failing @liorokman

**Comment by liorokman** [comment]
> all e2e tests consistently seem to be consistently failing @liorokman

@arkodg all e2e tests have passed.
