### PR TITLE
fix: add mutex lock to snapshot cache OnStreamResponse/OnStreamDeltaResponse

### LINKED ISSUE #8276: fix: data race in snapshot cache OnStreamResponse/OnStreamDeltaResponse
`OnStreamResponse` and `OnStreamDeltaResponse` in `internal/xds/cache/snapshotcache.go` read from `s.streamIDNodeInfo` without holding the mutex lock.

The comment says "No mutex lock required here because no writing to the cache" — but this is incorrect. Other callbacks (`OnStreamOpen`, `OnStreamClosed`, `OnStreamRequest`, `OnDeltaStreamOpen`, `OnDeltaStreamClosed`) all write to this same map while holding `s.mu`. In Go, concurrent map read and write is a data race that causes `fatal error: concurrent map read and map write`.

**Affected code:**
- `OnStreamResponse` (line ~277): reads `s.streamIDNodeInfo[streamID]` without lock
- `OnStreamDeltaResponse` (line ~396): same pattern

**Impact:** Under concurrent xDS traffic (multiple Envoy proxies connecting/disconnecting), this can crash the control plane with a runtime panic.

**Fix:** Acquire `s.mu.RLock()` before reading the map in both functions.

### PR DESCRIPTION
**Pull request by jaffarkeikei**
`OnStreamResponse` and `OnStreamDeltaResponse` read from `s.streamIDNodeInfo` without the mutex, causing a data race with concurrent writes from `OnStreamOpen`/`OnStreamClosed`/etc. This can crash the control plane under concurrent xDS traffic.

Adds `s.mu.Lock()`/`s.mu.Unlock()` to both functions.

Fixes #8276

### CODE REVIEW

File: internal/xds/cache/snapshotcache.go [hunk 1]
```diff
@@ -273,8 +273,9 @@ func (s *snapshotCache) OnStreamRequest(streamID int64, req *discoveryv3.Discove
 }
 
 func (s *snapshotCache) OnStreamResponse(_ context.Context, streamID int64, _ *discoveryv3.DiscoveryRequest, _ *discoveryv3.DiscoveryResponse) {
-	// No mutex lock required here because no writing to the cache.
+	s.mu.Lock()
```
Comment (jukie) [inline internal/xds/cache/snapshotcache.go:276]: Could you elaborate more on why this is necessary?

Comment (jaffarkeikei) [reply internal/xds/cache/snapshotcache.go:276]: OnStreamOpen, OnStreamClosed, OnStreamRequest, OnDeltaStreamOpen, and OnDeltaStreamClosed all write to s.streamIDNodeInfo while holding s.mu. But OnStreamResponse and OnStreamDeltaResponse were reading from the same map without any lock.

Comment (jukie) [reply internal/xds/cache/snapshotcache.go:276]: Thanks!
