### PR TITLE
fix: ratelimit not working with both headers and cidr matches 

### LINKED ISSUE #4351: Ratelimiting doesn't work with both clientSelectors (i.e. headers and sourceCIDR) enabled
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
Ratelimiting doesn't work with both clientSelectors (i.e. headers and sourceCIDR) enabled. I would expect it to work if the headers match and the request is from the IP in the sourceCIDR range.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
Followed all steps from quickstart. This is my ratelimit config:
```
rateLimit:
    global:
      rules:
      - clientSelectors:
        - headers:
          - name: x-user-id
            value: one
          sourceCIDR:
            type: Exact
            value: 0.0.0.0/0
        limit:
          requests: 3
          unit: Hour
    type: Global
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

These are the `envoy-ratelimit` logs, note this line `descriptor does not match any limit, no limits applied`.
```
time="2024-09-27T00:56:04Z" level=debug msg="CertProvider: waiting for runtime update"
time="2024-09-27T00:56:04Z" level=info msg="Starting xDS client connection for rate limit configurations"
time="2024-09-27T00:56:04Z" level=info msg="Dialing xDS Management Server: 'envoy-gateway:18001'"
time="2024-09-27T00:56:04Z" level=warning msg="connecting to redis on redis.redis-system.svc.cluster.local:6379 with pool size 10"
time="2024-09-27T00:56:04Z" level=debug msg="Implicit pipelining enabled: false"
time="2024-09-27T00:56:04Z" level=warning msg="Listening for debug on '0.0.0.0:6070'"
time="2024-09-27T00:56:04Z" level=warning msg="Listening for gRPC on '0.0.0.0:8081'"
time="2024-09-27T00:56:04Z" level=debug msg="Waiting for config update event"
time="2024-09-27T00:56:04Z" level=warning msg="Listening for HTTP on '0.0.0.0:8080'"
time="2024-09-27T00:56:04Z" level=info msg="Connection to xDS Management Server is successful"
time="2024-09-27T00:56:04Z" level=debug msg="loading domain: default/eg/http"
time="2024-09-27T00:56:04Z" level=debug msg="loading descriptor: key=default/eg/http.httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example"
time="2024-09-27T00:56:04Z" level=debug msg="Creating stats for key: 'default/eg/http.httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example.masked_remote_address_0.0.0.0/0'"
time="2024-09-27T00:56:04Z" level=debug msg="loading descriptor: key=default/eg/http.httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example.masked_remote_address_0.0.0.0/0 ratelimit={requests_per_unit=3, unit=HOUR, unlimited=false, shadow_mode=false}"
time="2024-09-27T00:56:04Z" level=debug msg="Setting config retrieved from config provider"
time="2024-09-27T00:56:04Z" level=info msg="Successfully loaded new configuration"
time="2024-09-27T00:56:04Z" level=debug msg="Waiting for config update event"
time="2024-09-27T00:56:39Z" level=debug msg="got descriptor: (httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example=httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example),(rule-0-match-0=rule-0-match-0),(masked_remote_address=0.0.0.0/0)"
time="2024-09-27T00:56:39Z" level=debug msg="starting get limit lookup"
time="2024-09-27T00:56:39Z" level=debug msg="looking up key: httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example"
time="2024-09-27T00:56:39Z" level=debug msg="iterating to next level"
time="2024-09-27T00:56:39Z" level=debug msg="looking up key: rule-0-match-0_rule-0-match-0"
time="2024-09-27T00:56:39Z" level=debug msg="looking up key: rule-0-match-0"
time="2024-09-27T00:56:39Z" level=debug msg="descriptor does not match any limit, no limits applied"
time="2024-09-27T00:56:39Z" level=debug msg="starting cache lookup"
time="2024-09-27T00:56:39Z" level=debug msg="returning normal response"
```

I do see that the config is reflected in xds-ir (in gateway logs):
```
2024-09-27T00:54:27.139Z        INFO    gateway-api     runner/runner.go:186    {
        "accessLog": {
                "text": [
                        {
                                "path": "/dev/stdout"
                        }
                ]
        },
        "http": [
                {
                        "name": "default/eg/http",
                        "address": "0.0.0.0",
                        "port": 10080,
                        "metadata": {
                                "kind": "Gateway",
                                "name": "eg",
                                "namespace": "default",
                                "sectionName": "http"
                        },
                        "hostnames": [
                                "*"
                        ],
                        "routes": [
                                {
                                        "name": "httproute/default/backend/rule/0/match/0/www_example_com",
                                        "hostname": "www.example.com",
                                        "isHTTP2": false,
                                        "pathMatch": {
                                                "name": "",
                                                "prefix": "/",
                                                "distinct": false
                                        },
                                        "destination": {
                                                "name": "httproute/default/backend/rule/0",
                                                "settings": [
                                                        {
                                                                "weight": 1,
                                                                "protocol": "HTTP",
                                                                "endpoints": [
                                                                        {
                                                                                "host": "10.244.0.10",
                                                                                "port": 3000
                                                                        },
                                                                        {
                                                                                "host": "10.244.0.10",
                                                                                "port": 3000
                                                                        }
                                                                ],
                                                                "addressType": "IP"
                                                        }
                                                ]
                                        },
                                        "metadata": {
                                                "kind": "HTTPRoute",
                                                "name": "backend",
                                                "namespace": "default"
                                        }
                                },
                                {
                                        "name": "httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example",
                                        "hostname": "ratelimit.example",
                                        "isHTTP2": false,
                                        "pathMatch": {
                                                "name": "",
                                                "prefix": "/",
                                                "distinct": false
                                        },
                                        "destination": {
                                                "name": "httproute/default/http-ratelimit/rule/0",
                                                "settings": [
                                                        {
                                                                "weight": 1,
                                                                "protocol": "HTTP",
                                                                "endpoints": [
                                                                        {
                                                                                "host": "10.244.0.10",
                                                                                "port": 3000
                                                                        },
                                                                        {
                                                                                "host": "10.244.0.10",
                                                                                "port": 3000
                                                                        }
                                                                ],
                                                                "addressType": "IP"
                                                        }
                                                ]
                                        },
                                        "traffic": {
                                                "rateLimit": {
                                                        "global": {
                                                                "rules": [
                                                                        {
                                                                                "headerMatches": [
                                                                                        {
                                                                                                "name": "x-user-id",
                                                                                                "exact": "one",
                                                                                                "distinct": false
                                                                                        }
                                                                                ],
                                                                                "cidrMatch": {
                                                                                        "cidr": "0.0.0.0/0",
                                                                                        "ip": "0.0.0.0",
                                                                                        "maskLen": 0,
                                                                                        "isIPv6": false,
                                                                                        "distinct": false
                                                                                },
                                                                                "limit": {
                                                                                        "requests": 3,
                                                                                        "unit": "Hour"
                                                                                }
                                                                        }
                                                                ]
                                                        }
                                                }
                                        },
                                        "metadata": {
                                                "kind": "HTTPRoute",
                                                "name": "http-ratelimit",
                                                "namespace": "default"
                                        }
                                }
                        ],
                        "isHTTP2": false,
                        "path": {
                                "mergeSlashes": true,
                                "escapedSlashesAction": "UnescapeAndRedirect"
                        }
                }
        ]
}       {"runner": "gateway-api", "xds-ir": "default/eg"}
```

Thanks !

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4351

### CODE REVIEW

File: internal/xds/translator/ratelimit.go [hunk 1]
```diff
@@ -157,19 +157,19 @@ func buildRouteRateLimits(descriptorPrefix string, global *ir.GlobalRateLimit) [
 		// Matches are ANDed
 		rlActions := []*routev3.RateLimit_Action{routeDescriptor}
 		for mIdx, match := range rule.HeaderMatches {
+			var action *routev3.RateLimit_Action
```
Comment (arkodg) [inline internal/xds/translator/ratelimit.go:160]: how does this help ?

File: internal/xds/translator/ratelimit.go [hunk 2]
```diff
@@ -401,25 +384,36 @@ func buildRateLimitServiceDescriptors(global *ir.GlobalRateLimit) []*rlsconfv3.R
...
+		if !rule.IsMatchSet() {
+			pbDesc := new(rlsconfv3.RateLimitDescriptor)
+			// GenericKey case
+			pbDesc.Key = getRouteRuleDescriptor(rIdx, -1)
+			pbDesc.Value = getRouteRuleDescriptor(rIdx, -1)
 			head = pbDesc
 			cur = head
 		}
 
+		// Add the ratelimit values to the last descriptor
```
Comment (arkodg) [inline internal/xds/translator/ratelimit.go:415]: this used to be under `if mIdx == len(rule.HeaderMatches)-1` , was that a bug ?

File: internal/xds/translator/ratelimit.go [hunk 3]
```diff
@@ -401,25 +384,36 @@ func buildRateLimitServiceDescriptors(global *ir.GlobalRateLimit) []*rlsconfv3.R
...
-			} else {
-				pbDesc.RateLimit = &rateLimit
+				pbDesc := new(rlsconfv3.RateLimitDescriptor)
+				pbDesc.Key = "remote_address"
+				cur.Descriptors = []*rlsconfv3.RateLimitDescriptor{pbDesc}
+				cur = pbDesc
 			}
+		}
+
+		// Case when header/cidr match is not set and the rate limit is applied
```
Comment (arkodg) [inline internal/xds/translator/ratelimit.go:404]: curious why this was moved below

Comment (shawnh2) [reply internal/xds/translator/ratelimit.go:404]: all descriptors built in this func, their order should be align with all the ratelimit actions in `buildRouteRateLimits`, as 1) headers match, 2) CIDR match, 3) no match

File: internal/xds/translator/ratelimit.go (hunk 2 above)
Comment (shawnh2) [reply internal/xds/translator/ratelimit.go:415]: yes, if we set both header and cidr matches, the `rateLimitPolicy` should not be added just because `mIdx == len(rule.HeaderMatches)-1`, it will be rewrite/coverd by the follow cidr match descriptors, causing header match to be invalid.

so the condition should be `mIdx == len(rule.HeaderMatches)-1 && no cidr match exist`

Comment (shawnh2) [reply internal/xds/translator/ratelimit.go:415]: the fix here is to add `rateLimitPolicy` after all the descriptors were built, works for: 1) only header match, 2) only cidr match, 3) both header & cidr match, 4) no match

**Review by arkodg — APPROVED** [review]
LGTM thanks !

File: internal/xds/translator/testdata/out/xds-ir/ratelimit-headers-and-cidr.routes.yaml [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+              descriptorKey: first-route
+              descriptorValue: first-route
+          - headerValueMatch:
+              descriptorKey: rule-0-match-0
+              descriptorValue: rule-0-match-0
+              expectMatch: true
+              headers:
+              - name: x-user-id
+                stringMatch:
+                  exact: one
```
Comment (zhaohuabing) [inline internal/xds/translator/testdata/out/xds-ir/ratelimit-headers-and-cidr.routes.yaml:25]: Should we also match `x-user-id`=`two`?
```
routes:
- name: "first-route"
  traffic:
    rateLimit:
      global:
        rules:
        - headerMatches:
          - name: "x-user-id"
            exact: "one"
          - name: "x-user-id"
            exact: "two"
          cidrMatch:
            cidr: 0.0.0.0/0
            ip: 0.0.0.0
            maskLen: 0
            isIPv6: false
            distinct: false
          limit:
            requests: 5
            unit: second
 ```

File: internal/xds/translator/testdata/in/ratelimit-config/header-and-cidr-matches.yaml [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+- name: "first-route"
+  traffic:
+    rateLimit:
+      global:
+        rules:
+        - headerMatches:
+          - name: "x-user-id"
+            exact: "one"
+          - name: "x-user-id"
+            exact: "two"
```
Comment (zhaohuabing) [inline internal/xds/translator/testdata/in/ratelimit-config/header-and-cidr-matches.yaml:19]: Nit: This is not a good example as "x-user-id=one && x-user-id=two" will always be false.

This raises a broader question: should we allow the same header appear multiple times in the `Headers` match conditions? @arkodg

File: internal/xds/translator/ratelimit.go [hunk 6]
```diff
@@ -329,20 +329,12 @@ func BuildRateLimitServiceConfig(irListener *ir.HTTPListener) *rlsconfv3.RateLim
 func buildRateLimitServiceDescriptors(global *ir.GlobalRateLimit) []*rlsconfv3.RateLimitDescriptor {
```
Comment (zhaohuabing) [inline internal/xds/translator/ratelimit.go:329]: Nit: This piece of code is hard to understand. Add an example to the comment will help later readers to understand it.

input:
```
name: "first-listener"
...
routes:
- name: "first-route"
  traffic:
    rateLimit:
      global:
        rules:
        - headerMatches:
          - name: "x-org
            exact: "foo"
          - name: "x-use
            exact: "bar"
          cidrMatch:
            cidr: 192.16
            maskLen: 16
          limit:
            requests: 5
            unit: second
```

output:
```
name: first-listener
domain: first-listener
descriptors:
  - key: first-route
    value: first-route
    rate_limit: null
    descriptors:
      - key: rule-0-match-0
        value: rule-0-match-0
        rate_limit: null
        descriptors:
          - key: rule-0-match-1
            value: rule-0-match-1
            rate_limit: null
            descriptors:
              - key: masked_remote_address
                value: 192.168.0.0/16
                rate_limit:
                  requests_per_unit: 5
                  unit: SECOND
                  unlimited: false
                  name: ""
                  replaces: []
                descriptors: []
                shadow_mode: false
                detailed_metric: false
            shadow_mode: false
            detailed_metric: false
        shadow_mode: false
        detailed_metric: false
    shadow_mode: false
    detailed_metric: false
```

**Review by zhaohuabing — DISMISSED** [review]
LGTM. Thanks for the fix! Could you also modify the `headerMatch` in the test and add an example in the comment to help future readers to better understand the code?

File: internal/xds/translator/testdata/in/ratelimit-config/header-and-cidr-matches.yaml (hunk 5 above)
Comment (arkodg) [reply internal/xds/translator/testdata/in/ratelimit-config/header-and-cidr-matches.yaml:19]: the same header multiple times is valid, for e.g. https://github.com/envoyproxy/gateway/pull/4452

Comment (zhaohuabing) [reply internal/xds/translator/testdata/in/ratelimit-config/header-and-cidr-matches.yaml:19]: This is ver difficult to understand:
```
        - clientSelectors:
            - headers:
                - name: x-user-name
                  type: Distinct
                - name: x-user-name
                  type: Exact
                  value: admin
                  invert: true
          limit:
            requests: 3
            unit: Hour                  
 ```
 
I prefer:
 
 ```
         - clientSelectors:
            - headers:
                - name: x-user-name
                  type: Exact
                  value: admin
                  invert: true
           limit:
            requests: 3
            unit: Hour                 
 ```

Comment (shawnh2) [reply internal/xds/translator/testdata/in/ratelimit-config/header-and-cidr-matches.yaml:19]: updated the test, add a two different header names case

File: internal/xds/translator/ratelimit.go (hunk 6 above)
Comment (shawnh2) [reply internal/xds/translator/ratelimit.go:329]: I've added some natural language to describe this function, imo adding example code is unnecessary, since it has the same content as the test does.

**Review by zhaohuabing — APPROVED** [review]

**Review by arkodg — APPROVED** [review]
