### PR TITLE
fix: add validation for envoy gateway watch mode field and update doc

### LINKED ISSUE #2430: EG failed on multi-tenancy example
*Description*:

the GatewayClass failed to be accepted on multi-tenancy example.

rolling EG logs, we got:

```console
W0111 10:28:02.676452       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1beta1.ReferenceGrant: referencegrants.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:marketing:envoy-gateway" cannot list resource "referencegrants" in API group "gateway.networking.k8s.io" at the cluster scope
E0111 10:28:02.676510       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1beta1.ReferenceGrant: failed to list *v1beta1.ReferenceGrant: referencegrants.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:marketing:envoy-gateway" cannot list resource "referencegrants" in API group "gateway.networking.k8s.io" at the cluster scope
W0111 10:28:04.988572       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha2.TLSRoute: tlsroutes.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:marketing:envoy-gateway" cannot list resource "tlsroutes" in API group "gateway.networking.k8s.io" at the cluster scope
E0111 10:28:04.988657       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1alpha2.TLSRoute: failed to list *v1alpha2.TLSRoute: tlsroutes.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:marketing:envoy-gateway" cannot list resource "tlsroutes" in API group "gateway.networking.k8s.io" at the cluster scope
...
```

seems that the namespaced watch mode are not effected.

*Repro steps*:

follow the steps from https://gateway.envoyproxy.io/latest/user/deployment-mode/#multi-tenancy

*Environment*:

latest

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2430

### CODE REVIEW

**Review by cnvergence — APPROVED** [review]
lgtm

File: api/v1alpha1/envoygateway_types.go [hunk 1]
```diff
@@ -219,13 +219,13 @@ type KubernetesWatchMode struct {
...
 	// Note that Envoy Gateway will continue to reconcile relevant cluster scoped resources such as
-	// GatewayClass that it is linked to. Precisely one of Namespaces and NamespaceSelectors must be set
+	// GatewayClass that it is linked to. Precisely one of Namespaces and NamespaceSelectors must be set.
 	Namespaces []string `json:"namespaces,omitempty"`
 
 	// NamespaceSelectors holds a list of labels that namespaces have to have in order to be watched.
 	// Note this doesn't set the informer to watch the namespaces with the given labels. Informer still
-	// watches all namespaces. But the events for objects whois namespce have no given labels
-	// will be filtered out. Precisely one of Namespaces and NamespaceSelectors must be set
+	// watches all namespaces. But the events for objects whois namespace have no given labels
```
Comment (arkodg) [inline api/v1alpha1/envoygateway_types.go:227]:
```suggestion
	// watches all namespaces. But the events for objects whose namespace do not match given labels
```

**Review by arkodg — DISMISSED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]
