### PR TITLE
fix(tcp): add SNI-based filter chain matching for TLS passthrough empty routes

### LINKED ISSUE #7866: Gateway generates invalid Envoy config with multiple EmptyCluster Routes
*Description*:

https://github.com/envoyproxy/gateway/blob/fba4f46ddf4b342e31379d1c493cb734ff2ddb9a/internal/xds/translator/translator.go#L834-L836 adds a dummy `EmptyCluster` TCPRoute for TCP listeners (or TLS listeners in Passthrough mode) with no routes. But if there is more than one such listener, multiple of these identical routes result in invalid Envoy configuration:
```
[2025-12-22 17:34:42.584][1][warning][config] [source/extensions/config_subscription/grpc/delta_subscription_state.cc:296] delta config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) xxx: error adding listener '0.0.0.0:10443': filter chain 'EmptyCluster' has the same matching rules defined as 'EmptyCluster'. duplicate matcher is: {}
```

In our specific case, we had certmanager annotations on a Gateway with only Passthrough TLS listeners, so there was nothing that actually needed a certificate. But a certmanager bug https://github.com/cert-manager/cert-manager/issues/6985 (fixed in 1.18) caused it to reject the listener instead of just ignoring it. But this seems like a generic issue that could be triggered separately from certmanager usage.

*Repro steps*:

Create multiple TCP or TLS/Passthrough listeners without any attached Routes.

*Environment*:

Gateway 1.6.1 and 1.5.6

### PR DESCRIPTION
**Pull request by OliverBailey**
## Description

Fixes the bug where multiple TCP/TLS listeners on the same port without any attached Routes would cause Envoy to reject the entire listener configuration with:

```
filter chain 'EmptyCluster' has the same matching rules defined as 'EmptyCluster'. duplicate matcher is: {}
```

The root cause: when multiple IR listeners share the same address:port (mapping to a single xDS listener), the old code called `addXdsTCPFilterChain` once per IR listener, adding identical `EmptyCluster` filter chains to the same xDS listener — which Envoy considers invalid duplicate matchers.

## Changes

**`internal/xds/translator/translator.go`**
- Introduce `emptyFilterChainAdded := make(map[string]bool)` keyed by xDS listener name
- The `EmptyCluster` filter chain is now added at most once per xDS listener, regardless of how many IR listeners share the same port
- The `EmptyCluster` route object is also created once and reused (`sharedEmptyTCPRoute`)

**Test coverage**
- Added `tcp-multiple-tls-passthrough-no-routes` test: 3 IR listeners on the same port with no routes → single `EmptyCluster` cluster, single filter chain on the xDS listener

## After this fix

```yaml
filterChains:
- name: EmptyCluster
  filters: [...]   # exactly one, regardless of how many IR listeners share the port
```

## Closes

Closes #7866

## Checklist

- [x] Code compiles correctly
- [x] All unit tests pass (`go test ./internal/gatewayapi/... ./internal/xds/translator/... ./internal/ir/...`)
- [x] Test coverage added for the exact failure scenario from the issue

### CODE REVIEW

File: internal/xds/translator/translator.go [hunk 1]
```diff
@@ -851,22 +852,65 @@ func (t *Translator) processTCPListenerXdsTranslation(
 		// If there are no routes, add a route without a destination to the listener to create a filter chain
 		// This is needed because Envoy requires a filter chain to be present in the listener, otherwise it will reject the listener and report a warning
 		if len(tcpListener.Routes) == 0 {
-			if findXdsCluster(tCtx, emptyClusterName) == nil {
-				if err := tCtx.AddXdsResource(resourcev3.ClusterType, emptyRouteCluster); err != nil {
-					errs = errors.Join(errs, err)
+			// TLS passthrough is indicated by having hostnames (for SNI matching) without TLS termination config
+			isTLSPassthrough := len(tcpListener.Hostnames) > 0
```
Comment (stekole) [inline internal/xds/translator/translator.go]: I noticed is right now the code uses `len(tcpListener.Hostnames) > 0` as the signal for "this is TLS passthrough." I think this could get confusing over time since hostname and passthrough mode are different concepts. For an example you could have a TLS terminate listeners with a hostname set, or a passthrough listener with no hostname (catch-all), and both cases would get misidentified here.
Could you add an explicit Passthrough bool to TCPListener? That way the intent is obvious in the IR and we're not coupling two unrelated things. Open to other approaches though. curious on your thoughts

Comment (OliverBailey) [reply internal/xds/translator/translator.go]: Nope, upon reflecting on it, I think you're correct.

I think adding an explicit passthrough bool would be better. Let me adjust, and you can re-review. Coming your way shortly :)

File: internal/ir/xds.go [hunk 2]
```diff
@@ -2173,6 +2173,12 @@ func (s StringMatch) Validate() error {
 // +k8s:deepcopy-gen=true
 type TCPListener struct {
 	CoreListenerDetails `json:",inline" yaml:",inline"`
+	// Hostnames are the hostnames associated with the listener (for TLS SNI matching).
```
Comment (arkodg) [inline internal/ir/xds.go]: lets rm this, we already have the notion of SNI in https://github.com/OliverBailey/gateway/blob/2c9349855fa852c6476ff9995c2ec59743ac0a31/internal/ir/xds.go#L2305

File: internal/xds/translator/testdata/out/xds-ir/tcp-multiple-tls-passthrough-no-routes.clusters.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+- name: EmptyCluster-tls-passthrough-1
```
Comment (arkodg) [inline internal/xds/translator/testdata/out/xds-ir/tcp-multiple-tls-passthrough-no-routes.clusters.yaml]: the goal is to achieve 
```
filterChains:
- name: EmptyCluster
  filters: [...]
```

not add 3 duplicates

File: internal/ir/xds.go (hunk 2 above)
Comment (OliverBailey) [reply internal/ir/xds.go]: Removed — `Hostnames []string` is gone from `TCPListener`. SNI remains only on `TLSInspectorConfig.SNIs` on the routes where it belongs.

File: internal/xds/translator/testdata/out/xds-ir/tcp-multiple-tls-passthrough-no-routes.clusters.yaml (hunk 3 above)
Comment (OliverBailey) [reply internal/xds/translator/testdata/out/xds-ir/tcp-multiple-tls-passthrough-no-routes.clusters.yaml]: Fixed — all empty-route listeners (passthrough or otherwise) now share a single `EmptyCluster` with one filter chain, not one per listener.

File: internal/xds/translator/translator.go (hunk 1 above)
Comment (OliverBailey) [reply internal/xds/translator/translator.go]: Done — `Passthrough bool` is now an explicit field on `TCPListener` and is used as the signal throughout. The `Hostnames` field has been removed entirely (per arkodg's comment below), so there's no longer any coupling between hostname presence and passthrough mode detection.

**Comment by arkodg** [comment]
hey @OliverBailey can you sign your commit, and force push to fix DCO ?

File: internal/xds/translator/translator.go [hunk 4]
```diff
@@ -851,28 +852,43 @@ func (t *Translator) processTCPListenerXdsTranslation(
...
-				tcpListener.Timeout,
-				tcpListener.Connection,
-				tcpListener.TLS,
-			); err != nil {
-				errs = errors.Join(errs, err)
+
+			// Only add the filter chain once per Envoy listener; multiple IR listeners may share
+			// the same address/port and map to the same xDS listener.
+			filterChainExists := false
+			for _, fc := range xdsListener.FilterChains {
```
Comment (arkodg) [inline internal/xds/translator/translator.go]: do we need the for loop ?
could we get by with a bool like `isEmptyClusterSet` and for the first pass we could create it, but for the second pass, we'd avoid it ?

File: internal/gatewayapi/listener.go [hunk 5]
```diff
@@ -161,6 +161,10 @@ func (t *Translator) ProcessListeners(gateways []*GatewayContext, xdsIR resource
 					// refers to the Listener TLS.
 					TLS: irTLSConfigsForTCPListener(listener.tlsSecrets...),
 				}
+				// Set Passthrough flag for TLS passthrough mode
+				if listener.Protocol == gwapiv1.TLSProtocolType && listener.TLS != nil && listener.TLS.Mode != nil {
+					irListener.Passthrough = *listener.TLS.Mode == gwapiv1.TLSModePassthrough
```
Comment (stekole) [inline internal/gatewayapi/listener.go]: This sets the passthrough but does anything read it?

File: internal/xds/translator/translator.go (hunk 4 above)
Comment (stekole) [reply internal/xds/translator/translator.go]: I like this approach. Only track the xDS listeners that already have the empty filter chain. It may need to be a map to allow for listeners on different ports. 
```emptyFilterChainAdded := make(map[string]bool)```

Comment (OliverBailey) [reply internal/xds/translator/translator.go]: Replaced the for-loop with `emptyFilterChainAdded := make(map[string]bool)` keyed by xDS listener name, per stekole's suggestion below. No loop needed — we just check/set the map entry once per xDS listener.

File: internal/gatewayapi/listener.go (hunk 5 above)
Comment (OliverBailey) [reply internal/gatewayapi/listener.go]: Nothing read it; you're right. 
After the translator was simplified to use a single `EmptyCluster` for all empty-route listeners regardless of mode, the `Passthrough` field became dead code. 
Removed the field from `TCPListener`, the setter in `listener.go`, and all testdata references. 

TLS passthrough routing is unaffected: SNI matching still works via `TLSInspectorConfig.SNIs` on each `TCPRoute`.

**Comment by OliverBailey** [comment]
> hey @OliverBailey can you sign your commit, and force push to fix DCO ?

Apologies, completely forgot for that specific commit. Done, and re-signed the commits and pushed back up.

**Review by arkodg — APPROVED** [review]
