### PR TITLE
fix: bug in overlap detection of cert SANs

### LINKED ISSUE #7230: Bug in logic detecting overlapping cert SANs
*Description*:

1. This issue is not a duplicate of #6321.
2. The cause of this issue is mistakenly treating all absolute domain names as wildcard domain names for comparison.
3. Use 'strings.HasSuffix' for comparison is reckless, because [the wildcard applies only to one level of the domain name](https://en.wikipedia.org/wiki/Public_key_certificate#Further_examples).

*Repro steps*:

1. Add a listener for `foo.example.com` and `pdf.foo.example.com`.
※ Use `*.example.com` and `pdf.foo.example.com` should also trigger the issue.
3. Use cert-manager to issue certs for them (note that a wildcard certificate should not be used)
4. Look in the logs to see a warning about overlapping SANs

Sample Gateway Listeners
```yaml
listeners:
  - name: foo
    hostname: foo.example.com
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        - name: foo-tls
  - name: foo-pdf
    hostname: pdf.foo.example.com
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        - name: foo-pdf-tls
```

*Environment*:
Envoy Gateway v1.5.3

*Logs*:
```
Message:  The certificate SAN pdf.foo.example.com overlaps with the certificate SAN foo.example.com in listener foo. ALPN will default to HTTP/1.1 to prevent HTTP/2 connection coalescing, unless explicitly configured via ClientTrafficPolicy
Reason: OverlappingCertificates
Type: OverlappingTLSConfig
```

### PR DESCRIPTION
**Pull request by rudrakhp**
**What type of PR is this?**

fix: bug in overlap detection of cert SANs

**What this PR does / why we need it**:
Fix SAN overlap detection

**Which issue(s) this PR fixes**:

Fixes #7230 

Release Notes: Yes

### CODE REVIEW

**Review by kkk777-7 — APPROVED** [review]

File: internal/gatewayapi/listener_test.go [hunk 1]
```diff
@@ -185,15 +185,21 @@ func TestIsOverlappingHostname(t *testing.T) {
...
+			hostname2: ptr.To(gwapiv1.Hostname("foo.dev")),
+			want:      false,
+		},
 	}
 
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			if got := isOverlappingHostname(tt.hostname1, tt.hostname2); got != tt.want {
+			if got := areOverlappingHostnames(tt.hostname1, tt.hostname2); got != tt.want {
 				t.Errorf("isOverlappingHostname(%q, %q) = %v, want %v", ptr.Deref(tt.hostname1, ""), ptr.Deref(tt.hostname2, ""), got, tt.want)
```
Comment (zhaohuabing) [inline internal/gatewayapi/listener_test.go:199]: Nit:
```suggestion
				t.Errorf("areOverlappingHostnames(%q, %q) = %v, want %v", ptr.Deref(tt.hostname1, ""), ptr.Deref(tt.hostname2, ""), got, tt.want)
```

File: internal/gatewayapi/listener_test.go [hunk 2]
```diff
@@ -185,15 +185,21 @@ func TestIsOverlappingHostname(t *testing.T) {
...
 			}
 			// Test should be symmetric
-			if got := isOverlappingHostname(tt.hostname2, tt.hostname1); got != tt.want {
+			if got := areOverlappingHostnames(tt.hostname2, tt.hostname1); got != tt.want {
 				t.Errorf("isOverlappingHostname(%q, %q) = %v, want %v", ptr.Deref(tt.hostname2, ""), ptr.Deref(tt.hostname1, ""), got, tt.want)
```
Comment (zhaohuabing) [inline internal/gatewayapi/listener_test.go:203]: Nit:
```suggestion
				t.Errorf("areOverlappingHostnames(%q, %q) = %v, want %v", ptr.Deref(tt.hostname2, ""), ptr.Deref(tt.hostname1, ""), got, tt.want)
```

**Review by zhaohuabing — APPROVED** [review]
LGTM. Thanks for fixing this!
