### PR TITLE
fix(translator): ext-proc full duplex streamed trailers and validation

### LINKED ISSUE #6270: Envoy complains about request_trailer_mode not being set to SEND with 1.4.1
*Description*:
I installed the latest 1.4.1 of Envoy Gateway and tried to use the new FullDuplex body mode in one of my EnvoyExtensionPolicies. However Envoy complains about "request_trailer_mode not being set to SEND"

*Repro steps*:
I added an extension as follows:

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: my-ext-proc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  extProc:
    - backendRefs:
        - name: my-ext-proc-ingress
          port: 443
      processingMode:
        request:
          body: FullDuplexStreamed
        response: 
          body: FullDuplexStreamed
```

However when I triggered this extension by sending a request, Envoy generates an error as follows:

severity: "ERROR"

```[source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) default/eg/http: If the ext_proc filter has the request_body_mode set to FULL_DUPLEX_STREAMED, then the request_trailer_mode has to be set to SEND```

I notice there's no way to add "trailers" in the extension. How can we use FullDuplexStreamed body mode? How was it verified in the tests?

*Environment*:
gateway version, envoy version: 1.4.1

*Logs*:

### PR DESCRIPTION
**Pull request by guydc**
**What type of PR is this?**

**What this PR does / why we need it**:
fix ext proc validation and trailer management for full duplex streamed mode

**Which issue(s) this PR fixes**:

Fixes #6270

Release Notes: Yes

### CODE REVIEW

File: internal/xds/translator/extproc.go [hunk 1]
```diff
@@ -127,6 +130,9 @@ func extProcConfig(extProc ir.ExtProc) *extprocv3.ExternalProcessor {
 
 	if extProc.ResponseBodyProcessingMode != nil {
 		config.ProcessingMode.ResponseBodyMode = buildExtProcBodyProcessingMode(extProc.ResponseBodyProcessingMode)
+		if config.ProcessingMode.ResponseBodyMode == extprocv3.ProcessingMode_FULL_DUPLEX_STREAMED {
```
Comment (arkodg) [inline internal/xds/translator/extproc.go]: should this be moved into buildExtProcBodyProcessingMode ?

File: api/v1alpha1/ext_proc_types.go [hunk 2]
```diff
@@ -17,7 +17,8 @@ const (
 	StreamedExtProcBodyProcessingMode ExtProcBodyProcessingMode = "Streamed"
 	// BufferedExtProcBodyProcessingMode will buffer the message body in memory and send the entire body at once. If the body exceeds the configured buffer limit, then the downstream system will receive an error.
 	BufferedExtProcBodyProcessingMode ExtProcBodyProcessingMode = "Buffered"
-	// FullDuplexStreamedExtBodyProcessingMode will send the body in pieces, to be read in a stream. Full details here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/processing_mode.proto.html#enum-extensions-filters-http-ext-proc-v3-processingmode-bodysendmode
+	// FullDuplexStreamedExtBodyProcessingMode will send the body in pieces, to be read in a stream. When enabled, trailers are also sent, and failOpen must be false.
```
Comment (arkodg) [inline api/v1alpha1/ext_proc_types.go:20]: not seeing the `failOpen` validation logic

Comment (guydc) [reply api/v1alpha1/ext_proc_types.go:20]: https://github.com/envoyproxy/gateway/pull/6323/files#diff-2d475e566eff6abe27d7ed2892b3dd252980f2cfccc04bb859a14878c8ca71b1R71

Comment (arkodg) [reply api/v1alpha1/ext_proc_types.go:20]: my bad, as in, is this a requirement from envoy proxy side ?

File: internal/xds/translator/extproc.go (hunk 1 above)
Comment (guydc) [reply internal/xds/translator/extproc.go]: created a dedicated function for handling all the processing mode translation.

File: api/v1alpha1/ext_proc_types.go (hunk 2 above)
Comment (guydc) [reply api/v1alpha1/ext_proc_types.go:20]: yes. https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-externalprocessor. 

> failure_mode_allow
([bool](https://developers.google.com/protocol-buffers/docs/proto#scalar)) If the BodySendMode in the [processing_mode](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-field-extensions-filters-http-ext-proc-v3-externalprocessor-processing-mode) is set to FULL_DUPLEX_STREAMED, failure_mode_allow can not be set to true.

Comment (arkodg) [reply api/v1alpha1/ext_proc_types.go:20]: Thanks !

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]
