### PR TITLE
fix: fix topology injector bug

### LINKED ISSUE #5890: Topology injector blocking envoy proxy from starting
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: The expected value isn't returned, etc.

Noticed envoy-proxy pods were not starting

```
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
```

in the envoy gateway logs, I noticed topology injector failures

```
2025-05-01T15:58:03.840Z	ERROR	provider	kubernetes/topology_injector.go:78	error decoding patch: unexpected end of JSON inputpatch pod failedpodenvoy-gateway-system/envoy-default-eg-e41e7b31-654ccf5f87-mw6hk	{"runner": "provider"}
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by jukie**
**What type of PR is this?**

fix: fix topology injector bugs

**What this PR does / why we need it**:
* Fix caBundle
* Fix patch - patches binding resource instead and uses annotation env var

**Which issue(s) this PR fixes**:

Fixes #5890

Release Notes: No

### CODE REVIEW

File: internal/infrastructure/kubernetes/proxy/resource.go [hunk 1]
```diff
@@ -402,7 +402,7 @@ func expectedContainerEnv(containerSpec *egv1a1.KubernetesContainerSpec, gateway
 			ValueFrom: &corev1.EnvVarSource{
 				FieldRef: &corev1.ObjectFieldSelector{
 					APIVersion: "v1",
-					FieldPath:  fmt.Sprintf("metadata.labels['%s']", corev1.LabelTopologyZone),
+					FieldPath:  fmt.Sprintf("metadata.annotations['%s']", corev1.LabelTopologyZone),
```
Comment (zirain) [inline internal/infrastructure/kubernetes/proxy/resource.go:405]: why change from labels to annotations?

Comment (jukie) [reply internal/infrastructure/kubernetes/proxy/resource.go:405]: Annotations from `Binding` will get copied to the pod unlike labels so it saves an extra resource to handle during webhook execution.

Comment (arkodg) [reply internal/infrastructure/kubernetes/proxy/resource.go:405]: ah cool !

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]
