### PR TITLE
fix: bound BackendTrafficPolicy rateLimit requests to uint32 max

### LINKED ISSUE #8797: BackendTrafficPolicy: rate limit `requests` silently truncated to uint32 (root cause of ai-gateway#2012 / ai-gateway#2066)
`BackendTrafficPolicy.spec.rateLimit.{global,local}.rules[].limit.requests` is unbounded in the CRD but narrowed to `uint32` by the xDS translator (`internal/xds/translator/ratelimit.go`, `internal/xds/translator/local_ratelimit.go`). Values above `4294967295` are silently truncated modulo `2^32`  e.g. `30000000000` becomes `4230196224`, rate limiting users at ~14% of intent with no error.

The wire format really is `uint32` (RLS `RateLimitPolicy.requests_per_unit`, Envoy `TokenBucket.max_tokens`/`tokens_per_fill`), so the fix is to reject out-of-range values at admission:

```go
// api/v1alpha1/ratelimit_types.go
type RateLimitValue struct {
    // +kubebuilder:validation:Minimum=1
    // +kubebuilder:validation:Maximum=4294967295
    Requests uint          `json:"requests"`
    Unit     RateLimitUnit `json:"unit"`
}
```

Reported via [ai-gateway#2012](https://github.com/envoyproxy/ai-gateway/issues/2012); the AI-gateway-side workaround in [ai-gateway#2066](https://github.com/envoyproxy/ai-gateway/pull/2066) only covers AIGatewayRoutes with `io.envoy.ai_gateway` cost metadata, fixing it here covers every `BackendTrafficPolicy` user.

### PR DESCRIPTION
**Pull request by PatilHrushikesh**
**What type of PR is this?**

`api`: bound `BackendTrafficPolicy` rate limit `requests` to uint32 max

**What this PR does / why we need it**:

`RateLimitValue.Requests` is unbounded in the CRD but narrowed with an unchecked `uint32(...)` cast in the xDS translator. Since the RLS config proto (`RateLimitPolicy.requests_per_unit`) and Envoy's `TokenBucket` (`max_tokens` / `tokens_per_fill`) are `uint32` on the wire, values above `4294967295` get silently truncated modulo `2^32` (e.g. `30000000000` → `4230196224`, ~14% of intent). This PR adds `+kubebuilder:validation:Minimum=1 / Maximum=4294967295` to `RateLimitValue.Requests`, regenerates the CRDs and helm-template snapshots, and adds CEL validation coverage (boundary, above-max with the 30B repro value, zero, and the local-RL path). The existing `uint32(...)` narrowings in `internal/xds/translator/ratelimit.go` and `internal/xds/translator/local_ratelimit.go` are now safe by construction.

**Which issue(s) this PR fixes**:

Fixes #8797
Refs envoyproxy/ai-gateway#2012

Release Notes: Yes

### CODE REVIEW

File: api/v1alpha1/ratelimit_types.go [hunk 1]
```diff
@@ -432,6 +432,17 @@ type PathMatch struct {
...
+	//
+	// The value is bounded by the uint32 range because the upstream rate
+	// limit service config proto (RateLimitPolicy.requests_per_unit) and
+	// Envoy's local rate-limit TokenBucket (max_tokens / tokens_per_fill)
+	// are uint32 on the wire. Values above 4294967295 would otherwise be
+	// silently truncated modulo 2^32.
+	//
+	// +kubebuilder:validation:Minimum=1
+	// +kubebuilder:validation:Maximum=4294967295
 	Requests uint          `json:"requests"`
```
Comment (jukie) [inline api/v1alpha1/ratelimit_types.go]: Would it be sufficient to use int32 or uint32 for the api fields?

Comment (jukie) [reply api/v1alpha1/ratelimit_types.go]: Can you update the input value in one of the testdata examples to confirm rendering?

https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/testdata/backendtrafficpolicy-with-ratelimit.in.yaml

Also one of the examples under internal/xds/translator

Comment (PatilHrushikesh) [reply api/v1alpha1/ratelimit_types.go]: Done

Comment (jukie) [reply api/v1alpha1/ratelimit_types.go]: Guessing we'll need the same type change in https://github.com/envoyproxy/gateway/blob/main/internal/ir/xds.go too.

**Review by jukie — APPROVED** [review]

File: api/v1alpha1/ratelimit_types.go [hunk 2]
```diff
@@ -432,7 +432,18 @@ type PathMatch struct {
...
 type RateLimitValue struct {
-	Requests uint          `json:"requests"`
+	// Requests is the number of requests (or cost units, when used with
+	// cost-based rate limiting) allowed per Unit.
+	//
+	// The value is bounded by the uint32 range because the upstream rate
+	// limit service config proto (RateLimitPolicy.requests_per_unit) and
+	// Envoy's local rate-limit TokenBucket (max_tokens / tokens_per_fill)
+	// are uint32 on the wire. Values above 4294967295 would otherwise be
+	// silently truncated modulo 2^32.
```
Comment (jukie) [inline api/v1alpha1/ratelimit_types.go]: Can this be trimmed?

**Review by jukie — CHANGES_REQUESTED** [review]

**Review by jukie — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Review by kkk777-7 — APPROVED** [review]

**Comment by kkk777-7** [comment]
LGTM, thanks!

**Comment by jukie** [comment]
Great, thanks!
