### PR TITLE
fix(crd): correct EnvoyPatchPolicy printer columns

### LINKED ISSUE #7745: EnvoyPatchPolicy CRD printer column references non-existent field, STATUS column empty in kubectl get
*Description*:
When running kubectl get envoypatchpolicies.gateway.envoyproxy.io, the STATUS column is always empty, even though the EnvoyPatchPolicy is successfully applied (Accepted and Programmed).

The CRD defines an additionalPrinterColumns entry pointing to .status.conditions[?(@.type=="Programmed")].reason. However, EnvoyPatchPolicy stores conditions under .status.ancestors[].conditions following Gateway API conventions.
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
Envoy Gateway version: v1.6.1
Envoy version: distroless-v1.36.3

*Logs*:
here https://github.com/envoyproxy/gateway/blob/main/charts/gateway-crds-helm/templates/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml#L21
it should be 
```
additionalPrinterColumns:
- name: Accepted
  type: string
  jsonPath: .status.ancestors[0].conditions[?(@.type=="Accepted")].status
- name: Programmed
  type: string
  jsonPath: .status.ancestors[0].conditions[?(@.type=="Programmed")].status
- name: Age
  type: date
  jsonPath: .metadata.creationTimestamp

```

### PR DESCRIPTION
**Pull request by Aditya7880900936**
**What type of PR is this?**

fix(crd): correct EnvoyPatchPolicy printer columns

**What this PR does / why we need it**:

This PR fixes the `additionalPrinterColumns` configuration for the
EnvoyPatchPolicy CRD.

Previously, the STATUS column was empty because the printer column
referenced a non-existent field under `.status.conditions`.
EnvoyPatchPolicy follows Gateway API conventions and stores conditions
under `.status.ancestors[].conditions`.

This change updates the printer columns to reference condition `status`
under `.status.ancestors[].conditions`, so
`kubectl get envoypatchpolicies` correctly shows Accepted and Programmed
states.

**Which issue(s) this PR fixes**:

Fixes #7745

Release Notes: No

### CODE REVIEW

**Review by chaima-belhedi — APPROVED** [review]
Thanx for taking care of this @Aditya7880900936

**Comment by Aditya7880900936** [comment]
Thanks a lot for the review and approval! Appreciate your time and guidance @chaima-belhedi

**Comment by arkodg** [comment]
how did you fix this without updating any markers

**Comment by arkodg** [comment]
you need to edit https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/envoypatchpolicy_types.go

**Comment by Aditya7880900936** [comment]
Thanks for the pointer!
I’ve updated the kubebuilder printcolumn annotations in envoypatchpolicy_types.go to reference status.ancestors[].conditions per Gateway API conventions and regenerated the CRDs.
Please let me know if anything else needs adjustment.

**Comment by zirain** [comment]
please run `make -k gen-check` locally, and commit the changes.

**Comment by Aditya7880900936** [comment]
I’ve run make -k gen-check locally and committed the updated helm test outputs.
Thanks!

File: api/v1alpha1/envoypatchpolicy_types.go [hunk 1]
```diff
@@ -19,7 +19,8 @@ const (
 // +kubebuilder:object:root=true
 // +kubebuilder:resource:categories=envoy-gateway,shortName=epp
 // +kubebuilder:subresource:status
-// +kubebuilder:printcolumn:name="Status",type=string,JSONPath=`.status.conditions[?(@.type=="Programmed")].reason`
+// +kubebuilder:printcolumn:name="Accepted",type=string,JSONPath=`.status.ancestors[0].conditions[?(@.type=="Accepted")].status`
```
Comment (zirain) [inline api/v1alpha1/envoypatchpolicy_types.go:22]: why we only check the first ancestors?

Comment (zirain) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: is it possible to check any or all?

Comment (Aditya7880900936) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: status.ancestors can contain multiple entries, but kubectl printer columns need to resolve to a single scalar value and don’t support aggregation across arrays. Because of that, checking “any” or “all” ancestors isn’t supported in printer columns today.

Using ancestors[0] follows the existing Gateway API convention to surface the primary attachment point, and is consistent with how other policy CRDs expose status via printer columns.

Happy to adjust if there’s a preferred convention here.

Comment (zirain) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: what would happen if we use `ancestors[*]` here?

Comment (Aditya7880900936) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: If we use `ancestors[*]`, the JSONPath evaluation would return a list of values rather than a single scalar (e.g. `["True", "False"]` when multiple ancestors exist).

Kubectl printer columns don’t support aggregation or reduction over arrays, so returning a list can lead to unstable or non-deterministic output (empty values, joined lists, or differing behavior across kubectl versions).

That’s why most CRDs constrain printer columns to a single, deterministic value. Using `ancestors[0]` follows the existing Gateway API convention to surface the primary attachment point and keeps the printer column output stable and predictable.

For full multi-ancestor status, users can still inspect `.status.ancestors` directly via `kubectl get -o yaml`.

Comment (zirain) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: it's fine to me use `ancestors[0]`, it's should be accepted for all or none.

@envoyproxy/gateway-maintainers PTAL

Comment (Aditya7880900936) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: Thanks for confirming! Happy to keep it consistent with `ancestors[0]` for both.

**Comment by Aditya7880900936** [comment]
The remaining CI failures are from coverage-test.
This PR only updates CRD annotations and regenerated manifests, with no executable Go logic changes, so no additional coverage is produced.

Please let me know if you’d prefer:

skipping/overriding coverage for this PR, or

any specific test adjustments you’d like me to make.

File: api/v1alpha1/envoypatchpolicy_types.go (hunk 1 above)
Comment (arkodg) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: yeah this is fine imo, order is unlikely to change

Comment (arkodg) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: does this work properly even when no status is set ? (when `extensionApis.enableEnvoyPatchPolicy: false`)

Comment (Aditya7880900936) [reply api/v1alpha1/envoypatchpolicy_types.go:22]: Good question — yes, this should behave fine.

When `extensionApis.enableEnvoyPatchPolicy` is false, the controller doesn’t populate .status, so the JSONPath won’t resolve. In that case, kubectl printer columns simply render an empty value rather than erroring.

This is consistent with other Gateway API resources where status may be absent or delayed, and matches existing printer column behavior across CRDs.

Users can still inspect the full object via `kubectl get -o yaml` if needed.

**Comment by Aditya7880900936** [comment]
Friendly ping — happy to help unblock if anything else is needed.

**Comment by Aditya7880900936** [comment]
Thanks for the reviews and approvals!
The remaining CI failures are coverage-related and expected for this CRD-only change.
Happy to let maintainers decide the best way to proceed.

**Comment by Aditya7880900936** [comment]
Hi @zirain ,

The PR has approvals now. The only remaining CI failures are coverage tests, which appear expected for this CRD-only change.

Please let me know if you’re okay to merge as-is, or if you’d like me to make any changes before merge.

**Comment by Aditya7880900936** [comment]
Thanks everyone for the reviews and help!

**Comment by Aditya7880900936** [comment]
Friendly ping @zirain — whenever you’re back online, please take a look.
Happy to help if anything else is needed. Thanks!

**Comment by Aditya7880900936** [comment]
Hi @zirain ,
I checked the failing e2e jobs.

They fail in ZoneAwareRouting / BackendTrafficPolicy tests, which don’t appear related to this PR (CRD printer column metadata only).
The failure happens late in the suite and looks consistent with known e2e flakiness.

I’ve updated the branch to latest main.
Happy to re-run CI or dig further if needed.

**Comment by Aditya7880900936** [comment]
Hi @zirain,

I’ve updated the branch to the latest main.

The remaining CI failures are in e2e-related jobs (ZoneAwareRouting / BackendTrafficPolicy) and don’t appear related to this change, which only updates CRD printer column metadata. The failures occur late in the suite and look consistent with known e2e flakiness.

All reviews are approved. Would you mind re-running the failing jobs or overriding CI if you’re comfortable?

Happy to investigate further if you think there’s any possible linkage I’m missing.
Thanks!
