### PR TITLE
fix(gatewayapi): reject ClientTrafficPolicy with invalid TLS cipher

### LINKED ISSUE #7400: ClientTrafficPolicy with invalid TLS cipher is marked as "Accepted" instead of being rejected
*Description*:
When applying a `ClientTrafficPolicy` with an invalid TLS cipher, Envoy Gateway marks the policy as **Accepted**, even though Envoy later fails to apply the configuration due to the invalid cipher.

**Expected behavior:**
The `ClientTrafficPolicy` should **not** be marked as `Accepted` if it contains invalid TLS cipher suites. The controller should validate the cipher list and report a validation or reconciliation error, preventing invalid configurations from reaching Envoy.

**Actual behavior:**
The policy is accepted by the controller:

```yaml
status:
  ancestors:
  - ancestorRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
      namespace: gateway-envoy
    conditions:
    - lastTransitionTime: "2025-10-31T16:14:11Z"
      message: Policy has been accepted.
      observedGeneration: 20
      reason: Accepted
      status: "True"
      type: Accepted
```

However, Envoy rejects the listener configuration with an error indicating the cipher is invalid.

*Repro steps*:
1. Create a `ClientTrafficPolicy` with an invalid cipher name:

   ```yaml
   apiVersion: gateway.envoyproxy.io/v1alpha1
   kind: ClientTrafficPolicy
   metadata:
     name: eg
     namespace: gateway-envoy
   spec:
     targetRefs:
       - group: gateway.networking.k8s.io
         kind: Gateway
         name: eg
     tls:
       minVersion: "1.0"
       ciphers:
         - "ECDHE-ECDSA-AES128-GCM-SHA256"
         - "WRONG"
   ```
2. Apply the manifest:

   ```bash
   kubectl apply -f client-traffic-policy.yaml
   ```
3. Check the policy status:

   ```bash
   kubectl -n gateway-envoy get ClientTrafficPolicy eg -o yaml
   ```

   → The policy shows as `Accepted`.
4. Check the Envoy Gateway controller logs — you will see an Envoy xDS error:

   ```
   ERROR  Envoy rejected the last update with code 13 and message:
   Error adding/updating listener(s) gateway-envoy/eg/https:
   Failed to initialize cipher suites ECDHE-ECDSA-AES128-GCM-SHA256:WRONG.
   The following ciphers were rejected when tried individually: WRONG
   ```

*Environment*:
`gateway-helm-v1.5.4`
`image: envoyproxy/envoy:v1.35.6`

*Logs*:
```
2025-10-31T16:25:42.094Z ERROR xds cache/snapshotcache.go:352 Envoy rejected the last update with code 13 and message Error adding/updating listener(s) gateway-envoy/eg/https: Failed to initialize cipher suites ECDHE-ECDSA-AES128-GCM-SHA256:WRONG. The following ciphers were rejected when tried individually: WRONG
```

### PR DESCRIPTION
**Pull request by Junnygram**
**What type of PR is this?**
fix(gatewayapi): reject ClientTrafficPolicy with invalid TLS cipher

**What this PR does / why we need it**:
This PR adds validation for the `ciphers` field in `ClientTrafficPolicy` TLS settings. Previously, `ClientTrafficPolicy` resources with invalid or unsupported TLS cipher suites were marked as `Accepted: True`, but the invalid configuration would fail silently or be ignored in the data plane.

This change ensures that if a user provides a cipher suite that is not in the allowed list of supported Envoy cipher suites, the `ClientTrafficPolicy` status will report a `Accepted: False` condition with a descriptive message (e.g., `TLS: unsupported cipher suite: INVALID-CIPHER.`).

**Which issue(s) this PR fixes**:
Fixes #7400

**Release Notes**:
```yaml
- type: fix
  area: gatewayapi
  issue: 7400
  description: Rejected ClientTrafficPolicy if invalid TLS cipher suites are configured.
```

### CODE REVIEW

File: internal/gatewayapi/tls.go [hunk 1]
```diff
@@ -16,6 +16,24 @@ import (
 	gwapiv1 "sigs.k8s.io/gateway-api/apis/v1"
 
 	"github.com/envoyproxy/gateway/internal/gatewayapi/status"
+	"k8s.io/apimachinery/pkg/util/sets"
+)
+
```
Comment (arkodg) [inline internal/gatewayapi/tls.go:21]: can we add a link here of where the source of truth is coming from (envoy docs)

Comment (Junnygram) [reply internal/gatewayapi/tls.go:21]: Done, anything else ?

Comment (arkodg) [reply internal/gatewayapi/tls.go:21]: https://github.com/envoyproxy/envoy/blob/cbe23a824a70006f26aac478c6ca8bc42e968d30/test/common/tls/context_impl_test.cc#L52 seems like a better link to add here,
seeing some diff between the two sets, should we add them all here ?
cc @guydc

**Review by zirain — DISMISSED** [review]

**Review by zhaohuabing — CHANGES_REQUESTED** [review]
Do we need to update the docs for `api/v1alpha1/tls_types.go` `TLSSettings.Ciphers` to list the allowed Ciphers there(Or a link to the allowed Ciphers)?

**Comment by arkodg** [comment]
@Junnygram can you fix CI (`make lint` && `make generate`)

**Comment by zirain** [comment]
please run `make gen-check` and commit the changes to make CI happy.

**Comment by Junnygram** [comment]
> please run `make gen-check` and commit the changes to make CI happy.




I fought the make generate and make generate won.

File: release-notes/current.yaml [hunk 2]
```diff
@@ -10,6 +10,19 @@ security updates: |
 new features: |
 
 bug fixes: |
+  Fixed configured OIDC authorization endpoint being overridden by discovered endpoints from issuer's well-known URL.
```
Comment (zirain) [inline release-notes/current.yaml]: this's not right after rebase/merge.

Comment (Junnygram) [reply release-notes/current.yaml]: can you review now @zirain

File: internal/gatewayapi/testdata/clienttrafficpolicy-for-tcp-listeners.out.yaml [hunk 3]
```diff
@@ -233,74 +228,15 @@ xdsIR:
...
-              name: envoy-gateway/tls-secret-1
-              privateKey: '[redacted]'
-            ciphers:
-            - cipher1
```
Comment (arkodg) [inline internal/gatewayapi/testdata/clienttrafficpolicy-for-tcp-listeners.out.yaml:271]: can we add some valid inputs for this case so this doesnt get deleted, its supposed to be a positive case

Comment (Junnygram) [reply internal/gatewayapi/testdata/clienttrafficpolicy-for-tcp-listeners.out.yaml:271]: @arkodg  Just to clarify, do you mean I should replace the invalid 'cipher1' with a valid cipher (e.g. ECDHE-RSA-AES128-GCM-SHA256) in the test data?

Comment (arkodg) [reply internal/gatewayapi/testdata/clienttrafficpolicy-for-tcp-listeners.out.yaml:271]: yeah, thanks

**Review by arkodg — DISMISSED** [review]

**Comment by zirain** [comment]
@Junnygram can you fix the conflict?

**Review by zirain — APPROVED** [review]

File: internal/gatewayapi/tls.go (hunk 1 above)
Comment (guoard) [reply internal/gatewayapi/tls.go:21]: > seeing some diff between the two sets, should we add them all here

This comment was never addressed.
For example, I’m using the ECDHE-RSA-AES128-SHA256 cipher. It’s a valid cipher, but it’s not included in any of those lists.

I think all cipher suites supported by BoringSSL should be included.

**Comment by guoard** [comment]
Sorry to comment on this closed pull request, but I wanted to resurface a resolved review thread that may still need attention.

@arkodg In comment https://github.com/envoyproxy/gateway/pull/8040#discussion_r2725789123 you said:

> https://github.com/envoyproxy/envoy/blob/cbe23a824a70006f26aac478c6ca8bc42e968d30/test/common/tls/context_impl_test.cc#L52 seems like a better link to add here,
> seeing some diff between the two sets, should we add them all here ?

and in the next comment i said:

> This comment was never addressed.
> For example, I’m using the ECDHE-RSA-AES128-SHA256 cipher. It’s a valid cipher, but it’s not included in any of those lists.

> I think all cipher suites supported by BoringSSL should be included.

Since that review resolved, it is not visible by default. Could you please recheck this?
