### PR TITLE
fix: null pointer when CORS maxAge is not specified

### LINKED ISSUE #2132: Null pointer when CORS maxAge is not specified
goroutine 125 [running]:
github.com/envoyproxy/gateway/internal/xds/translator.patchRouteWithCORSConfig(0xc0001c7680, 0xc00037e780)
      /home/ubuntu/gateway/internal/xds/translator/cors.go:129 +0x5a7
github.com/envoyproxy/gateway/internal/xds/translator.patchRouteWithFilters(0xc0001c7680, 0x0?)
      /home/ubuntu/gateway/internal/xds/translator/httpfilters.go:133 +0x65
github.com/envoyproxy/gateway/internal/xds/translator.buildXdsRoute(0xc00037e780)
      /home/ubuntu/gateway/internal/xds/translator/route.go:80 +0x1085
github.com/envoyproxy/gateway/internal/xds/translator.(*Translator).processHTTPListenerXdsTranslation(0xc000e73d80, 0xc001226d60, {0xc0006c2618, 0x1, 0x0?}, 0x0?, 0x2948508?, 0x0)
      /home/ubuntu/gateway/internal/xds/translator/translator.go:203 +0xb2c
github.com/envoyproxy/gateway/internal/xds/translator.(*Translator).Translate(0xc000e73d80, 0xc0009c6f80)
      /home/ubuntu/gateway/internal/xds/translator/translator.go:67 +0x70
github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).subscribeAndTranslate.func1({{0xc000f18cc0?, 0x0?}, 0x4d?, 0xc0009c6f80?}, 0x0?)
      /home/ubuntu/gateway/internal/xds/translator/runner/runner.go:80 +0x265
github.com/envoyproxy/gateway/internal/message.HandleSubscription[...]({{0x25efe06, 0x2945910?}, {0x25e294d?, 0x0?}}, 0xc00073ac60?, 0xc000e73f98)
      /home/ubuntu/gateway/internal/message/watchutil.go:76 +0x47d
github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).subscribeAndTranslate(0xc000b36100, {0x2945910?, 0xc000710cd0?})
      /home/ubuntu/gateway/internal/xds/translator/runner/runner.go:52 +0x8d
created by github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).Start
      /home/ubuntu/gateway/internal/xds/translator/runner/runner.go:45 +0x272

### PR DESCRIPTION
**Pull request by zhaohuabing**
fix https://github.com/envoyproxy/gateway/issues/2132

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
if it is nil, will it have the default value?

**Comment by zhaohuabing** [comment]
> if it is nil, will it have the default value?

It's an optional setting, the default value is an empty stering.

**Review by Xunzhuo — APPROVED** [review]

File: internal/xds/translator/cors.go [hunk 1]
```diff
@@ -126,7 +126,9 @@ func patchRouteWithCORSConfig(route *routev3.Route, irRoute *ir.HTTPRoute) error
 	allowMethods = strings.Join(irRoute.CORS.AllowMethods, ", ")
 	allowHeaders = strings.Join(irRoute.CORS.AllowHeaders, ", ")
 	exposeHeaders = strings.Join(irRoute.CORS.ExposeHeaders, ", ")
-	maxAge = strconv.Itoa(int(irRoute.CORS.MaxAge.Seconds()))
+	if irRoute.CORS.MaxAge != nil {
```
Comment (arkodg) [inline internal/xds/translator/cors.go:129]: can you add a test that only sets `allowOrigins` and `allowMethods` are rest are unset ?

**Review by arkodg — APPROVED** [review]
