### PR TITLE
bugfix: the controller cannot read the EnvoyProxy attached gatewayclass only.

### LINKED ISSUE #6832: the controller read the customized service name from EnvoyProxy failed
Set the customized service name in  EnvoyProxy, and the EnvoyProxy has attached to GatewayClass

Image

But the controller reports the auto-generated service name

Image

### PR DESCRIPTION
**Pull request by qicz**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6832 

Release Notes: Yes

### CODE REVIEW

File: internal/provider/kubernetes/controller.go [hunk 1]
```diff
@@ -1481,7 +1481,7 @@ func (r *gatewayAPIReconciler) processGateways(ctx context.Context, managedGC *g
 				// processGatewayParamsRef has been called for this gateway, its EnvoyProxy should exist in resourceTree
 				ep = resourceTree.GetEnvoyProxy(gtw.Namespace, gtw.Spec.Infrastructure.ParametersRef.Name)
 			}
-			r.processServiceClusterForGateway(ep, &gtw, resourceMap)
+			r.processServiceClusterForGateway(ep, &gtw, resourceMap, resourceTree)
```
Comment (zirain) [inline internal/provider/kubernetes/controller.go]: we can do the check at L1483 instead of processServiceClusterForGateway

Comment (qicz) [reply internal/provider/kubernetes/controller.go]: I think the check logic is a part of the `processServiceClusterForGateway`

Comment (zirain) [reply internal/provider/kubernetes/controller.go]: the name called `processServiceClusterForGateway`, so we'd need do the check before call it.
there's another one called `processServiceClusterForGatewayClass`.

Comment (qicz) [reply internal/provider/kubernetes/controller.go]: ok, deal with this after #6847 and add the release note for this bug

File: internal/envoygateway/config/testdata/decoder/in/gateway-logging.yaml
Comment (zirain) [inline internal/envoygateway/config/testdata/decoder/in/gateway-logging.yaml:1]: why remove this?

Comment (qicz) [reply internal/envoygateway/config/testdata/decoder/in/gateway-logging.yaml:1]: bad commit

**Review by zirain — DISMISSED** [review]

**Review by shawnh2 — APPROVED** [review]
