### PR TITLE
fix: proxies going from HTTP => HTTPS: matching upstream http(s) scheme

### LINKED ISSUE #7979: .NET servers reject https gRPC requests terminated to plaintext by Envoy
*Description*:
This appears to be the same behavior reported in https://github.com/istio/istio/issues/34448 and has to do with the way Envoy preserves `:scheme`.
> When an application makes an https gRPC request to a .NET server behind an Istio proxy or gateway and Envoy terminates the request to plaintext, starting in 1.10 Envoy preserves :scheme as https. .NET sees the mismatch between the scheme and the fact that the request from Envoy is plaintext and raises an error, rejecting the request.

My org runs a lot of .NET services and during the migration from ingress-nginx this has become an issue for grpc services. I think we should expose the ability to configure [SchemeHeaderTransformation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-schemeheadertransformation) in ~BackendTrafficPolicy~ so that users can configure this. Since SchemeHeaderTransformation is an HCM level configuration ClientTrafficPolicy is right place to add this.

*Repro steps*:
- Build a .NET backend with a gRPC listenter
- GRPCRoute with TLS termination at the gateway and plaintext upstream

### PR DESCRIPTION
**Pull request by andreaswachs**
This makes it possible to use gateways that are internally exposed to Kubernetes as an HTTP service that proxies to a strictly HTTPS service. Some HTTPS services will declare a protocol error when an HTTPS request is forwarded towards them but the HTTP2 `:scheme` header is still set to `http`.

**What type of PR is this?**

This fixes issues with proxying from an internally exposed HTTP proxy, that proxies to strict HTTPS services

**What this PR does / why we need it**:

I have found issues with a Envoy Gateway deployment that is internal to a Kubernetes cluster, exposed with an HTTP listener. It is talking to an HTTP/2 service that strictly speaks HTTPS. The `:scheme` meta header were being passed from the downstream source as `http` even though the backend were configured as HTTPS.

This remediation attempts to base the scheme of the proxied requests to match what the upstream is serving.

The same issue in spirit has been discussed before, specifically for the Envoy Proxy: https://github.com/envoyproxy/envoy/issues/16255

I have tested this change in a local kind cluster hand have found it to fix my issue.

**Note to reviewers**: I am not well versed in this Envoy Gateway code base and I welcome any and all critique and comments. I don't have the experience to foresee the consequences of this change for users, if there are any.

Release Notes: Yes

Fixes #7979

### CODE REVIEW

**Comment by zirain** [comment]
xref: https://github.com/envoyproxy/envoy/issues/33020

File: internal/xds/translator/listener.go [hunk 1]
```diff
@@ -355,6 +355,11 @@ func (t *Translator) addHCMToXDSListener(
 		HttpProtocolOptions: http1ProtocolOptions(irListener.HTTP1),
 		// Hide the Envoy proxy in the Server header by default
 		ServerHeaderTransformation: hcmv3.HttpConnectionManager_PASS_THROUGH,
+		// Set the :scheme header to match the upstream transport protocol (http/https)
+		// This ensures correct scheme is sent to backends using TLS
+		SchemeHeaderTransformation: &corev3.SchemeHeaderTransformation{
+			MatchUpstream: true,
+		},
```
Comment (jukie) [inline internal/xds/translator/listener.go]: Can this be made configurable? This may have conflicts with `useClientProtocol ` in BackendTrafficPolicy

Comment (jukie) [reply internal/xds/translator/listener.go]: I think this would be great to support so thank you for opening but we need to think through how this should be applied alongside existing fields and/or whether it should be merged into that logic.

Comment (andreaswachs) [reply internal/xds/translator/listener.go]: Thanks for the feedback! I will look into making this configurable :)

Comment (andreaswachs) [reply internal/xds/translator/listener.go]: I have cooked something up in the latest commit to make it configurable. Please let me know what you think

File: api/v1alpha1/backendtrafficpolicy_types.go [hunk 2]
```diff
@@ -73,6 +73,21 @@ type BackendTrafficPolicySpec struct {
 	// +optional
 	UseClientProtocol *bool `json:"useClientProtocol,omitempty"`
 
+	// UpstreamScheme configures how the :scheme pseudo-header is set for requests forwarded to backends.
```
Comment (arkodg) [inline api/v1alpha1/backendtrafficpolicy_types.go]: can we use `Client` and `Backend` instead of `Downstream` and `Upstream` to match existing API

Comment (andreaswachs) [reply api/v1alpha1/backendtrafficpolicy_types.go]: I have added a commit with renames - let me know if you like it or if there are more adjustments needed

Comment (arkodg) [reply api/v1alpha1/backendtrafficpolicy_types.go]: still using Downstream and Upstream in the Enums

Comment (andreaswachs) [reply api/v1alpha1/backendtrafficpolicy_types.go]: Ah, I have misunderstood you - I thought you only meant the "public facing" API. I'll adjust

Comment (andreaswachs) [reply api/v1alpha1/backendtrafficpolicy_types.go]: Ah sorry I have missed this

Comment (andreaswachs) [reply api/v1alpha1/backendtrafficpolicy_types.go]: @arkodg would it make sense to rename the field new field `clientScheme` that this PR introduces on the BackendTrafficPolicy spec to `scheme` instead if I rename the enum values to `Preserve` and `MatchBackend`?

File: api/v1alpha1/backendtrafficpolicy_types.go [hunk 3]
```diff
@@ -73,6 +73,21 @@ type BackendTrafficPolicySpec struct {
...
+	//
+	// - MatchUpstream: Sets the :scheme to match the upstream transport protocol.
+	//   If the backend uses TLS, the scheme is "https", otherwise "http".
+	//   Use this when backends require the scheme to match the actual transport protocol,
+	//   such as strictly HTTPS services that validate the :scheme header.
+	//
+	// This setting only takes effect when BackendTrafficPolicy targets a Gateway.
+	//
+	// +optional
+	ClientScheme *ClientScheme `json:"clientScheme,omitempty"`
```
Comment (jukie) [inline api/v1alpha1/backendtrafficpolicy_types.go]: Since this is a listener level field it should probably be under ClientTrafficPolicy. I don't think it's possible to apply this per-route

File: api/v1alpha1/backendtrafficpolicy_types.go (hunk 2 above)
Comment (arkodg) [reply api/v1alpha1/backendtrafficpolicy_types.go]: sure +1
cc @jukie

File: api/v1alpha1/backendtrafficpolicy_types.go (hunk 3 above)
Comment (arkodg) [reply api/v1alpha1/backendtrafficpolicy_types.go]: +1

Comment (andreaswachs) [reply api/v1alpha1/backendtrafficpolicy_types.go]: I have moved the field (that is now renamed)

File: api/v1alpha1/backendtrafficpolicy_types.go (hunk 2 above)
Comment (andreaswachs) [reply api/v1alpha1/backendtrafficpolicy_types.go]: I've renamed the field (and also moved it to the Client Traffic Policy CR)

**Review by arkodg — APPROVED** [review]
LGTM thanks

File: release-notes/current.yaml [hunk 4]
```diff
@@ -29,12 +26,10 @@ bug fixes: |
...
   Fixed CRL ref not processed by gateway controller.
-
 # Enhancements that improve performance.
-performance improvements: |
-
+performance improvements: ""
 # Deprecated features or APIs.
-deprecations: |
-
+deprecations: ""
```
Comment (zirain) [inline release-notes/current.yaml]: Nit: unreleated changes.

**Review by zirain — APPROVED** [review]

File: release-notes/current.yaml (hunk 4 above)
Comment (jukie) [reply release-notes/current.yaml]: I'll follow up with a fix to this and add docs from my PR

**Comment by jukie** [comment]
Thanks @andreaswachs! Can you fix the conflicts so we can get this in?

File: release-notes/current.yaml (hunk 4 above)
Comment (jukie) [reply release-notes/current.yaml]: There's merge conflicts anyways so please fix this during the rebase @andreaswachs

File: release-notes/current.yaml [hunk 5]
```diff
@@ -1,5 +1,5 @@
+---
 date: Pending
```
Comment (jukie) [inline release-notes/current.yaml]:
```suggestion
date: Pending

```

**Review by jukie — APPROVED** [review]

File: release-notes/current.yaml (hunk 4 above)
Comment (jukie) [reply release-notes/current.yaml]: Updated

**Comment by jukie** [comment]
Fixed the merge conflict but needs a `make gen-check` @andreaswachs

**Comment by andreaswachs** [comment]
> Fixed the merge conflict but needs a `make gen-check` @andreaswachs

Thank you - done!

**Comment by jukie** [comment]
Still failing  @andreaswachs

**Comment by andreaswachs** [comment]
> Still failing @andreaswachs

I'm sorry, I failed to run all the CI checks that I could locally. I see they are working now and thank you for the approval!

Are the Ci checks on the PR something that I can trigger myself or need it be some of you guys?

**Comment by jukie** [comment]
For first time contributors you'll need someone to approve the workflow run upon each commit but in the future they'll be automatic.

**Comment by jukie** [comment]
Thanks a lot for this @andreaswachs!
