### PR TITLE
fix: handle context errors as transient errors

### LINKED ISSUE #6849: Context cancelled not treated as transient, causing unintended Envoy-Proxy recreation
*Description*:

We encountered an unexpected recreation of the Envoy-Proxy deployment, which caused traffic disruption. After investigating, we found that a network issue triggered Envoy-Gateway to recreate the Envoy-Proxy deployment.

The logs indicate that while processingGateways, the system received a `context cancelled` error. This error was not handled as a transient error, which caused the remaining logic to incorrectly assume that zero Gateways existed, and eventually led to the deletion of the Envoy-Proxy deployment.

Expected: These context errors (`deadline exceeded` or `context cancelled`) should be treated as transient, allowing retry.
Actual: They are treated as non-transient, which may cause unexpected failures—such as the issue we experienced and the one reported [here](https://github.com/envoyproxy/gateway/issues/6284).

*Repro steps*:

1. Send a context with a tight timeout or manually cancel the request context.
2. Observe that the context returns `deadline exceeded` or `context cancelled`.
3. The system doesn't classify this as a transient error and continuing with a corrupted truth.

*Environment*:

EG v1.4.2

*Logs*:

An error correctly marked as a transient error:
>2025-08-25T19:34:24.009Z	ERROR	provider	kubernetes/controller.go:295	transient error processing gateways	{"runner": "provider", "gatewayClass": "eg", "error": "failed to list <resource>: etcdserver: leader changed"}

Examples of errors not marked as transient:

>2025-08-25T14:47:35.097Z	ERROR	provider	kubernetes/controller.go:298	failed processGateways for gatewayClass eg, skipping it	{"runner": "provider", "error": "failed to list <resource>: client rate limiter Wait returned an error: context canceled"}
>2025-08-25T14:47:31.632Z	ERROR	provider	kubernetes/controller.go:298	failed processGateways for gatewayClass eg, skipping it	{"runner": "provider", "error": "failed to list <resource>: context canceled"}

### PR DESCRIPTION
**Pull request by TomerJLevy**
**What type of PR is this?**
fix(provider): handle context errors as transient

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
This PR updates the error handling logic so that `context cancelled` and `deadline exceeded` are classified as transient errors.
Currently, these errors are not treated as transient; This can result in unintended behaviors such as Envoy-Proxy deployment recreation.
By treating these errors as transient, the system will retry or recover gracefully instead of propagating incorrect state.

Fixes #6849

Release Notes: Yes
Handle `context cancelled` and `deadline exceeded` as transient errors to prevent incorrect state reconciliation and unintended behaviors.

### CODE REVIEW

**Comment by kkk777-7** [comment]
thanks for raising this issue and fixing! Could you add in release notes?
https://github.com/envoyproxy/gateway/blob/main/release-notes/current.yaml

**Comment by zirain** [comment]
@TomerJLevy can you add a release note?

**Review by zhaohuabing — DISMISSED** [review]
LGTM. Thanks for the quick fix!

**Comment by TomerJLevy** [comment]
> @TomerJLevy can you add a release note?

Thanks. I added release notes.
I also returned the error as-is, without any wrapping, so it can be caught as a transient error.
@zhaohuabing and @kkk777-7 let me know what you think.

**Comment by zirain** [comment]
@TomerJLevy can you make CI happy?

File: internal/provider/kubernetes/filters.go [hunk 1]
```diff
@@ -24,8 +24,8 @@ func (r *gatewayAPIReconciler) getExtensionRefFilters(ctx context.Context) ([]un
 		uExtResourceList := &unstructured.UnstructuredList{}
 		uExtResourceList.SetGroupVersionKind(gvk)
 		if err := r.client.List(ctx, uExtResourceList); err != nil {
-			r.log.Info("no associated resources found for %s", gvk.String())
-			return nil, fmt.Errorf("failed to list %s: %w", gvk.String(), err)
```
Comment (zhaohuabing) [inline internal/provider/kubernetes/filters.go]: Why do we need to remove this line?

Comment (TomerJLevy) [reply internal/provider/kubernetes/filters.go]: I was afraid that once we're wrapping the error it won't be caught by the `isTransientError` function, but I tested it now and it indeed getting caught. So I'll revert these changes.

File: internal/provider/kubernetes/filters.go [hunk 2]
```diff
@@ -24,7 +24,7 @@ func (r *gatewayAPIReconciler) getExtensionRefFilters(ctx context.Context) ([]un
 		uExtResourceList := &unstructured.UnstructuredList{}
 		uExtResourceList.SetGroupVersionKind(gvk)
 		if err := r.client.List(ctx, uExtResourceList); err != nil {
-			r.log.Info("no associated resources found for %s", gvk.String())
```
Comment (TomerJLevy) [inline internal/provider/kubernetes/filters.go]: This is to fix DPANIC of improper key–value pairs.

File: internal/provider/kubernetes/filters.go [hunk 3]
```diff
@@ -57,7 +57,7 @@ func (r *gatewayAPIReconciler) getExtensionBackendResources(ctx context.Context)
 		uExtResourceList := &unstructured.UnstructuredList{}
 		uExtResourceList.SetGroupVersionKind(gvk)
 		if err := r.client.List(ctx, uExtResourceList); err != nil {
-			r.log.Info("no associated backend resources found for %s", gvk.String())
```
Comment (TomerJLevy) [inline internal/provider/kubernetes/filters.go]: This is to fix DPANIC of improper key–value pairs.

File: internal/provider/kubernetes/filters.go (hunk 2 above)
Comment (TomerJLevy) [reply internal/provider/kubernetes/filters.go]: I'll address these in a separate PR https://github.com/envoyproxy/gateway/pull/6846

File: internal/provider/kubernetes/filters.go (hunk 3 above)
Comment (TomerJLevy) [reply internal/provider/kubernetes/filters.go]: I'll address these in a separate PR https://github.com/envoyproxy/gateway/pull/6846

**Comment by kkk777-7** [comment]
LGTM, thanks!

**Comment by zirain** [comment]
@TomerJLevy can you fix the conflict?

**Review by zirain — APPROVED** [review]
