### PR TITLE
fix: replace context.TODO with timeout context in config dump

### LINKED ISSUE #8121: context.TODO() used in production code (config_dump.go)
Found `context.TODO()` in production troubleshooting code at `internal/troubleshoot/collect/config_dump.go:69`

**Current:**
```go
pods, err := listPods(context.TODO(), client, cd.Namespace, labels.SelectorFromSet(...))
```

**Issue:**
- No cancellation/timeout support for Kubernetes API calls
- Operations can hang indefinitely if API server is slow
- Can't propagate context from caller

**Fix:**
Accept context parameter in `Collect()` method signature:
```go
func (cd ConfigDump) Collect(ctx context.Context, _ chan<- interface{}) (tbcollect.CollectorResult, error) {
    pods, err := listPods(ctx, client, cd.Namespace, ...)
}
```

Similar pattern found in `internal/troubleshoot/collect/prometheus_metrics.go`

**Location:** `internal/troubleshoot/collect/config_dump.go:69`

### PR DESCRIPTION
**Pull request by jaffarkeikei**
Replaces `context.TODO()` with `context.WithTimeout()` to enable proper cancellation and timeouts.

**Before:**
```go
pods, err := listPods(context.TODO(), client, cd.Namespace, ...)
```

**After:**
```go
ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
defer cancel()
pods, err := listPods(ctx, client, cd.Namespace, ...)
```

**Benefits:**
- Prevents indefinite hangs when Kubernetes API is slow
- Enables proper cancellation
- Follows Go best practices for context propagation

Fixes #8121

### CODE REVIEW

File: internal/troubleshoot/collect/config_dump.go [hunk 1]
```diff
@@ -60,12 +61,15 @@ func (cd ConfigDump) CheckRBAC(_ context.Context, _ tbcollect.Collector, _ *trou
 }
 
 func (cd ConfigDump) Collect(_ chan<- interface{}) (tbcollect.CollectorResult, error) {
+	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
```
Comment (zirain) [inline internal/troubleshoot/collect/config_dump.go]: I would prefer this(30s) be configurable with a default value of 30s.

**Comment by jaffarkeikei** [comment]
Good point! I've updated the implementation to make the timeout configurable:

- Added a `Timeout` field to the `ConfigDump` struct
- Created a `DefaultConfigDumpTimeout` constant set to 30s
- Added a `getTimeout()` helper that returns the configured timeout or falls back to the default

This way, users can customize the timeout when needed, while maintaining the sensible 30s default. Thanks for the review!

**Comment by zirain** [comment]
> Good point! I've updated the implementation to make the timeout configurable:
> 
> * Added a `Timeout` field to the `ConfigDump` struct
> * Created a `DefaultConfigDumpTimeout` constant set to 30s
> * Added a `getTimeout()` helper that returns the configured timeout or falls back to the default
> 
> This way, users can customize the timeout when needed, while maintaining the sensible 30s default. Thanks for the review!

Thanks for your patient, the next step is making it configurable as part of the args in `egctl x collect`.

**Comment by zirain** [comment]
BTW, please fix DCO.

**Comment by jaffarkeikei** [comment]
DCO fixed! Added sign-off to all commits. ✅

**Comment by jaffarkeikei** [comment]
Hi @zirain - Both commits have the Signed-off-by trailer:

**Commit 1 (5bab0f7):**  
```
Signed-off-by: jaffar <keikei.jaffar@mail.utoronto.ca>
```

**Commit 2 (b88453f):**  
```
Signed-off-by: jaffar <keikei.jaffar@mail.utoronto.ca>
```

You can verify by checking the commits directly:
- https://github.com/envoyproxy/gateway/commit/5bab0f79018cc76aed20b988b256f74f36294721
- https://github.com/envoyproxy/gateway/commit/b88453fc9ef2ccc95d42f3bf9f430ed5238906d7

The DCO should pass now. Perhaps the DCO bot needs to re-check? ✅

**Review by arkodg — APPROVED** [review]
