### PR TITLE
fix: when service type = clusterIP set the address to service.clusterIP

### LINKED ISSUE #2166: If Service Type is ClusterIP set spec.addresses.value into ClusterIP
When creating a GW using ClusterIP:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: proxy-config-internal
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP
```

There is no way to set the IP address to be used, if we use spec.adresses it will set the `externalIPs` not the `clusterIP`:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-internal
  namespace: envoy-gateway-system
spec:
  addresses:
    - type: IPAddress
      value: 10.43.146.30
```
```
NAME          CLASS         ADDRESS        PROGRAMMED   AGE
eg-internal   eg-internal   10.43.146.30   True         11m
```
But is in fact this will produce:
```
spec:
  clusterIP: 10.43.65.18
  clusterIPs:
  - 10.43.65.18
  externalIPs:
  - 10.43.146.30
  internalTrafficPolicy: Cluster
```
In a ClusterIP case, setting the clusterIP with spec.addresses.value would probably be more useful.

### PR DESCRIPTION
**Pull request by ShyunnY**
**What type of PR is this?**
fix:  when service type = clusterIP set the address to service.clusterIP 

**What this PR does / why we need it**:

This commit solves the problem that when setting Service Type=ClusterIP and customizing the address for Gateway.spec.addresses, the address is incorrectly set to externalIPs.

I fixed it so that it can be correctly set to the ClusterIP

**Which issue(s) this PR fixes**:

Fixes #2166

### CODE REVIEW

File: internal/infrastructure/kubernetes/proxy/resource_provider.go [hunk 1]
```diff
@@ -120,7 +120,17 @@ func (r *ResourceRender) Service() (*corev1.Service, error) {
...
 	serviceSpec.Ports = ports
 	serviceSpec.Selector = resource.GetSelector(labels).MatchLabels
-	serviceSpec.ExternalIPs = r.infra.Addresses
+
+	if (*envoyServiceConfig.Type) == egv1a1.ServiceTypeClusterIP {
+		if len(r.infra.Addresses) > 0 {
+			// we just need the first one address
+			// if address is not set, the automatically assigned clusterIP is used
+			serviceSpec.ClusterIP = r.infra.Addresses[0]
+			serviceSpec.ClusterIPs = r.infra.Addresses[0:1]
```
Comment (arkodg) [inline internal/infrastructure/kubernetes/proxy/resource_provider.go:129]: should we assign all for `ClusterIPs` ?

**Comment by arkodg** [comment]
we'll also need to update the logic in https://github.com/envoyproxy/gateway/blob/d44f4be1d60b778b8acefc2b67008a8947fa62a5/internal/status/gateway.go#L30 to make sure that the `ClusterIP` is updated in the status
the `if/else` will need to be refactored a bit

File: internal/infrastructure/kubernetes/proxy/resource_provider.go (hunk 1 above)
Comment (ShyunnY) [reply internal/infrastructure/kubernetes/proxy/resource_provider.go:130]: No, actually we can only set one clusterIPs, and clusterIPs[0] must be equal to clusterIP, and clusterIPs stipulates that each IP family can only set one IP.

**For example**: 
When we create the following Service resource and set multiple clusterIPs
```yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy-custom
  namespace: envoy-gateway-system
spec:
  clusterIP: 10.102.168.100
  clusterIPs:
    - 10.102.168.100
    - 10.102.168.101
  ports:
  - name: envoy-http
    port: 10009
    protocol: TCP
    targetPort: 10000
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: eg-gw
    gateway.envoyproxy.io/owning-gateway-namespace: default
  type: ClusterIP
```

Actually api-server throws `The Service "envoy-custom" is invalid: spec.clusterIPs: Invalid value: []string{"10.102.168.100", "10.102.168.101"}: may specify no more than one IP for each IP family` error

So I think that when configuring `envoyService.type=ClusterIP`, if the user specifies addresses when configuring the gateway, we only need to get the first address.

I will add more detailed comments to the code explaining this

**Comment by ShyunnY** [comment]
> we'll also need to update the logic in
> 
> https://github.com/envoyproxy/gateway/blob/d44f4be1d60b778b8acefc2b67008a8947fa62a5/internal/status/gateway.go#L30
> 
> to make sure that the `ClusterIP` is updated in the status
> the `if/else` will need to be refactored a bit

Yes, I've made changes

**Review by shawnh2 — APPROVED** [review]
lgtm, thanks

one more thing, it's not recommended to merge code from your main branch, so next time please create a new branch, thanks

**Review by zirain — APPROVED** [review]

File: internal/infrastructure/kubernetes/proxy/resource_provider.go (hunk 1 above)
Comment (arkodg) [reply internal/infrastructure/kubernetes/proxy/resource_provider.go:130]: thanks for explaining this, TIL about why `ClusterIPs` exist :)
