### PR TITLE
fix: enforce connection limit value

### LINKED ISSUE #4457: Empty Connection Limit causes XDS rejection
*Description*:
If an empty connection limit is configured in CTP, envoy rejects xds. 

```
"details": "Proto constraint validation failed (ConnectionLimitValidationError.MaxConnections: value must be greater than or equal to 1): stat_prefix: \"tls-terminate-10443\"\nmax_connections {\n}\n"}
```

*Repro steps*:
Follow quickstart and apply the following CTP:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: connection-limit-ctp
  namespace: default
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  connection:
    connectionLimit: {}
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by guydc**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4457

### CODE REVIEW

File: api/v1alpha1/connection_types.go [hunk 1]
```diff
@@ -63,12 +63,12 @@ type BackendConnection struct {
...
 
+// +kubebuilder:validation:XValidation:rule="(has(self.value))",message="value must be specified"
 type ConnectionLimit struct {
 	// Value of the maximum concurrent connections limit.
 	// When the limit is reached, incoming connections will be closed after the CloseDelay duration.
-	// Default: unlimited.
 	//
-	// +kubebuilder:validation:Minimum=0
+	// +kubebuilder:validation:Minimum=1
 	Value int64 `json:"value,omitempty"`
```
Comment (arkodg) [inline api/v1alpha1/connection_types.go:72]: can you also rm `omitempty`

File: api/v1alpha1/connection_types.go [hunk 2]
```diff
@@ -63,13 +63,13 @@ type BackendConnection struct {
 	SocketBufferLimit *resource.Quantity `json:"socketBufferLimit,omitempty"`
 }
 
+// +kubebuilder:validation:XValidation:rule="(has(self.value))",message="value must be specified"
```
Comment (arkodg) [inline api/v1alpha1/connection_types.go:66]: nit: not needed since `Value` is now mandatory

**Review by arkodg — APPROVED** [review]

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]
