### PR TITLE
fix: return early from buildwasms

### LINKED ISSUE #6159: WASM cache initialization failure causes all routes with EEP to fail
*Description*:

see here https://github.com/envoyproxy/gateway/issues/6124#issuecomment-2901233079 :

> The "Translator" calls buildWasms twice, once in translateEnvoyExtensionPolicyForRoute and once in translateEnvoyExtensionPolicyForGateway both treat a nil as an error

Seems like buildWasms will default all routes with an EEP, regardless of if the EEP even has wasms: 

It's always called when processing EEPs: 
https://github.com/envoyproxy/gateway/blob/c09c42ca34a2eba9d7699e800c218c293f69d5fc/internal/gatewayapi/envoyextensionpolicy.go#L302

It returns an error before checking if wasm cache is really needed:
https://github.com/envoyproxy/gateway/blob/c09c42ca34a2eba9d7699e800c218c293f69d5fc/internal/gatewayapi/envoyextensionpolicy.go#L618

In other words, if wasm cache fails to start - all routes with EEPs are zeroed-out. 

cc @zhaohuabing

*Repro steps*:

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by guydc**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6159 

Release Notes: Yes

### CODE REVIEW

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

File: internal/gatewayapi/envoyextensionpolicy.go [hunk 1]
```diff
@@ -614,12 +614,16 @@ func (t *Translator) buildWasms(
 	policy *egv1a1.EnvoyExtensionPolicy,
 	resources *resource.Resources,
 ) ([]ir.Wasm, error) {
+	var wasmIRList []ir.Wasm
+
+	if len(policy.Spec.Wasm) == 0 {
+		return wasmIRList, nil
```
Comment (arkodg) [inline internal/gatewayapi/envoyextensionpolicy.go:620]: does the caller expect `nil` or empty list ?

Comment (guydc) [reply internal/gatewayapi/envoyextensionpolicy.go:620]: nil slice wasmIRList was previosuly returned if `range policy.Spec.Wasm` was empty. So, should be safe.

**Review by arkodg — APPROVED** [review]
