### PR TITLE
fix: prevent xdsIR updates from overwriting RateLimit configs from other xdsIR

### LINKED ISSUE #3678: Ratelimit does not work across multiple GatewayClasses
*Description*:
EG currently uses Listener as domain for Ratelimit service config. It should instead use Gateway class not to override RL config for a case when when multiple Envoy deployments with diff gateway classes use same RL instance. 

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by sanposhiho**
**What type of PR is this?**

**What this PR does / why we need it**:

This PR tries to prevent xdsIR updates from overwriting RateLimit configs from other xdsIR.

When there are multiple gateway classes, the gateway API runner updates `r.XdsIR.Store` several times with different keys.
https://github.com/envoyproxy/gateway/blob/d784c3237765aa258c3526b32765dd9c3abf6415/internal/gatewayapi/runner/runner.go#L81

But, the ratelimit config runner create a ratelimit config from zero every time it gets updates of XdsIR.
https://github.com/envoyproxy/gateway/blob/d784c3237765aa258c3526b32765dd9c3abf6415/internal/globalratelimit/runner/runner.go#L114-L136

As a result, an update to a XdsIR could overwrite rate limit configs generated from other XdsIRs in the ratelimit config runner.

**Which issue(s) this PR fixes**:

Fixes #3678

### CODE REVIEW

File: internal/globalratelimit/runner/runner.go [hunk 1]
```diff
@@ -120,6 +124,7 @@ func (r *Runner) subscribeAndTranslate(ctx context.Context) {
 					r.Logger.Error(err, "failed to update the config snapshot")
```
Comment (arkodg) [inline internal/globalratelimit/runner/runner.go:124]: is `r.addNewSnapshot(ctx, nil)` still valid ? looks like it will need to be replaced by `r.updateSnapshot(ctx, xdsResourcesToUpdate)` ?

**Comment by arkodg** [comment]
thanks for picking this one up @sanposhiho !
the approach looks good, added a comment
can you also add a test in runner_test.go where you instrument some creates and deletes for multiple keys similar to https://github.com/envoyproxy/gateway/blob/181979697fc2f1254d37bab98d1820b72582fb9b/internal/gatewayapi/runner/runner_test.go#L28

File: internal/globalratelimit/runner/runner.go (hunk 1 above)
Comment (sanposhiho) [reply internal/globalratelimit/runner/runner.go]: 🤦‍♂️

**Comment by sanposhiho** [comment]
@arkodg Addressed your points.

**Review by zirain — APPROVED** [review]

File: internal/globalratelimit/runner/runner.go [hunk 2]
```diff
@@ -109,17 +110,27 @@ func (r *Runner) serveXdsConfigServer(ctx context.Context) {
...
+	for _, xdsR := range rateLimitConfigsCache {
+		xdsResourcesToUpdate[resourcev3.RateLimitConfigType] = append(xdsResourcesToUpdate[resourcev3.RateLimitConfigType], xdsR...)
+	}
+
+	return xdsResourcesToUpdate
+}
+
 func (r *Runner) subscribeAndTranslate(ctx context.Context) {
+	// rateLimitConfigsCache is a cache of the rate limit config, which is keyed by the xdsIR key.
+	rateLimitConfigsCache := map[string][]cachetype.Resource{}
```
Comment (arkodg) [inline internal/globalratelimit/runner/runner.go:124]: is there a way to not maintain this cache here and instead create an API like `rCache := r.getSnapshot(ctx)` instead ? this will allow us to reduce one copy in memory

Comment (sanposhiho) [reply internal/globalratelimit/runner/runner.go:124]: Let me try; depending on the complexity that would give though, that looks a better idea.

Comment (sanposhiho) [reply internal/globalratelimit/runner/runner.go:124]: The change would be like this https://github.com/sanposhiho/gateway/commit/a9f0a190ed7ecc939225598c0e5ce96f23307ce9

So, either way, we have to have a cache to track which ir.Key generates which rate limit configurations. (A cache size would be smaller than the current cache of entire configs, that's one good point though.)
The cache is required because otherwise we wouldn't know which part of snapshot we have to update. (A `message.Update` comes from `watchable.Snapshot` doesn't have a previous state of ir.)

So, I'm not very motivated to proceed that way; For me, it looks like only a little gain (less memory usage) would come with a certain downside (complexity).

Comment (arkodg) [reply internal/globalratelimit/runner/runner.go:124]: hey @sanposhiho thanks for writing up the quick diff, what I was suggesting was a little different, instead of holding the entire cache on the stack using `rateLimitConfigsCache` which incurs a constant memory hit, can we retrieve the cache snapshot using an API like 
https://github.com/envoyproxy/go-control-plane/blob/1da4500d00e270d803caefbe0c20e4d3d162e586/pkg/cache/v3/snapshot.go#L124
every time we get a new new message ?

Comment (sanposhiho) [reply internal/globalratelimit/runner/runner.go:124]: Sorry, what's the difference from my diff? It fetches the previous snapshot with GetSnapshot -> GetResources, and try to rebuild a new snapshot from there already.

Comment (arkodg) [reply internal/globalratelimit/runner/runner.go:124]: I missed that 🙈 
lets go ahead with diff to keep the code complexity low and we can revisit these if/when we hit a memory bottleneck

**Review by arkodg — APPROVED** [review]
LGTM thanks !
