### PR TITLE
fix: avoid metric increments on no-op delete reconcile paths

### LINKED ISSUE #8438: Delete metrics increment on no-op reconcile when DaemonSet/HPA/PDB are not configured
*Description*:

The `resource_delete_total` and `resource_delete_duration_seconds` metrics are being incremented every reconcile cycle for resources that don't exist and were never created.

When using a Deployment-based EnvoyProxy, it seems like the controller calls `deleteDaemonSet()`, `deleteHPA()`, and `deletePDB()` on every reconcile because the `createOrUpdate*` seems to treat `nil` renders as a signal to delete. 

After running for a few days, I'm seeing ~25k deletes for DaemonSet, HPA, and PDB - while the Deployment (which actually exists) shows zero deletes as expected.

This makes the metrics noisy and  hard to track actual delete operations. It is also misleading for the dashboards and does not seem to match with the description of the metric:

Image

Image

Image

Basically, if a resource is not actually deleted, then I wouldn't expect it to be counted as such.

*Repro steps*:

1. Deploy Envoy Gateway with default config (Deployment mode, no HPA/PDB)
2. Create a Gateway and let it reconcile for a while
3. Query metrics:
```promql
resource_delete_total
resource_delete_duration_seconds_sum
```
4. Observe DaemonSet/HPA/PDB counters climbing while Deployment stays at 0

*Environment*:

- Envoy Gateway v1.7.0
- Kubernetes 1.34.2
- Default EnvoyProxy config (Deployment with 2 replicas, no autoscaling or PDB)

*Logs*:

N/A - no errors, just metric behavior

---

Possible fix would be to check whether `DeleteAllOf` actually deleted anything before recording metrics, or skip the delete call entirely if a Get shows the resource doesn't exist.

---

### PR DESCRIPTION
**Pull request by felipesabadini**
## What type of PR is this?

`fix: avoid metric increments on no-op delete reconcile paths`

## What this PR does / why we need it

This PR fixes metric inflation during no-op reconciles for optional resources.

Previously, `deleteDeployment`, `deleteDaemonSet`, `deleteHPA`, and `deletePDB` always called `DeleteAllOf` and recorded `resource_delete_*` success metrics, even when no matching resources existed. In default Deployment mode (without DaemonSet/HPA/PDB), this caused delete metrics to grow continuously despite no real deletions.

Additionally, `createOrUpdateHPA` and `createOrUpdatePodDisruptionBudget` registered apply metric defers before nil checks, causing `resource_apply_total` to be incremented on the nil->delete path.

### Changes

- Add pre-delete existence checks (`List` with the same namespace/label selector) in:
  - `deleteDeployment`
  - `deleteDaemonSet`
  - `deleteHPA`
  - `deletePDB`
- If no matching resources exist, return early and skip delete metric recording.
- Move apply-metric `defer` blocks in:
  - `createOrUpdateHPA`
  - `createOrUpdatePodDisruptionBudget`
  to run only in actual apply paths (after nil checks), matching Deployment/DaemonSet behavior.

## Which issue(s) this PR fixes

Fixes #8438

## Release Notes

No

### CODE REVIEW

**Comment by felipesabadini** [comment]
Validated in a local Kind test cluster (default Deployment mode, no HPA/PDB/DaemonSet configured).

- Deployed Envoy Gateway with this fix.
- Checked `/metrics` after startup and again after ~60s of reconcile loops.
- Re-checked across multiple reconcile cycles.

Observed:
- `resource_delete_total`: no increments for `DaemonSet`, `HPA`, or `PDB` (previously these grew continuously on no-op reconciles).
- `resource_apply_total`: no increments for `HPA`/`PDB` on nil -> delete paths (previously incremented incorrectly).
- Counters remained stable over time.

**Review by zirain — APPROVED** [review]

**Comment by kkk777-7** [comment]
Hi @felipesabadini, thanks for working this!
Overall LGTM, could you fix lint?

File: internal/infrastructure/kubernetes/infra_resource_test.go [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+
+	mu.Lock()
+	defer mu.Unlock()
+
+	assert.Greater(t, counts["*v1.DaemonSet"], 0,
+		"DeleteAllOf should be called for DaemonSet when it exists")
+	assert.Greater(t, counts["*v2.HorizontalPodAutoscaler"], 0,
+		"DeleteAllOf should be called for HPA when it exists")
+	assert.Greater(t, counts["*v1.PodDisruptionBudget"], 0,
+		"DeleteAllOf should be called for PDB when it exists")
```
Comment (jukie) [inline internal/infrastructure/kubernetes/infra_resource_test.go]:
```suggestion
	assert.Positive(t, counts["*v1.DaemonSet"],
		"DeleteAllOf should be called for DaemonSet when it exists")
	assert.Positive(t, counts["*v2.HorizontalPodAutoscaler"],
		"DeleteAllOf should be called for HPA when it exists")
	assert.Positive(t, counts["*v1.PodDisruptionBudget"],
		"DeleteAllOf should be called for PDB when it exists")
```

File: internal/infrastructure/kubernetes/infra_resource_test.go [hunk 2]
```diff
@@ -0,0 +1,287 @@
...
+	require.NoError(t, cli.Create(ctx, deploy))
+
+	// Reconcile in DaemonSet mode → should DELETE the stale Deployment.
+	err := kube.CreateOrUpdateProxyInfra(ctx, daemonSetModeInfra())
+	require.NoError(t, err)
+
+	mu.Lock()
+	defer mu.Unlock()
+
+	assert.Greater(t, counts["*v1.Deployment"], 0,
```
Comment (jukie) [inline internal/infrastructure/kubernetes/infra_resource_test.go]:
```suggestion
	assert.Positive(t, counts["*v1.Deployment"],
```

**Comment by arkodg** [comment]
hey @felipesabadini  can you help with these follow ups

  - `createOrUpdateHPA()` now returns directly on `r.HorizontalPodAutoscaler()`
  errors before the defer is installed, so HPA render/patch failures no longer
  increment `resource_apply_total{result="failure"}`.
  - `deleteDeployment()`, `deleteDaemonSet()`, `deleteHPA()`, and `deletePDB()`
  now return on the pre-delete `List()` call before the delete-metrics defer is
  installed, so list/RBAC/API failures no longer increment
  `resource_delete_total{result="failure"}`.

#8438 looks fixed for the no-op delete case, but failure-path observability
  regressed
