### PR TITLE
fix: disable `-shadow` host suffix append

### LINKED ISSUE #7227: Remove shadow host suffix from the mirrored requests
The current [HTTPRoute Request Mirroring](https://gateway.envoyproxy.io/v1.5/tasks/traffic/http-request-mirroring/) automatically appends a “-shadow” to the mirror requests Host header. According to the [Envoy doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-requestmirrorpolicy), this is used for logging.   

However, this can be surprising to users, as the Host header is modified without explicit notice.  It may also cause issues for application that depends on the original Host header.

I suggest removing the suffix by default. Since the mirror policy already uses a different cluster, this should be sufficient to distinguish the mirroring traffic from regular requests in the access log.

### PR DESCRIPTION
**Pull request by shreealt**
**What type of PR is this?**

bugfix

**What this PR does / why we need it**:
The current [HTTPRoute Request Mirroring](https://gateway.envoyproxy.io/v1.5/tasks/traffic/http-request-mirroring/) automatically appends a “-shadow” to the mirror requests Host header. According to the [Envoy doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-requestmirrorpolicy), this is used for logging.

However, this can be surprising to users, as the Host header is modified without explicit notice. It may also cause issues for application that depends on the original Host header.
**Which issue(s) this PR fixes**:

Fixes #7227

Release Notes: Yes/No

### CODE REVIEW

**Comment by shreealt** [comment]
I am kinda confused on how to write test cases for this one. Specially the part on how to confirm that the host header in mirrored HTTP message does not contain the shadow suffix.

I am reading existing test cases, however I would appreciate any help on this.

**Comment by zhaohuabing** [comment]
@shreealt thanks for picking this up!

Iet's hold off on this PR for now until a decision is made on how to address https://github.com/envoyproxy/gateway/issues/7227.

**Comment by zhaohuabing** [comment]
@shreealt we discussed this in today's meeting. The decision is to make a breaking change to remove the `-shadow` suffix at this PR.

Feel free to proceed.

File: internal/xds/translator/route.go [hunk 1]
```diff
@@ -541,8 +541,9 @@ func buildXdsRequestMirrorPolicies(mirrorPolicies []*ir.MirrorPolicy) []*routev3
 	for _, policy := range mirrorPolicies {
 		if mp := mirrorPercentByPolicy(policy); mp != nil && policy.Destination != nil {
 			xdsMirrorPolicies = append(xdsMirrorPolicies, &routev3.RouteAction_RequestMirrorPolicy{
-				Cluster:         policy.Destination.Name,
-				RuntimeFraction: mp,
+				Cluster:                       policy.Destination.Name,
+				RuntimeFraction:               mp,
+				DisableShadowHostSuffixAppend: true,
```
Comment (zhaohuabing) [inline internal/xds/translator/route.go:547]: Nit: can we add a line of comment to explain why setting this option?

**Comment by zhaohuabing** [comment]
> I am kinda confused on how to write test cases for this one. Specially the part on how to confirm that the host header in mirrored HTTP message does not contain the shadow suffix.

> I am reading existing test cases, however I would appreciate any help on this.

RequestMirror is in a Gateway API feature, so we rely on [the gateway api conformance test](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-request-mirror.go) to verify it in the e2e tests.

For this PR, it's fine to verify it in the xds translator tests.

**Review by jukie — APPROVED** [review]
