### PR TITLE
fix: multiple reference grants in same namespace

### LINKED ISSUE #2149: Multiple Reference Grant for specific service in the same namespace didn't work as expected.
*Description*:
If we separate `HTTPRoute` into a central namespace and place all related backends into their respective namespaces, this will necessitate the use of a `ReferenceGrant`. In our scenario, we include a `ReferenceGrant` as part of each application deployment, that refers to its Kubernetes Service. 
Everything seems working fine, but as soon as we add another application deployment in the existing namespace (that is contains an existing application with its `ReferenceGrant`), HTTPRoute starts showing an inconsistent status that shows `Backend ref to service <namespace>/<service_name> not permitted by any ReferenceGrant`.

*Initial Finding*:

We think this is because of inconsistent steps between these line of code:
* For finding the reference of `ReferenceGrant` for the associated service.
https://github.com/envoyproxy/gateway/blob/defed574484e2708933d5f911b8bfc35e7ac8ee2/internal/provider/kubernetes/controller.go#L496-L504

* For validating when referring to `ReferenceGrant` for the HTTPRoute.
https://github.com/envoyproxy/gateway/blob/defed574484e2708933d5f911b8bfc35e7ac8ee2/internal/gatewayapi/validate.go#L678-L682

The filtering mechanism only checks after the From spec, meaning, the first match with its `From` will be used. While on validation, it will check thoroughly on the `To` spec.

*Repro steps*:
Assuming you have deployed 3 services of Echoserver in the `testing` namespace.

Apply these `ReferenceGrant` manifests:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: echoserver-1-rg
  namespace: testing
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: echoserver-1
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: echoserver-2-rg
  namespace: testing
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: echoserver-2
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: echoserver-3-rg
  namespace: testing
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: echoserver-3
```

Apply these for HTTPRoute manifests,

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: sample-01
  namespace: envoy-gateway-system
spec:
  hostnames:
  - playground.internal
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver-1
      namespace: testing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /echo1a
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver-2
      namespace: testing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /echo2
  - backendRefs:
    - group: ""
      kind: Service
      name: echoserver-3
      namespace: testing
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /echo3
```

*Environment*:
v0.5.0 Envoy Gateway, but a similar code still exists in the recent version.

### PR DESCRIPTION
**Pull request by ardikabs**
**What type of PR is this?**

The current behavior of Envoy Gateway when working with multiple `ReferenceGrants` in the same namespace is problematic. When searching for a ReferenceGrant for corresponding resources, such as the `HTTPRoute`, it only checks the `ReferenceGrant.spec.from` semantics. However, during translation, the translator validates both the `ReferenceGrant.spec.from` and `ReferenceGrant.spec.to` semantics thoroughly.
As a result, the `findReferenceGrant` method only captures the first `ReferenceGrant` with the correct `From`, meaning other `ReferenceGrants` are not honored. This leads to the corresponding resource that uses two different resource references encountering an error message such as `Backend ref to service <namespace>/<service_name> not permitted by any ReferenceGrant` during translation.

Code for `findReferenceGrant`:
https://github.com/envoyproxy/gateway/blob/349760029d5ea70c003e291e8d1c9d0ddedc3e96/internal/provider/kubernetes/controller.go#L771-L782

Code for translation:
https://github.com/envoyproxy/gateway/blob/349760029d5ea70c003e291e8d1c9d0ddedc3e96/internal/gatewayapi/validate.go#L832-L857

**Proposed Solution**

This PR modifies the `findReferenceGrant` method to also check the To semantics.

Fixes #2149

### CODE REVIEW

**Comment by ardikabs** [comment]
since there is no existing unit test for the corresponding line, could you please advise me on whether I should add a unit test elsewhere?

File: internal/provider/kubernetes/controller.go [hunk 1]
```diff
@@ -769,13 +769,37 @@ func (r *gatewayAPIReconciler) findReferenceGrant(ctx context.Context, from, to
...
-				}
+		if refGrant.Namespace != to.namespace {
+			continue
+		}
+
+		var fromAllowed bool
+		for _, refGrantFrom := range refGrant.Spec.From {
+			if string(refGrantFrom.Kind) == from.kind &&
+				string(refGrantFrom.Namespace) == from.namespace {
+				fromAllowed = true
```
Comment (shawnh2) [inline internal/provider/kubernetes/controller.go:780]: should `break` here ?

File: internal/provider/kubernetes/controller.go [hunk 2]
```diff
@@ -769,13 +769,37 @@ func (r *gatewayAPIReconciler) findReferenceGrant(ctx context.Context, from, to
...
+
+		if !fromAllowed {
+			continue
+		}
+
+		var toAllowed bool
+		for _, refGrantTo := range refGrant.Spec.To {
+			if string(refGrantTo.Kind) == to.kind &&
+				(refGrantTo.Name == nil ||
+					*refGrantTo.Name == "" ||
```
Comment (shawnh2) [inline internal/provider/kubernetes/controller.go:792]: let's keep this three conditions in one line

File: internal/provider/kubernetes/controller.go [hunk 3]
```diff
@@ -769,13 +769,37 @@ func (r *gatewayAPIReconciler) findReferenceGrant(ctx context.Context, from, to
...
+					string(*refGrantTo.Name) == to.name) {
+				toAllowed = true
```
Comment (shawnh2) [inline internal/provider/kubernetes/controller.go:794]: ditto, `break` here ?

**Comment by shawnh2** [comment]
> since there is no existing unit test for the corresponding line, could anyone advise me on whether I should add a unit test elsewhere?

An e2e test would be nice!

File: internal/provider/kubernetes/controller.go (hunk 1 above)
Comment (ardikabs) [reply internal/provider/kubernetes/controller.go:781]: added, thanks @shawnh2

File: internal/provider/kubernetes/controller.go (hunk 2 above)
Comment (ardikabs) [reply internal/provider/kubernetes/controller.go]: changed!

**Comment by ardikabs** [comment]
> An e2e test would be nice!

@shawnh2 do you mean the integration, like [here](https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/kubernetes_test.go)?

**Comment by ardikabs** [comment]
hi @shawnh2, 
I've added an e2e test, but it seems that some of the other tests, like `TestE2E/Wasm_HTTP_Code_Source`, are a bit flaky.

**Comment by shawnh2** [comment]
they sure are flaky, and we are trying to repair them. 😿

**Review by shawnh2 — APPROVED** [review]
LGTM! Thanks for fixing this

**Review by arkodg — APPROVED** [review]
LGTM !
thanks for adding an e2e
