### PR TITLE
fix(kubernetes): apply namespace selector filtering to List operations

### LINKED ISSUE #8305: xPolicy resources are processed from all namespaces when NamespaceSelector watch is configured
*Description*:
When Envoy Gateway is configured with `NamespaceSelector` watch type in the Kubernetes provider to only watch specific namespaces, xPolicy resources from all namespaces are still being processed.

**Note:** Other resources like `HTTPRoute`, `Gateway`, and `ReferenceGrant` are correctly filtered by the namespace selector. This issue affects all xPolicy resources (`ClientTrafficPolicy`, `BackendTrafficPolicy`, `SecurityPolicy`, `EnvoyExtensionPolicy`, etc.). The reproduction steps below use `ClientTrafficPolicy` as an example, but the same behavior applies to all policy types.

*Repro steps*:
1. Install EG with namespace selector:
```shell
helm upgrade --install eg oci://docker.io/envoyproxy/gateway-helm \
--version v1.7.0 \
-n envoy-gateway-system \
--create-namespace \
--wait --wait-for-jobs \
--values - <<EOF
config:
  envoyGateway:
    provider:
      kubernetes:
        watch:
          type: NamespaceSelector
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: consumer
    extensionApis:
      enableBackend: true
EOF
```

2. Apply the following manifests:
```shell
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: consumer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: consumer
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend
  namespace: consumer
spec:
  endpoints:
    - fqdn:
        hostname: httpbin.org
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: consumer
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: v1
kind: Namespace
metadata:
  name: consumer2
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: client-validation-policy
  namespace: consumer2
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  tls:
    clientValidation:
      caCertificateRefs:
        - kind: Secret
          group: ""
          name: non-existing-secret
EOF
```

3. Check envoy-gateway logs:
```shell
kubectl -n envoy-gateway-system logs -l app.kubernetes.io/instance=eg | grep ERROR
```

The following error shows that `ClientTrafficPolicy` in `consumer2` namespace is being processed, even though only `consumer` namespace should be watched:

```
2026-02-18T15:06:48.202Z        ERROR   provider        kubernetes/controller.go:1386   failed to process CACertificateRef for ClientTrafficPolicy       {"runner": "provider", "policy": {"kind":"ClientTrafficPolicy","apiVersion":"gateway.envoyproxy.io/v1alpha1","metadata":{"name":"client-validation-policy","namespace":"consumer2","uid":"2e5b39ed-ab2c-4db2-bf2e-54c0d64d48db","resourceVersion":"20140","generation":1,"creationTimestamp":"2026-02-18T15:05:56Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"gateway.envoyproxy.io/v1alpha1\",\"kind\":\"ClientTrafficPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"client-validation-policy\",\"namespace\":\"consumer2\"},\"spec\":{\"targetRefs\":[{\"group\":\"gateway.networking.k8s.io\",\"kind\":\"Gateway\",\"name\":\"eg\"}],\"tls\":{\"clientValidation\":{\"caCertificateRefs\":[{\"group\":\"\",\"kind\":\"Secret\",\"name\":\"non-existing-secret\"}]}}}}\n"}},"spec":{"targetRefs":[{"group":"gateway.networking.k8s.io","kind":"Gateway","name":"eg"}],"tls":{"clientValidation":{"caCertificateRefs":[{"group":"","kind":"Secret","name":"non-existing-secret"}]}}},"status":{"ancestors":null}}, "caCertificateRef": "non-existing-secret", "kind": "Secret", "error": "unable to find the Secret consumer2/non-existing-secret: Secret \"non-existing-secret\" not found"}
```

*Environment*:
EG 1.7.0

### PR DESCRIPTION
**Pull request by shahar-h**
**What this PR does / why we need it**:
When using the Kubernetes provider with `NamespaceSelector` watch mode, namespace filtering after `client.List` operations was implemented for some resources (Gateway, xRoute, ReferenceGrant) but was missing for xPolicy resources (SecurityPolicy, BackendTrafficPolicy, ClientTrafficPolicy, etc.). This caused xPolicy resources from all namespaces to be processed during reconciliation, even when those namespaces didn't match the configured selector.

This PR centralizes the namespace filtering logic by introducing a `namespaceSelectorClient` wrapper that automatically filters List results. This approach:

- Eliminates scattered namespace filtering checks throughout the codebase
- Ensures consistent filtering for all resource types including xPolicies
- Excludes cluster-scoped resources (e.g., GatewayClass) from filtering since they have no namespace

Note: Watch predicates in `watchResources` still have their own namespace filtering checks for filtering incoming events.

**Which issue(s) this PR fixes**:
Fixes #8305

Release Notes: Yes

### CODE REVIEW

File: internal/provider/kubernetes/predicates.go [hunk 1]
```diff
@@ -68,16 +68,18 @@ type NamespaceGetter interface {
...
+	// Cluster-scoped resources should not be filtered
 	if nsString = obj.GetNamespace(); len(nsString) == 0 {
-		return false, nil
+		return true, nil
 	}
 
 	ns := &corev1.Namespace{}
-	if err := r.client.Get(
+	if err := c.Get(
 		context.Background(),
```
Comment (zhaohuabing) [inline internal/provider/kubernetes/predicates.go]: Nit: could we pass the reconcile context down and use it instead of the BackGround context?

File: internal/provider/kubernetes/predicates.go
Comment (zhaohuabing) [inline internal/provider/kubernetes/predicates.go:89]: We should probably return `false, nil` for `IsNotFound` instead of return the error here.

Since `IsNotFound` is not a transient error, it doesn't trigger the explicit transient retry path, and it is just logged and the list is skipped for this reconcile.

Comment (zhaohuabing) [inline internal/provider/kubernetes/predicates.go:62]: Nit:  would it be safer to return true for any errors that are **not** `IsNotFound`, so we don't drop the event?
This comment is non-blocking, as this is not related to this PR directly.

File: internal/provider/kubernetes/namespace_selector_client.go [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+
+	// Check if this is a cluster-scoped resource by examining the first item.
+	// All items in a list are the same type, so if the first has no namespace,
+	// they're all cluster-scoped and should not be filtered.
+	if firstObj, ok := items[0].(metav1.Object); ok && firstObj.GetNamespace() == "" {
+		return nil
+	}
+
+	// Filter items based on namespace labels
+	var filtered []runtime.Object
```
Comment (zhaohuabing) [inline internal/provider/kubernetes/namespace_selector_client.go]: Nit: can we do in-place compaction of items instead of building another filtered array?

File: internal/provider/kubernetes/namespace_selector_client.go [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+				obj.GetNamespace(), obj.GetName(), err)
+		}
+
+		if matches {
+			filtered = append(filtered, item)
+		}
+	}
+
+	// Set the filtered items back to the list
+	if err := meta.SetList(list, filtered); err != nil {
```
Comment (zhaohuabing) [inline internal/provider/kubernetes/namespace_selector_client.go]: Nit: this can be skipped if the length of the resulting list is the same as the original one.

File: internal/provider/kubernetes/namespace_selector_client.go [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+	// All items in a list are the same type, so if the first has no namespace,
+	// they're all cluster-scoped and should not be filtered.
+	if firstObj, ok := items[0].(metav1.Object); ok && firstObj.GetNamespace() == "" {
+		return nil
+	}
+
+	// Filter items based on namespace labels
+	var filtered []runtime.Object
+	for _, item := range items {
+		obj, ok := item.(metav1.Object)
```
Comment (zhaohuabing) [inline internal/provider/kubernetes/namespace_selector_client.go:83]: Nit: Could we cache namespace match results in a map (keyed by namespace) and check that first, to avoid repeatedly calling `checkObjectNamespaceLabels` for objects in the same namespace?

**Comment by zhaohuabing** [comment]
Hi @shahar-h thanks for the fix! This looks good overall. I left a few minor nits for follow-up.

File: internal/provider/kubernetes/predicates.go (hunk 1 above)
Comment (shahar-h) [reply internal/provider/kubernetes/predicates.go]: Done

File: internal/provider/kubernetes/predicates.go
Comment (shahar-h) [reply internal/provider/kubernetes/predicates.go:89]: Done

Comment (shahar-h) [reply internal/provider/kubernetes/predicates.go:62]: You probably meant `false`. Anyway it is now covered in `checkObjectNamespaceLabels` - see https://github.com/envoyproxy/gateway/pull/8312#discussion_r2837411309.

File: internal/provider/kubernetes/namespace_selector_client.go (hunk 2 above)
Comment (shahar-h) [reply internal/provider/kubernetes/namespace_selector_client.go]: Done

File: internal/provider/kubernetes/namespace_selector_client.go (hunk 3 above)
Comment (shahar-h) [reply internal/provider/kubernetes/namespace_selector_client.go]: Done

File: internal/provider/kubernetes/namespace_selector_client.go (hunk 4 above)
Comment (shahar-h) [reply internal/provider/kubernetes/namespace_selector_client.go:83]: Done

**Review by kkk777-7 — APPROVED** [review]

**Comment by kkk777-7** [comment]
LGTM, thanks!

**Comment by zhaohuabing** [comment]
Hi @shahar-h  — once the conflict is resolved, we should be good to go.

**Comment by shahar-h** [comment]
> Hi @shahar-h — once the conflict is resolved, we should be good to go.

Done

**Comment by shahar-h** [comment]
Can this be merged if there are no further comments?
