### PR TITLE
e2e: fix flaky merge-gateways test

### LINKED ISSUE #3290: flaky: TestMergeGateways/BasicMergeGateways
https://github.com/envoyproxy/gateway/actions/runs/8865654957/job/24342242631

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3290

### CODE REVIEW

File: test/e2e/merge_gateways/merge_gateways_test.go [hunk 1]
```diff
@@ -52,9 +52,6 @@ func TestMergeGateways(t *testing.T) {
 		Debug:                *flags.ShowDebug,
 		CleanupBaseResources: *flags.CleanupBaseResources,
 		RunTest:              *flags.RunTest,
-		SkipTests: []string{
-			tests.MergeGatewaysTest.ShortName, // https://github.com/envoyproxy/gateway/issues/3290
-		},
```
Comment (zirain) [inline test/e2e/merge_gateways/merge_gateways_test.go:57]: can you just remove L56?

**Review by zirain — DISMISSED** [review]

File: test/e2e/merge_gateways/merge_gateways_test.go (hunk 1 above)
Comment (shawnh2) [reply test/e2e/merge_gateways/merge_gateways_test.go:57]: sure

**Review by guydc — APPROVED** [review]
