### PR TITLE
fix flaky wasm permission check

### LINKED ISSUE #5735: flaky test: TestPermissionCache
https://github.com/envoyproxy/gateway/actions/runs/14451616907/job/40525450482?pr=5734

```
--- FAIL: TestPermissionCache (0.14s)
    --- FAIL: TestPermissionCache/Cached_permission_should_be_removed_after_expiry (0.04s)
        premissioncache_test.go:175: 
            	Error Trace:	/home/runner/work/gateway/gateway/internal/wasm/premissioncache_test.go:175
            	Error:      	Should be true
            	Test:       	TestPermissionCache/Cached_permission_should_be_removed_after_expiry
            	Messages:   	expired entry should be added after recheck
```

### PR DESCRIPTION
**Pull request by zhaohuabing**
fix #5735

### CODE REVIEW

**Review by arkodg — APPROVED** [review]

**Comment by zhaohuabing** [comment]
Quick and dirt fix to quickly fix the build. 

May try @mathetake 's [suggestion](https://github.com/envoyproxy/gateway/issues/5735#issuecomment-2831679819) later in another PR.

**Comment by zirain** [comment]
The recent flaky is not caused by this, so prefer to go straight with the final solution.

**Comment by zhaohuabing** [comment]
> The recent flaky is not caused by this, so prefer to go straight with the final solution.

I thought it's the same。 It's a different reason?

**Comment by zhaohuabing** [comment]
@zirain This should fix #5735

```
--- FAIL: TestPermissionCache (0.14s)
    --- FAIL: TestPermissionCache/Cached_permission_should_be_removed_after_expiry (0.04s)
        premissioncache_test.go:175: 
            	Error Trace:	/home/runner/work/gateway/gateway/internal/wasm/premissioncache_test.go:175
            	Error:      	Should be true
            	Test:       	TestPermissionCache/Cached_permission_should_be_removed_after_expiry
            	Messages:   	expired entry should be added after recheck
```

```go
t.Run("Cached permission should be removed after expiry", func(t *testing.T) {
		lock.Lock()
		failPermissionCheck = false
		lock.Unlock()

		ctx := context.Background()
		defer ctx.Done()
		cache, entry := setupTestPermissionCache(
			permissionCacheOptions{
				checkInterval: 1 * time.Nanosecond,
				cacheExpiry:   10 * time.Nanosecond,
			},
			image,
			latestImage,
			secret)
		cache.Start(ctx)

		lastAccessTime := entry.lastAccess
		lastCheckTime := entry.lastCheck

		cache.triggerChan <- struct{}{}.     # This is the key change
		time.Sleep(1 * time.Millisecond)
		key := entry.key()
```

File: internal/wasm/premissioncache.go [hunk 1]
```diff
@@ -71,6 +71,9 @@ type permissionCache struct {
 
 	cache  map[string]*permissionCacheEntry
 	logger logging.Logger
+
+	// For tests
+	triggerChan chan struct{}
```
Comment (zirain) [inline internal/wasm/premissioncache.go:76]: IMO, this's overkill for test only or it's a wrong design.

Comment (zhaohuabing) [reply internal/wasm/premissioncache.go:76]: Yeah, we can make the tests better following @mathetake 's https://github.com/envoyproxy/gateway/issues/5735#issuecomment-2831679819 later in another PR. This is a quick/dirt fix to unblock the github flows for v1.4.

**Review by zirain — APPROVED** [review]
