### PR TITLE
fix: validation behavior for multiple certificate refs

### LINKED ISSUE #5730: certificate in gateway
*Description*:
In my environment, the gateway certificate is not managed by cert-manager but manually maintained. I've observed that when the certificate bound to the gateway expires, it causes the entire listener to fail. Isn't this behavior a bit too strict?
env: v1.3.0

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by kkk777-7**
**What this PR does / why we need it**:
Fix validation behavior for multiple certificate refs.

currently, when both an invalid certificate ref and a valid certificate ref are present in listener TLS, we set `ResolvedRefs=False` and `Programmed=False`.
As a result, listener translation fails and no xDS listeners are generated.

we update the behavior by introducing new `PartiallyInvalidCertificateRef` condition reason.
- If both valid and invalid certificate refs exist:
  - `ResolvedRefs=False` with reason `PartiallyInvalidCertificateRef`
  - `Programmed=True`

**Which issue(s) this PR fixes**:

Fixes #5730

Release Notes: Yes

### CODE REVIEW

File: internal/gatewayapi/status/error.go [hunk 1]
```diff
@@ -35,6 +35,72 @@ const (
...
+const (
+	ListenerReasonPartiallyInvalidCertificateRef gwapiv1.ListenerConditionReason = "PartiallyInvalidCertificateRef"
+)
+
+// ListenerError is an error interface that represents errors that need to be reflected
+// in the status of a Kubernetes resource. It extends the standard error interface
+// with a Reason method that returns the specific condition reason.
+//
+// TODO kkk777-7: consider using generics to make Error interface resource-agnostic to support all resource types.
+type ListenerError interface {
```
Comment (kkk777-7) [inline internal/gatewayapi/status/error.go:48]: I think we should use generics in error interface to avoid duplication.

But this needs wide changes. so I want to handle this in follow up PR.

File: internal/gatewayapi/validate.go [hunk 2]
```diff
@@ -289,6 +289,19 @@ func (t *Translator) validateListenerConditions(listener *ListenerContext) (isRe
 		return true
 	}
 
+	// Edge case: only one condition which is ResolvedRefs=False, Reason=PartiallyInvalidCertificateRef
+	// In this case, we can still consider the listener as ready because we only program the listener using only the valid certificates.
+	if len(lConditions) == 1 && lConditions[0].Type == string(gwapiv1.ListenerConditionResolvedRefs) &&
+		lConditions[0].Reason == string(status.ListenerReasonPartiallyInvalidCertificateRef) {
+		status.SetGatewayListenerStatusCondition(listener.gateway.Gateway, listener.listenerStatusIdx,
```
Comment (arkodg) [inline internal/gatewayapi/validate.go]: nit: order of programmed and accepted should probably be flipped

File: internal/gatewayapi/validate.go [hunk 3]
```diff
@@ -430,53 +434,89 @@ func (t *Translator) validateTerminateModeAndGetTLSSecrets(
...
+		for i, e := range errs {
+			errList[i] = e
+		}
+
+		status.SetGatewayListenerStatusCondition(listener.gateway.Gateway,
+			listener.listenerStatusIdx,
+			gwapiv1.ListenerConditionResolvedRefs,
+			metav1.ConditionFalse,
+			reason,
+			fmt.Sprintf("No valid secrets exist: %v", errors.Join(errList...)),
```
Comment (arkodg) [inline internal/gatewayapi/validate.go:484]: do we need a new & explicit errList here or can we reuse `errs`

Comment (kkk777-7) [reply internal/gatewayapi/validate.go:484]: maybe we need new `errList`, I found the compile error message
```
cannot use errs (variable of type []"github.com/envoyproxy/gateway/internal/gatewayapi/status".ListenerError) as []error value in argument to errors.Join
```

File: internal/gatewayapi/validate.go (hunk 2 above)
Comment (kkk777-7) [reply internal/gatewayapi/validate.go]: thanks! I've fixed.

**Review by arkodg — APPROVED** [review]
LGTM thanks

**Comment by kkk777-7** [comment]
gentle ping @zhaohuabing
