### PR TITLE
fix: EnvoyProxy image with digest is rejected

### LINKED ISSUE #6713: [Regression-1.5.0-rc.2] EnvoyProxy image with digest is rejected
*Description*:
A custom EnvoyProxy image with digest is rejected with:
```log
The EnvoyProxy "custom-proxy-config" is invalid: spec.provider.kubernetes.envoyDeployment.container.image: Invalid value: "string": Image must include a tag and allowed characters only (e.g., 'repo:tag').
```

*Repro steps*:
1. install EG 1.5.0-rc.2 chart:
```shell
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v1.5.0-rc.2 -n envoy-gateway-system --create-namespace --wait
```
2. Apply `EnvoyProxy` resource with a custom image that contains a digest:
```shell
cat <<EOF | kubectl apply -f -
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image: envoyproxy/envoy:distroless-v1.35.0@sha256:da99c47f08546492d19973920dc76334c592f59ad5b732a514320d959db9fa40
EOF
```

*Environment*:
EG 1.5.0-rc.2

### PR DESCRIPTION
**Pull request by zirain**
fixes: https://github.com/envoyproxy/gateway/issues/6713

xref: https://regex101.com/r/afzJkz/1

### CODE REVIEW

File: test/cel-validation/envoyproxy_test.go [hunk 1]
```diff
@@ -1615,6 +1615,24 @@ func TestEnvoyProxyProvider(t *testing.T) {
 			},
 			wantErrors: []string{},
 		},
+		{
+			desc: "valid: image set with digest, imageRepository not set",
```
Comment (arkodg) [inline test/cel-validation/envoyproxy_test.go:1619]: can we also add a test for `envoyproxy/envoy@sha256:da99c47f08546492d19973920dc76334c592f59ad5b732a514320d959db9fa40`
which is the more common way for pulling by digest

Comment (zirain) [reply test/cel-validation/envoyproxy_test.go:1619]: updated

**Review by arkodg — APPROVED** [review]

**Review by guydc — APPROVED** [review]
LGTM, thanks!
