### PR TITLE
fix: add optional flag for hostname fix #6278

### LINKED ISSUE #6278: `hostname` should not be required in `HTTPActiveHealthChecker`
*Description*:
`hostname` is marked as required in the `HTTPActiveHealthChecker`: https://gateway.envoyproxy.io/latest/api/extension_types/#httpactivehealthchecker

this should be optional, as the doc mentions the default behavior:
> Default: HTTPRoute or GRPCRoute hostname.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by yyadavalli**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6278 

Release Notes: Yes/No

### CODE REVIEW

**Comment by arkodg** [comment]
@yyadavalli above tag may not be used in docs, you may need to use `// +optional` to populate the docs column

File: api/v1alpha1/healthcheck_types.go [hunk 1]
```diff
@@ -152,6 +152,7 @@ type HTTPActiveHealthChecker struct {
 	// Hostname defines the HTTP host that will be requested during health checking.
 	// Default: HTTPRoute or GRPCRoute hostname.
 	//
+	// +kubebuilder:validation:Optional
```
Comment (muwaqar) [inline api/v1alpha1/healthcheck_types.go]: use `// +optional` as the rest of places in this file do for optional fields

**Comment by yyadavalli** [comment]
> @yyadavalli above tag may not be used in docs, you may need to use `// +optional` to populate the docs column

Ack, will use the other tag

File: api/v1alpha1/healthcheck_types.go (hunk 1 above)
Comment (muwaqar) [inline api/v1alpha1/healthcheck_types.go]: you need to run `make kube-generate` to reflect these changes in the CRD (the `git status` would show a modified generated file)

**Review by muwaqar — CHANGES_REQUESTED** [review]

**Review by arkodg — APPROVED** [review]
LGTM thanks
