### PR TITLE
bugfix: fix egctl experimental translate with error ns.

### LINKED ISSUE #3982: egctl experimental translate using bad ns
https://github.com/envoyproxy/gateway/blob/8d82ea9748b57a0dada0bea133fbac018f9ba972/internal/cmd/egctl/translate.go#L363-L367

### PR DESCRIPTION
**Pull request by qicz**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3982

### CODE REVIEW

File: internal/cmd/egctl/translate.go [hunk 1]
```diff
@@ -117,6 +118,8 @@ func newTranslateCommand() *cobra.Command {
 	translateCommand.PersistentFlags().StringVarP(&resourceType, "type", "t", string(AllEnvoyConfigType), getValidResourceTypesStr())
 	translateCommand.PersistentFlags().BoolVarP(&addMissingResources, "add-missing-resources", "", false, "Provides dummy resources if missed")
 	translateCommand.PersistentFlags().StringVarP(&dnsDomain, "dns-domain", "", "cluster.local", "DNS domain used by k8s services, default is cluster.local")
+	translateCommand.PersistentFlags().StringVarP(&namespace, "namespace", "n", "envoy-gateway-system", "Namespace where envoy proxy pod are installed.")
```
Comment (arkodg) [inline internal/cmd/egctl/translate.go:121]:
```suggestion
	translateCommand.PersistentFlags().StringVarP(&namespace, "namespace", "n", "envoy-gateway-system", "Namespace where envoy gateway is installed.")
```

**Review by arkodg — APPROVED** [review]
thanks !

**Review by guydc — APPROVED** [review]
