### PR TITLE
set the status when EPP target to a MergeGateways with wrong kind

### LINKED ISSUE #7172: set the status when EPP target to a MergeGateways with wrong kind
this could be improved with a following PR

cc @arkodg

_Originally posted by @zirain in https://github.com/envoyproxy/gateway/pull/7153#discussion_r2415277016_

### PR DESCRIPTION
**Pull request by fabian4**
**What type of PR is this?**

set the status when EPP target to a MergeGateways with wrong kind

**What this PR does / why we need it**:

set the status when EPP target to a MergeGateways with wrong kind

**Which issue(s) this PR fixes**:

Fixes #7172

Release Notes: Yes/No

### CODE REVIEW

File: internal/gatewayapi/envoypatchpolicy.go [hunk 1]
```diff
@@ -52,6 +52,21 @@ func (t *Translator) ProcessEnvoyPatchPolicies(envoyPatchPolicies []*egv1a1.Envo
 		gwXdsIR, ok := xdsIR[irKey]
 		if !ok {
 			// The TargetRef Gateway is not an accepted Gateway, then skip processing.
+			message := fmt.Sprintf(
```
Comment (arkodg) [inline internal/gatewayapi/envoypatchpolicy.go]: can't be done for the non merge gateways case, because a gateway target not found means that it could be part of another gatewayclass or another controller

Comment (fabian4) [reply internal/gatewayapi/envoypatchpolicy.go]: I thought we just mark the status of the envoyPatchPolicies here and attached to the related one or is there any other appropriate approach to mark the status?

Comment (arkodg) [reply internal/gatewayapi/envoypatchpolicy.go]: you'll need to scope the fix to only mergeGateways mode

File: internal/gatewayapi/envoypatchpolicy.go [hunk 2]
```diff
@@ -51,7 +51,24 @@ func (t *Translator) ProcessEnvoyPatchPolicies(envoyPatchPolicies []*egv1a1.Envo
 
 		gwXdsIR, ok := xdsIR[irKey]
 		if !ok {
-			// The TargetRef Gateway is not an accepted Gateway, then skip processing.
+			if t.MergeGateways {
```
Comment (arkodg) [inline internal/gatewayapi/envoypatchpolicy.go]: imo it may be easier to move/copy `gwXdsIR, ok := xdsIR[irKey]` into the above `if` & `else` to avoid this complex logic, and the not found case, is only applicable for mergeGateways

File: internal/gatewayapi/envoypatchpolicy.go [hunk 3]
```diff
@@ -39,6 +41,26 @@ func (t *Translator) ProcessEnvoyPatchPolicies(envoyPatchPolicies []*egv1a1.Envo
 				Name:  refName,
 			}
 
+			gwXdsIR, ok = xdsIR[irKey]
+			if !ok {
+				// The TargetRef Gateway is not an accepted Gateway, then skip processing.
```
Comment (arkodg) [inline internal/gatewayapi/envoypatchpolicy.go]: targetRef here is GatewayClass not Gateway

File: internal/gatewayapi/envoypatchpolicy.go [hunk 4]
```diff
@@ -47,12 +69,11 @@ func (t *Translator) ProcessEnvoyPatchPolicies(envoyPatchPolicies []*egv1a1.Envo
...
 			ancestorRef = getAncestorRefForPolicy(gatewayNN, nil)
-		}
 
-		gwXdsIR, ok := xdsIR[irKey]
-		if !ok {
-			// The TargetRef Gateway is not an accepted Gateway, then skip processing.
-			continue
+			gwXdsIR, ok = xdsIR[irKey]
+			if !ok {
+				continue
```
Comment (arkodg) [inline internal/gatewayapi/envoypatchpolicy.go:76]: can we keep the comment

File: internal/gatewayapi/envoypatchpolicy.go [hunk 5]
```diff
@@ -26,19 +26,41 @@ func (t *Translator) ProcessEnvoyPatchPolicies(envoyPatchPolicies []*egv1a1.Envo
...
+					Reason:  gwapiv1.PolicyReasonInvalid,
+					Message: message,
+				}
+				status.SetResolveErrorForPolicyAncestor(&policy.Status,
+					&ancestorRef,
+					t.GatewayControllerName,
+					policy.Generation,
+					resolveErr,
+				)
+				continue
```
Comment (arkodg) [inline internal/gatewayapi/envoypatchpolicy.go:61]: we can `break` since this is definitive

Comment (fabian4) [reply internal/gatewayapi/envoypatchpolicy.go:61]: Since we are iterating over a list of policies here `(for _, policy := range envoyPatchPolicies)`, using break would terminate the entire loop and prevent subsequent policies in the list from being processed.

Comment (arkodg) [reply internal/gatewayapi/envoypatchpolicy.go:61]: got it thanks

**Review by zirain — APPROVED** [review]

File: internal/gatewayapi/envoypatchpolicy.go [hunk 6]
```diff
@@ -26,19 +26,41 @@ func (t *Translator) ProcessEnvoyPatchPolicies(envoyPatchPolicies []*egv1a1.Envo
...
 				Group: GroupPtr(gwapiv1.GroupName),
 				Kind:  KindPtr(targetKind),
 				Name:  refName,
 			}
 
+			gwXdsIR, ok = xdsIR[irKey]
+			if !ok {
+				// The TargetRef GatewayClass is not an accepted GatewayClass, then skip processing.
+				message := fmt.Sprintf(
+					"TargetRef.Group:%s TargetRef.Kind:%s TargetRef.Namespace:%s TargetRef.Name:%s not found or not accepted (MergeGateways=%t).",
```
Comment (kkk777-7) [inline internal/gatewayapi/envoypatchpolicy.go:48]: nits:
If the target here is only meant to be a GatewayClass, then there may be no need to output the namespace.

File: internal/gatewayapi/testdata/envoypatchpolicy-invalid-target-kind-merge-gateways.out.yaml [hunk 7]
```diff
@@ -1,3 +1,37 @@
...
+      group: gateway.networking.k8s.io
+      kind: Gateway
+      name: gateway-1
+    type: JSONPatch
+  status:
+    ancestors:
+    - ancestorRef:
+        group: gateway.networking.k8s.io
+        kind: GatewayClass
+        name: gateway-1
```
Comment (kkk777-7) [inline internal/gatewayapi/testdata/envoypatchpolicy-invalid-target-kind-merge-gateways.out.yaml:25]: this output may make user confuse.
IMO, How about keeping the original Gateway target in ancestorRef, while also showing a message indicating that a GatewayClass should be specified and displaying an Invalid condition?

**Review by kkk777-7 — APPROVED** [review]

**Comment by kkk777-7** [comment]
LGTM, thanks!
my comments can handle in follow-up PR.
