### PR TITLE
fix: check error first before accessing the result during translation

### LINKED ISSUE #1917: Panic because of invalid result during xDS translation
*Description*:
When integrating Envoy Gateway and Envoy Gateway Extension service, I observed that during the xDS translation result, when an error occurred, it would be panicking because there was some operation to the result variable before the error check.
https://github.com/envoyproxy/gateway/blob/7d9e16e4997e7118d70ea910a6ef9d0732426878/internal/xds/translator/runner/runner.go#L80-L98

*Repro steps*:

In my scenario, we can simply produce an error from one of the hooks registered through the Envoy Gateway Extension service. Then you will see Envoy Gateway no longer up and running because of panicking.

*Environment*:
Tested on Envoy Gateway v0.5.0, but the code also persists in the main branch.

*Logs*:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1792a64]

goroutine 97 [running]:
github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).subscribeAndTranslate.func1({{0x400086d170?, 0x1733654?}, 0x78?, 0x4000138f50?})
        /home/runner/work/gateway/gateway/internal/xds/translator/runner/runner.go:79 +0x1a4
github.com/envoyproxy/gateway/internal/message.HandleSubscription[...](0x2112300, 0x4000d4df88?)
        /home/runner/work/gateway/gateway/internal/message/watchutil.go:36 +0x104
github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).subscribeAndTranslate(0x40003ba180, {0x20f19b8?, 0x4000528410?})
        /home/runner/work/gateway/gateway/internal/xds/translator/runner/runner.go:52 +0x70
created by github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).Start
        /home/runner/work/gateway/gateway/internal/xds/translator/runner/runner.go:45 +0x1f8
```

*Expectation*:

The error during xDS translation should be returned and logged instead of panicking.

### PR DESCRIPTION
**Pull request by ardikabs**
Fixes #1917

### CODE REVIEW

**Comment by ardikabs** [comment]
it seems that the e2e-test is a bit flaky. It succeeded on v1.28, but failed on v1.26.6, am I missing something here?
/cc @arkodg

File: internal/xds/translator/runner/runner.go [hunk 1]
```diff
@@ -78,6 +78,10 @@ func (r *Runner) subscribeAndTranslate(ctx context.Context) {
 				}
 
 				result, err := t.Translate(val)
+				if err != nil {
```
Comment (arkodg) [inline internal/xds/translator/runner/runner.go:81]: you can't `return` here, this is an endless loop, one bad config should not cause the entire translator to exit

Comment (ardikabs) [reply internal/xds/translator/runner/runner.go:81]: sure, let me change it to move under the `else` directive.

Comment (ardikabs) [reply internal/xds/translator/runner/runner.go:81]: out of curiosity, @arkodg if we are not allowed to `return` this, then why this is allowed here? 
https://github.com/envoyproxy/gateway/blob/2ba50ea89e7a7342f3c44962715201b2d382b862/internal/provider/kubernetes/controller.go#L1077-L1093
Because I thought that process was just a callable function, that would be executed on every incoming data.

Comment (arkodg) [reply internal/xds/translator/runner/runner.go:81]: that is returning from the function, not from the go routine

File: internal/xds/translator/runner/runner.go [hunk 2]
```diff
@@ -78,21 +78,20 @@ func (r *Runner) subscribeAndTranslate(ctx context.Context) {
...
-					}
-					r.EnvoyPatchPolicyStatuses.Store(key, e.Status)
-				}
-				// Discard the EnvoyPatchPolicyStatuses to reduce memory footprint
-				result.EnvoyPatchPolicyStatuses = nil
-
 				if err != nil {
 					r.Logger.Error(err, "failed to translate xds ir")
 				} else {
+					// Publish EnvoyPatchPolicyStatus
```
[the remark this answers is not in the document]
Comment (ardikabs) [reply internal/xds/translator/runner/runner.go:84]: the issue is when an error occurs, the `result` variable is nil, then empty values wouldn't be a problem, but the access to the value is the problem.

[the remark this answers is not in the document]
Comment (ardikabs) [reply internal/xds/translator/runner/runner.go:84]: as we can see here, 
https://github.com/envoyproxy/gateway/blob/2ba50ea89e7a7342f3c44962715201b2d382b862/internal/xds/translator/translator.go#L60-L97

File: internal/xds/translator/runner/runner.go (hunk 1 above)
Comment (ardikabs) [reply internal/xds/translator/runner/runner.go:81]: sure, just a side note, I forgot to mention as well, that the patch that I work on now is actually running in my org staging environment, and it works well.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

File: internal/xds/translator/runner/runner.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (arkodg) [reply internal/xds/translator/runner/runner.go]: thanks for root causing the panic

**Review by Xunzhuo — APPROVED** [review]
LGTM
