### PR TITLE
fix: use per-route ratelimit filter

### LINKED ISSUE #8707: BackendTrafficPolicy rate limiting attached to Gateway only applies to one listener
### Description
  When applying a `BackendTrafficPolicy` (BTP) configured with Global Rate Limiting to a `Gateway` resource (via `targetRefs`), the rate limiting configuration is only applied to the first listener defined on the Gateway (typically the first domain's HTTP and HTTPS listeners).

  Traffic routed through subsequent listeners (other domains) completely bypasses the rate limit policy. According to the Gateway API policy attachment model, a policy targeting a Gateway
  should apply to all listeners on that Gateway.

  ### Steps to Reproduce
  1. Deploy Envoy Gateway with Redis/Valkey rate limiting enabled in the `EnvoyGateway` config.
  2. Create a `Gateway` with multiple listeners spanning different domains (e.g., 4 listeners total: HTTP/HTTPS for `app1.example.com` and HTTP/HTTPS for `app2.example.com`).
  3. Create a `BackendTrafficPolicy` targeting the `Gateway` with a global rate limit:

  ```yaml
  apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: BackendTrafficPolicy
  metadata:
    name: global-rate-limit
  spec:
    targetRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: multi-listener-gateway
    rateLimit:
      type: Global
      global:
        rules:
          - clientSelectors:
              - sourceCIDR:
                  type: Distinct
                  value: 0.0.0.0/0
            limit:
              requests: 5
              unit: Minute
```

  4. Send >5 requests to app1.example.com.
    - Result: Requests are rate-limited (429 Too Many Requests) as expected.
  5. Send >5 requests to app2.example.com.
    - Result: Requests are successful (200 OK) and bypass the rate limit completely.

  ### Expected Behavior

  The BackendTrafficPolicy rate limit should apply uniformly to all listeners and domains configured on the target Gateway, enforcing the per-IP rate limit across the entire Gateway surface
  area.

 ### Actual Behavior

  The rate limit xDS configuration (filter and route actions) is only generated/applied to the first two listeners. All subsequent listeners do not have the rate limit filter enforced.

  ### Environment

  - Envoy Gateway Version:  v1.7.1
  - Kubernetes Version:  v1.33
  - Install Method: Helm
  - Infrastructure Provider:  AWS EKS

### PR DESCRIPTION
**Pull request by zirain**
fixes: https://github.com/envoyproxy/gateway/issues/8707

use use per-route ratelimit configuration for non-shared rules.

### CODE REVIEW

File: internal/xds/translator/ratelimit.go [hunk 1]
```diff
@@ -170,23 +170,27 @@ func createRateLimitFilter(t *Translator, irListener *ir.HTTPListener, domain, f
...
 
 // patchRouteWithRateLimit builds rate limit actions and appends to the route.
-func patchRouteWithRateLimit(route *routev3.Route, irRoute *ir.HTTPRoute) error { //nolint:unparam
+func patchRouteWithRateLimit(irListener *ir.HTTPListener, route *routev3.Route, irRoute *ir.HTTPRoute) error { //nolint:unparam
 	// Return early if no rate limit config exists.
 	xdsRouteAction := route.GetRoute()
 	if !isValidGlobalRateLimit(irRoute) || xdsRouteAction == nil {
 		return nil
 	}
-	rateLimits, costSpecified := buildRouteRateLimits(irRoute)
```
Comment (kkk777-7) [inline internal/xds/translator/ratelimit.go:179]: Just Question:
is it right that we don't have to care about `costSpecified` because of Envoy version?

found previous context:
https://github.com/envoyproxy/gateway/pull/5035/changes#diff-3e370ab0c69cb6df1c58639c500e3049922dedf33567957dfed122337da7d601R138-R157

File: internal/xds/translator/ratelimit.go [hunk 2]
```diff
@@ -222,6 +229,9 @@ func buildRouteRateLimits(route *ir.HTTPRoute) (rateLimits []*routev3.RateLimit,
 
 	// Iterate over each rule in the global rate limit configuration.
 	for rIdx, rule := range global.Rules {
+		if isRuleShared(rule) {
+			hasSharedRule = true
```
Comment (kkk777-7) [inline internal/xds/translator/ratelimit.go:233]: what happen if exists both shared rule and non-shared rule?

File: internal/xds/translator/ratelimit.go (hunk 1 above)
Comment (zirain) [reply internal/xds/translator/ratelimit.go:179]: I think it's fine for now.
cc @arkodg

File: internal/xds/translator/ratelimit.go (hunk 2 above)
Comment (zirain) [reply internal/xds/translator/ratelimit.go:233]: if there's any shared rule we use same logic as before.

Comment (zirain) [reply internal/xds/translator/ratelimit.go:233]: let me update the testcase.

Comment (zirain) [reply internal/xds/translator/ratelimit.go:233]: updated in https://github.com/envoyproxy/gateway/pull/8741/commits/3ad6fdb31e1a63b6c0e7dfadcbc9f8d327e39622

**Review by kkk777-7 — APPROVED** [review]

**Comment by kkk777-7** [comment]
LGTM, thanks!

**Review by rudrakhp — APPROVED** [review]
