### PR TITLE
fix: deep copy status in translator layer to avoid race

### LINKED ISSUE #8771: Go panic in control plane
*Description*:

```
2026-04-11T03:05:01.539210647Z 2026-04-11T03:05:01.539Z INFO    gateway-api     gatewayapi/route.go:372 setting 503 direct response in routes due to no ready endpoints        {"runner": "gateway-api", "trace_id": "0195624f15cc725cfaabb15c6d6948c1", "span_id": "00471239e7f37bb5", "routes": ["httproute/<redacted>/rule/0/match/0"]}
2026-04-11T03:05:01.548388789Z panic: reflect: slice index out of range
2026-04-11T03:05:01.548449780Z 
2026-04-11T03:05:01.548455500Z goroutine 183 [running]:
2026-04-11T03:05:01.548460240Z reflect.Value.Index({0x3303720?, 0xc002f2df60?, 0x197?}, 0x35e8420?)
2026-04-11T03:05:01.548477150Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/value.go:1407 +0x167
2026-04-11T03:05:01.548613752Z reflect.deepValueEqual({0x3303720?, 0xc00260df60?, 0xc00116ca58?}, {0x3303720?, 0xc002f2df60?, 0x98?}, 0xc00116daa8)
2026-04-11T03:05:01.548653463Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:113 +0x1187
2026-04-11T03:05:01.548669233Z reflect.deepValueEqual({0x36da040?, 0xc00260df60?, 0xc00116cc20?}, {0x36da040?, 0xc002f2df60?, 0x98?}, 0xc00116daa8)
2026-04-11T03:05:01.548673713Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:130 +0x10e5
2026-04-11T03:05:01.548724704Z reflect.deepValueEqual({0x36da4c0?, 0xc00260df60?, 0x113?}, {0x36da4c0?, 0xc002f2df60?, 0x1274a8b?}, 0xc00116daa8)
2026-04-11T03:05:01.548731824Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:130 +0x10e5
2026-04-11T03:05:01.548825366Z reflect.deepValueEqual({0x394f180?, 0xc00260de00?, 0xc00116cfb0?}, {0x394f180?, 0xc002f2de00?, 0x98?}, 0xc00116daa8)
2026-04-11T03:05:01.548833696Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:130 +0x10e5
2026-04-11T03:05:01.549093930Z reflect.deepValueEqual({0x3c94d80?, 0xc005b896b8?, 0xc00116d178?}, {0x3c94d80?, 0xc003668c38?, 0xc0059d2248?}, 0xc00116daa8)
2026-04-11T03:05:01.549111211Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:127 +0xcd3
2026-04-11T03:05:01.549648570Z reflect.deepValueEqual({0x3310e60?, 0xc000ed88a8?, 0x0?}, {0x3310e60?, 0xc001367668?, 0x6?}, 0xc00116daa8)
2026-04-11T03:05:01.549660160Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:113 +0x11b5
2026-04-11T03:05:01.549850723Z reflect.deepValueEqual({0x3cb1a40?, 0xc000ed8848?, 0xc00116d508?}, {0x3cb1a40?, 0xc001367608?, 0x930a4304ca366a03?}, 0xc00116daa8)
2026-04-11T03:05:01.549860293Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:130 +0x10e5
2026-04-11T03:05:01.549865343Z reflect.deepValueEqual({0x38819a0?, 0xc0061b5920?, 0xc00116d6d0?}, {0x38819a0?, 0xc002646e10?, 0x4a2200?}, 0xc00116daa8)
2026-04-11T03:05:01.549869523Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:127 +0xcd3
2026-04-11T03:05:01.549873823Z reflect.deepValueEqual({0x35378e0?, 0xc005380ca8?, 0xc00116d898?}, {0x35378e0?, 0xc004de2dc8?, 0xc0015d7764?}, 0xc00116daa8)
2026-04-11T03:05:01.549878293Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:113 +0x11b5
2026-04-11T03:05:01.549882713Z reflect.deepValueEqual({0x35ee9a0?, 0xc005380ca8?, 0xc0014d3900?}, {0x35ee9a0?, 0xc004de2dc8?, 0xc001261c00?}, 0xc00116daa8)
2026-04-11T03:05:01.549886664Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:127 +0xcd3
2026-04-11T03:05:01.549921224Z reflect.DeepEqual({0x35ee9a0?, 0xc005380ca8?}, {0x35ee9a0?, 0xc004de2dc8?})
2026-04-11T03:05:01.549928044Z  /opt/hostedtoolcache/go/1.25.8/x64/src/reflect/deepequal.go:238 +0x250
2026-04-11T03:05:01.550866870Z github.com/envoyproxy/gateway/internal/gatewayapi/resource.(*ControllerResourcesContext).Equal(0x3?, 0x2d?)
2026-04-11T03:05:01.550887140Z  /home/runner/work/gateway/gateway/internal/gatewayapi/resource/resource.go:190 +0x57
2026-04-11T03:05:01.550892460Z github.com/telepresenceio/watchable.DeepEqual[...](0xc005380d20, 0xc004de2e40)
2026-04-11T03:05:01.550897240Z  /home/runner/go/pkg/mod/github.com/telepresenceio/watchable@v0.0.0-20220726211108-9bb86f92afa7/valtypes.go:101 +0x78
2026-04-11T03:05:01.550902110Z github.com/telepresenceio/watchable.(*Map[...]).coalesce.func2()
2026-04-11T03:05:01.550906890Z  /home/runner/go/pkg/mod/github.com/telepresenceio/watchable@v0.0.0-20220726211108-9bb86f92afa7/map.go:356 +0xec
2026-04-11T03:05:01.550911851Z github.com/telepresenceio/watchable.(*Map[...]).coalesce(0x8f07fa0, {0x8e90eb0, 0xc000a3fb30}, 0xc00097f430, 0xc000be8a10, 0xc000be8a80, 0xc000ff42a0)
2026-04-11T03:05:01.550916301Z  /home/runner/go/pkg/mod/github.com/telepresenceio/watchable@v0.0.0-20220726211108-9bb86f92afa7/map.go:393 +0x67f
2026-04-11T03:05:01.550920431Z created by github.com/telepresenceio/watchable.(*Map[...]).SubscribeSubset in goroutine 127
2026-04-11T03:05:01.550924771Z  /home/runner/go/pkg/mod/github.com/telepresenceio/watchable@v0.0.0-20220726211108-9bb86f92afa7/map.go:281 +0x145
```

*Repro steps*:

Not sure how to replicate - transient error in logs. 

*Environment*:

envoyproxy/gateway:v1.7.1
K8s (EKS) 1.33

*Logs*:

(above)

### PR DESCRIPTION
**Pull request by rudrakhp**
**What type of PR is this?**

fix: deep copy status in translator layer to avoid race

**What this PR does / why we need it**:
`DeepCopy()` calls were removed in #6940 but are required to avoid race between `deepEqual()` in watchable coalesce routine and status updates in gateway api translator routine. Replaced plain shallow copy with deep copy only status.

Also includes a minor spelling fix `SeverOptions` -> `ServerOptions`

**Which issue(s) this PR fixes**:

Fixes #8771 

Release Notes: Yes

### CODE REVIEW

File: internal/gatewayapi/backend.go [hunk 1]
```diff
@@ -203,3 +204,11 @@ func validateIP(epIP *egv1a1.IPEndpoint, runningOnHost bool) status.Error {
 	}
 	return nil
 }
+
+// deepCopyBackendStatus returns a shallow copy with a deep-copied Status field.
+// Status is mutated during translation and shares a pointer with the watchable coalesce goroutine.
+func deepCopyBackendStatus(in *egv1a1.Backend) *egv1a1.Backend {
+	out := *in
+	in.Status.DeepCopyInto(&out.Status)
```
Comment (zirain) [inline internal/gatewayapi/backend.go:212]: why not use backend.DeepCopy directly? which is better for understanding.

Comment (rudrakhp) [reply internal/gatewayapi/backend.go:212]: It is less efficient than this as we only need deep copy for status which is modified. Rest of the policy can be a shallow copy. We were already doing complete deep copy before #6940 tried to optimize it.

File: internal/gatewayapi/securitypolicy.go [hunk 2]
```diff
@@ -146,7 +146,7 @@ func (t *Translator) ProcessSecurityPolicies(
 			if currTarget.Kind != resource.KindGateway && currTarget.SectionName != nil {
 				policy, found := handledPolicies[policyName]
 				if !found {
-					policy = currPolicy
+					policy = deepCopySecurityPolicyStatus(currPolicy)
```
Comment (arkodg) [inline internal/gatewayapi/securitypolicy.go]: cant we just do it once in L142 ?

Comment (rudrakhp) [reply internal/gatewayapi/securitypolicy.go]: makes sense, creating copies once in `XCopiesWithStatusDeepCopy()` before reusing them.

**Review by arkodg — APPROVED** [review]
LGTM thanks

**Review by zirain — APPROVED** [review]
