### PR TITLE
fix(status): align BackendTLSPolicy ResolvedRefs reason with Gateway API

### LINKED ISSUE #7790: Fix invalid ResolvedRefs condition in BackendTLSPolicy
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: The expected value isn't returned, etc.

Relates to https://github.com/kubernetes-sigs/gateway-api/pull/4360#discussion_r2635363000

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by Aditya7880900936**
**What type of PR is this?**

fix: correct BackendTLSPolicy ResolvedRefs reason

---

**What this PR does / why we need it**:

Envoy Gateway was setting the `ResolvedRefs=False` condition reason to
`InvalidKind` for BackendTLSPolicy when a referenced CA certificate could
not be resolved.

According to Gateway API conformance and the BackendTLSPolicy specification,
this scenario must use the `InvalidCACertificateRef` reason. This PR updates
the status reason and adjusts golden test outputs to align with the expected
behavior.

---

**Which issue(s) this PR fixes**:

Fixes #7790

---

Release Notes: No

### CODE REVIEW

**Comment by Aditya7880900936** [comment]
The conformance test failures appear to be related to GatewayClass acceptance timing (`proxy-config not found / context deadline exceeded`) and not BackendTLSPolicy behavior.

My change only affects BackendTLSPolicy status reason mapping and does not touch GatewayClass, EnvoyProxy, or control-plane startup logic.

Happy to re-run or adjust if maintainers think this is related.

**Comment by Aditya7880900936** [comment]
Hi @arkodg ,
just tagging you for a quick look when you get a chance.

This PR only updates the BackendTLSPolicy status reason mapping; the current failures appear to be unrelated conformance flakes.

Happy to rebase, rerun, or adjust based on your guidance. Thanks!

**Comment by Aditya7880900936** [comment]
Hi @zirain 👋

Apologies for the ping — just looking for a quick sanity check when you get a chance.

This PR aligns BackendTLSPolicy ResolvedRefs status reason with the Gateway API spec.  
The current CI failures appear to be unrelated conformance flakes (GatewayClass / proxy startup timing), not caused by this change.

I’ve added context above and can re-run or rebase if needed.  
Thanks for taking a look!

**Comment by arkodg** [comment]
instead of deleting the logic, is there an issue with the current logic of
```
	if errors.Is(err, ErrBackendTLSPolicyInvalidKind) {
			reason = gwapiv1.BackendTLSPolicyReasonInvalidKind
		}
```

is the right `err` being returned ?

**Comment by Aditya7880900936** [comment]
Hi @arkodg ,
Good question — the error *is* being returned, but it’s semantically overloaded.

`ErrBackendTLSPolicyInvalidKind` is currently returned from `getCaCertsFromCARefs` when **no CA bundle could be resolved** (e.g. missing key, missing object, empty result), not when the reference `kind` itself is invalid.

Because of that, the error does not reliably indicate an invalid reference kind per the Gateway API semantics. In practice it represents a CA resolution failure, which the spec and conformance tests map to `InvalidCACertificateRef`.

That’s why I removed the conditional mapping — keying `ResolvedRefs` on this error was causing valid CA-resolution failures to be reported as `InvalidKind`.

If you think we should distinguish these cases more explicitly, I’m happy to follow up with a separate change that introduces a dedicated error for truly invalid reference kinds.

**Comment by arkodg** [comment]
https://github.com/envoyproxy/gateway/blob/721e62dd9e71e9e63f19d0009e5b67ac25b96f5c/internal/gatewayapi/backendtlspolicy.go#L517 needs to be improved to better decipher between invalid kind and other failure cases

**Comment by Aditya7880900936** [comment]
That makes sense 👍

I’ll update `getCaCertsFromCARefs` to explicitly return an error for truly invalid
reference kinds and use a separate error for CA resolution failures. That should
allow `ResolvedRefs` to correctly distinguish `InvalidKind` vs
`InvalidCACertificateRef`.

I’ll push an updated revision shortly.

**Comment by Aditya7880900936** [comment]
Hi @arkodg 
Thanks for the review and the clarification.

I’ve updated the error classification for CA resolution failures so that missing or unusable CA bundles use a more accurate error, allowing the status to consistently report InvalidCACertificateRef without altering validation logic.

All tests pass locally (go test ./..., make test).

**Comment by jukie** [comment]
This looks good, thanks! Could you confirm that the new conformance test in https://github.com/kubernetes-sigs/gateway-api/pull/4360 passes here?

**Comment by Aditya7880900936** [comment]
Hi @jukie @arkodg 
Thanks for the heads-up.

It looks like the current CI failures are occurring during Helm chart linting, before the Gateway API conformance assertions run. I’ve updated the branch to pick up the latest changes from main and will confirm the result once the conformance tests complete.

File: internal/gatewayapi/backendtlspolicy.go [hunk 1]
```diff
@@ -515,7 +513,7 @@ func (t *Translator) getCaCertsFromCARefs(
 	}
 
 	if ca == "" {
-		return nil, ErrBackendTLSPolicyInvalidKind
+		return nil, ErrBackendTLSPolicyNoValidCACertificate
```
Comment (arkodg) [inline internal/gatewayapi/backendtlspolicy.go:536]: more plumbing is needed here
ca == "" could mean a `Get` returned nothing or it never entered the `for` loop block or it never entered the `switch` block

**Comment by Aditya7880900936** [comment]
Hi @arkodg ,
Thanks for the review!
I’ve updated the implementation to distinguish invalid CA kinds vs missing/empty CA bundles, updated the expected test output, and ensured DCO compliance.
All gatewayapi tests are passing locally. Please let me know if you’d like this handled differently.

**Comment by Aditya7880900936** [comment]
Hi @arkodg, just a gentle follow-up in case this got buried.
Happy to make any further changes if needed. Thanks!

**Comment by arkodg** [comment]
can you add a test case

File: internal/gatewayapi/backendtlspolicy.go (hunk 1 above)
Comment (Aditya7880900936) [reply internal/gatewayapi/backendtlspolicy.go:536]: its updated now

**Comment by Aditya7880900936** [comment]
Hi @arkodg, thanks for the note.

I’ve added coverage through the existing Gateway API golden tests. The file
`internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml` now covers both cases:

supported CA ref kinds where the CA data is missing, and

unsupported / invalid CA ref kinds.

This validates the updated status reasons end-to-end with the expected output.
Happy to add or adjust anything further if you had something else in mind.

Thanks!

File: internal/gatewayapi/backendtlspolicy.go [hunk 2]
```diff
@@ -23,6 +22,9 @@ import (
 )
 
 var ErrBackendTLSPolicyInvalidKind = fmt.Errorf("no CA bundle found in referenced ConfigMap, Secret, or ClusterTrustBundle")
```
Comment (arkodg) [inline internal/gatewayapi/backendtlspolicy.go]:
```suggestion
var ErrBackendTLSPolicyInvalidKind = fmt.Errorf("unsupported reference kind, supported kinds are ConfigMap, Secret, and ClusterTrustBundle")
```

**Comment by Aditya7880900936** [comment]
Friendly Ping @arkodg ,
i just wanna know is there any thing need to be updated .

**Comment by arkodg** [comment]
does a YAML test case exist that verifies the code path you added

**Comment by Aditya7880900936** [comment]
Yes — the existing golden test
`internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml`
already covers the code path added in this PR.

It includes:

- an invalid CA ref kind, which triggers `ErrBackendTLSPolicyInvalidKind`, and

- a valid ref kind with no CA data, which triggers `ErrBackendTLSPolicyNoValidCACertificate`.

The expected status output in the golden file was updated as part of this change to reflect the new branching logic.

If you’d prefer this to be split into a more explicit test case or renamed for clarity, I’m happy to do that.

**Comment by arkodg** [comment]
CI is failing

**Comment by Aditya7880900936** [comment]
Hi @arkodg ,
I ran `make lint` and `make generate` locally.
Since this change only affects `BackendTLSPolicy` logic and testdata, no generated artifacts were included.
All relevant `gatewayapi` tests are passing.

**Comment by arkodg** [comment]
here is the error from the CI, it is expecting a specific order, you can use `make testdata` to generate this

```
===========> ERROR: Some files need to be updated
diff --git a/internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml b/internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml
index 2b0a7f3..fb88e9b 100644
--- a/internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml
+++ b/internal/gatewayapi/testdata/backendtlspolicy-invalid-ca.out.yaml
@@ -59,12 +59,14 @@ backendTLSPolicies:
         sectionName: http
       conditions:
       - lastTransitionTime: null
-        message: Unsupported reference kind, supported kinds are ConfigMap, Secret, and ClusterTrustBundle.
+        message: Unsupported reference kind, supported kinds are ConfigMap, Secret,
+          and ClusterTrustBundle.
         reason: InvalidKind
         status: "False"
         type: Accepted
       - lastTransitionTime: null
-        message: Unsupported reference kind, supported kinds are ConfigMap, Secret, and ClusterTrustBundle.
+        message: Unsupported reference kind, supported kinds are ConfigMap, Secret,
+          and ClusterTrustBundle.
         reason: InvalidKind
         status: "False"
         type: ResolvedRefs
         ```

**Comment by Aditya7880900936** [comment]
Thanks @arkodg! I regenerated the testdata using `make testdata` to match the expected order and pushed the updated output.

**Comment by arkodg** [comment]
```
TestGatewayAPIConformance/BackendTLSPolicyInvalidKind/BackendTLSPolicy_with_a_single_invalid_CACertificateRef_has_a_Accepted_Condition_with_status_False_and_Reason_NoValidCACertificate
```

is failing

**Comment by Aditya7880900936** [comment]
Thanks @arkodg , found the issue. For invalid CA ref kind, Accepted must still use NoValidCACertificate while ResolvedRefs uses InvalidKind. Fixed the logic and regenerated testdata.

**Comment by zirain** [comment]
Remove this from v1.5, this's need Gateway API v1.4.
